AVR32 - FAT Services: reader_txt.h File Reference
reader_txt.h File Reference
Detailed Description
FAT 12/16/32 text reader service.
This file defines a useful set of functions for the text file accesses on AVR32 devices.
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file reader_txt.h.
#include "fs_com.h"
#include "fat.h"
Functions
void reader_txt_beg (void)
This function goes at the beginning of file and read the text header.
void reader_txt_close (void)
Close text file.
U16 reader_txt_get_line (Bool b_unicode, FS_STRING string, U16 u16_str_size)
This function fills an ASCII buffer with the current text line of opened file.
Bool reader_txt_jump_line (U16 nb_line)
This function jumps text lines.
Bool reader_txt_new (const FS_STRING sz_name, U8 u8_txt_format)
Create a new text file.
Bool reader_txt_open (Bool b_readonly)
Open a selected text file in the current navigator.
void reader_txt_select_format (U8 u8_txt_format)
This function allow to select the text format to decode.
Function Documentation
void reader_txt_beg (void)
This function goes at the beginning of file and read the text header.
Definition at line 103 of file reader_txt.c.
References file_read_buf(), file_seek(), fs_g_nav_entry, FS_SEEK_SET, Fs_management_entry::u8_txt_format, UNI_MAX_HEADER_SIZE, unicode_header_get(), and unicode_header_scan().
Referenced by pl_main_open(), pl_nav_readentry(), pl_nav_setpos(), and reader_txt_open().
{
   // Table to store the header of text file
   U8    string_header[UNI_MAX_HEADER_SIZE];
   file_seek( 0, FS_SEEK_SET );  // go to at the beginning of file
   // Read the header to detect the text format (ASCII, UNICODE LE, UNICODE BE, UTF8)
   memset( string_header, 0, UNI_MAX_HEADER_SIZE );     // By default ASCII
   file_read_buf( string_header , UNI_MAX_HEADER_SIZE );
   fs_g_nav_entry.u8_txt_format = unicode_header_scan( string_header );
   // Set cursor after header
   file_seek( unicode_header_get( string_header, fs_g_nav_entry.u8_txt_format ), FS_SEEK_SET );
}
void reader_txt_close (void)
Close text file.
Definition at line 271 of file reader_txt.c.
References file_close().
Referenced by pl_main_new().
{
   file_close();
}
U16 reader_txt_get_line (Bool b_unicode, FS_STRING string, U16 u16_str_size)
This function fills an ASCII buffer with the current text line of opened file.
Parameters:
b_unicode TRUE to return a unicode string (UTF16), ASCII otherwise over there
string string used to store text line
u16_str_size maximum size of string (unit character, 1B for ASCII, 2B for unicode)
Returns:
size of the line (may be < or > at u16_str_size)
0, in case of error
//! This routine remove the character '\n' '\r'
//!
Definition at line 142 of file reader_txt.c.
References file_eof(), file_getc(), file_read_buf(), file_seek(), FS_EOF, FS_ERR_EOF, fs_g_nav_entry, fs_g_status, FS_SEEK_CUR_RE, nav_checkdisk_disable(), nav_checkdisk_enable(), Fs_management_entry::u8_txt_format, UNI_MAX_UTF8_SIZE, UNI_TYPE_UTF16BE, UNI_TYPE_UTF16LE, UNI_TYPE_UTF8, and utf8_to_unicode().
Referenced by pl_main_readline(), and reader_txt_jump_line().
{
   U8    utf8[UNI_MAX_UTF8_SIZE];
   U8    size_utf8_buf=0;
   U8    size_utf8_dec=0;
   U16   u16_size_line = 1;   // 1 to compute null terminator
   U16   u16_unicode;
   Bool  b_error = FALSE;
   nav_checkdisk_disable();   // To optimize speed
   while( 0 == file_eof() && !b_error )
   {
      // Get a unicode value
      switch( fs_g_nav_entry.u8_txt_format )
      {
         case UNI_TYPE_UTF8:
         // Remove UTF8 codes used
         if( 0 != size_utf8_dec )
         {
            U8 u8_i;
            for( u8_i=0; u8_i<(UNI_MAX_UTF8_SIZE-size_utf8_dec); u8_i++ )
            {
               utf8[u8_i]=utf8[u8_i+size_utf8_dec];
            }
            size_utf8_buf -= size_utf8_dec;
            size_utf8_dec =0;
         }
         // Complet UTF8 array
         size_utf8_buf += file_read_buf( &utf8[size_utf8_buf], (UNI_MAX_UTF8_SIZE-size_utf8_buf) );
         // Decode UTF8 to unicode
         size_utf8_dec = utf8_to_unicode( &utf8[0], &u16_unicode );
         break;
         case UNI_TYPE_UTF16BE:
         MSB(u16_unicode) = file_getc();
         LSB(u16_unicode) = file_getc();
         if (LSB(u16_unicode) == (FS_EOF & 0xFF) && fs_g_status != FS_ERR_EOF)
           b_error = TRUE;
         break;
         case UNI_TYPE_UTF16LE:
         LSB(u16_unicode) = file_getc();
         MSB(u16_unicode) = file_getc();
         if (MSB(u16_unicode) == (FS_EOF & 0xFF) && fs_g_status != FS_ERR_EOF)
           b_error = TRUE;
         break;
         default: // ASCII or other
         u16_unicode = file_getc();
         if (u16_unicode == FS_EOF && fs_g_status != FS_ERR_EOF)
           b_error = TRUE;
         break;
      }
      // Check character to remove
      if( '\r' == u16_unicode )
         continue;   // Ignore character
      // Check end of line
      if((  0  == u16_unicode )
      || ('\n' == u16_unicode ) )
         break;      // End of line
      u16_size_line++;
      // Fill string
      if( 1 < u16_str_size )
      {
         if( b_unicode )
         {
            ((FS_STR_UNICODE)string)[0] = u16_unicode;
         }else{
            string[0] = u16_unicode;
         }
         string += (b_unicode? 2 : 1 );
         u16_str_size--;
      }
   }
   // HERE, the line is readed
   if( UNI_TYPE_UTF8 == fs_g_nav_entry.u8_txt_format )
   {
      // Re position cursor on next UTF8
      file_seek( (size_utf8_buf-size_utf8_dec) , FS_SEEK_CUR_RE );
   }
   // Handle error cases
   if (b_error)
   {
     nav_checkdisk_enable();
     return 0;
   }
   // Add Null terminate
   if( 0 != u16_str_size )
   {
      if( b_unicode )
      {
         ((FS_STR_UNICODE)string)[0] = 0;
      }else{
         string[0] = 0;
      }
   }
   nav_checkdisk_enable();
   return u16_size_line;
}
Bool reader_txt_jump_line (U16 nb_line)
This function jumps text lines.
Parameters:
nb_line number of lines to jump
Returns:
FALSE in case of error
Definition at line 256 of file reader_txt.c.
References file_eof(), and reader_txt_get_line().
{
   while( 0 != nb_line )
   {
      if( 0 != file_eof() )
         return FALSE;
      reader_txt_get_line( FALSE, NULL, 0 );
      nb_line--;
   }
   return TRUE;
}
Bool reader_txt_new (const FS_STRING sz_name, U8 u8_txt_format)
Create a new text file.
Parameters:
sz_name contains the file name (ASCII or UNICODE)
u8_txt_format text format to use (UNI_TYPE_UTF8, UNI_TYPE_UTF16BE, UNI_TYPE_UTF16LE, UNI_TYPE_ASCII)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 82 of file reader_txt.c.
References file_write_buf(), fs_g_nav_entry, nav_file_create(), Fs_management_entry::u8_txt_format, UNI_MAX_HEADER_SIZE, and unicode_header_get().
Referenced by pl_main_new().
{
   // Table to store the header of text file
   U8    string_header[UNI_MAX_HEADER_SIZE];
   U8    u8_header_size;
   // Create empty file
   if ( !nav_file_create( sz_name ))
      return FALSE;
   fs_g_nav_entry.u8_txt_format = u8_txt_format;
   // Write at the beginning of file the text header
   u8_header_size = unicode_header_get( string_header, fs_g_nav_entry.u8_txt_format );
   file_write_buf( string_header , u8_header_size );
   return TRUE;
}
Bool reader_txt_open (Bool b_readonly)
Open a selected text file in the current navigator.
Parameters:
b_readonly TRUE to open the text file in read only access
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 65 of file reader_txt.c.
References file_open(), FOPEN_MODE_R, FOPEN_MODE_R_PLUS, and reader_txt_beg().
Referenced by pl_main_open().
{
   if( !file_open( (b_readonly)? FOPEN_MODE_R : FOPEN_MODE_R_PLUS ) )
      return FALSE; // Open error
   reader_txt_beg();
   return TRUE;
}
void reader_txt_select_format (U8 u8_txt_format)
This function allow to select the text format to decode.
Parameters:
u8_txt_format text format selected (UNI_TYPE_UTF8, UNI_TYPE_UTF16BE, UNI_TYPE_UTF16LE, UNI_TYPE_ASCII)
Definition at line 123 of file reader_txt.c.
References fs_g_nav_entry, and Fs_management_entry::u8_txt_format.
{
   fs_g_nav_entry.u8_txt_format = u8_txt_format;
}