AVR32 - FAT Services: nav_filterflat.h File Reference
nav_filterflat.h File Reference
Detailed Description
FAT 12/16/32 Services.
This plug-in allow a navigation in filter and flat mode This plug-in is connected on the navigation module. The filter mode includes in the file list directories, sub directories and only files and sub files corresponding at a extension
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file nav_filterflat.h.
#include "fs_com.h"
Functions
Bool nav_filterflat_cd (void)
This function enters in the selected directory.
Bool nav_filterflat_findname (const FS_STRING sz_name, Bool b_match_case)
This function searches a file name in file list filtered.
U16 nav_filterflat_get (void)
This function returns the position of selected file in filtered file list.
Bool nav_filterflat_goto (U16 u16_newpos)
This function goes to a position in filtered file list.
Bool nav_filterflat_gotoparent (void)
This function goes to at the parent directory.
Bool nav_filterflat_mount (void)
This function mounts the selected partition.
U16 nav_filterflat_nb (void)
This function computes the number of files and directories in filtered file list.
Bool nav_filterflat_next (void)
This function goes to the next position in the filtered file list.
Bool nav_filterflat_previous (void)
This function goes to the previous position in filtered file list.
Bool nav_filterflat_reset (void)
This function resets the pointer of selection, so "no file selected" in filtered file list.
Bool nav_filterflat_root (void)
This function initializes the file filtered list on the root directory.
Function Documentation
Bool nav_filterflat_cd (void)
This function enters in the selected directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 298 of file nav_filterflat.c.
References fs_g_nav, nav_dir_cd(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   if( !nav_dir_cd() )
      return FALSE;
   fs_g_nav.u8_flat_dir_level   = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   return TRUE;
}
Bool nav_filterflat_findname (const FS_STRING sz_name, Bool b_match_case)
This function searches a file name in file list filtered.
Parameters:
sz_name name to search (UNICODE or ASCII)
The name must end with NULL or '*' value
b_match_case FALSE to ignore the case
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! This function starts a search at the next position of the current in filtered file list
//!
Definition at line 252 of file nav_filterflat.c.
References FS_NAME_CHECK, nav_file_name(), and nav_filterflat_next().
{
   while( 1 )
   {
      if ( !nav_filterflat_next() )
         return FALSE;
      if ( nav_file_name( sz_name , 0 , FS_NAME_CHECK , b_match_case ))
         return TRUE;
   }
}
U16 nav_filterflat_get (void)
This function returns the position of selected file in filtered file list.
Returns:
position of selected file in directory (0 is the first position)
FS_NO_SEL, in case of no file selected
Definition at line 201 of file nav_filterflat.c.
References fs_g_nav, nav_filterlist_get(), and Fs_management::u16_flat_pos_offset.
Referenced by nav_filterflat_goto(), and nav_filterflat_nb().
{
   return (fs_g_nav.u16_flat_pos_offset + nav_filterlist_get());
}
Bool nav_filterflat_goto (U16 u16_newpos)
This function goes to a position in filtered file list.
Parameters:
u16_newpos new position to select (0 is the first position)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 214 of file nav_filterflat.c.
References FS_NO_SEL, nav_filterflat_get(), nav_filterflat_next(), nav_filterflat_previous(), and nav_filterflat_reset().
Referenced by nav_filterflat_nb().
{
   if (u16_newpos < (nav_filterflat_get()/2))
   {
      // Restart at the beginning of list to accelerate search
      if (!nav_filterflat_reset())
         return FALSE;
   }
   if( FS_NO_SEL == nav_filterflat_get() )
      if( !nav_filterflat_next() )
         return FALSE;  // No file available
   while( u16_newpos > nav_filterflat_get())
   {
      if( !nav_filterflat_next())
         return FALSE; // End of list, position is bad
   }
   while(u16_newpos < nav_filterflat_get())
   {
      if( !nav_filterflat_previous())
         return FALSE; // Position error
   }
   return TRUE;
}
Bool nav_filterflat_gotoparent (void)
This function goes to at the parent directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After the selected file is the first entry
//!
Definition at line 317 of file nav_filterflat.c.
References fs_g_nav, nav_dir_gotoparent(), nav_filterflat_next(), nav_filterlist_reset(), nav_getindex(), nav_gotoindex(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   _MEM_TYPE_SLOW_ Fs_index index;
   index = nav_getindex();
   while( 0 != fs_g_nav.u8_flat_dir_level )
   {
      fs_g_nav.u8_flat_dir_level--;
      nav_dir_gotoparent();
   }
   if( !nav_dir_gotoparent() )
   {
      nav_gotoindex( &index );
      return FALSE;
   }
   // go to the beginning of FLAT list
   fs_g_nav.u8_flat_dir_level   = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   nav_filterlist_reset();
   nav_filterflat_next();
   return TRUE;
}
Bool nav_filterflat_mount (void)
This function mounts the selected partition.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! If the FS_MULTI_PARTITION option is disabled
//! then the mount routine selects the first partition supported by file system. <br>
//! After mount, the file list contains files and directories of ROOT directory
//!
Definition at line 70 of file nav_filterflat.c.
References fs_g_nav, nav_filterlist_mount(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   fs_g_nav.u8_flat_dir_level = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   return nav_filterlist_mount();
}
U16 nav_filterflat_nb (void)
This function computes the number of files and directories in filtered file list.
Returns:
number of files and directories present in filtered file list
Definition at line 268 of file nav_filterflat.c.
References nav_filterflat_get(), nav_filterflat_goto(), nav_filterflat_next(), and nav_filterflat_reset().
{
   U16   u16_save_position;
   U16   u16_number;
   // Save current position
   u16_save_position = nav_filterflat_get();
   // Reset position
   if ( !nav_filterflat_reset())
      return 0;
   // Scan all directory
   u16_number  = 0;
   while( nav_filterflat_next() )
   {
      u16_number++;
   }
   // Restore previous position
   nav_filterflat_goto( u16_save_position );
   return u16_number;
}
Bool nav_filterflat_next (void)
This function goes to the next position in the filtered file list.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 113 of file nav_filterflat.c.
References fs_g_nav, nav_dir_cd(), nav_file_isdir(), nav_filterlist_get(), nav_filterlist_gotoparent(), nav_filterlist_next(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
Referenced by nav_filterflat_findname(), nav_filterflat_goto(), nav_filterflat_gotoparent(), and nav_filterflat_nb().
{
   U16 u16_save_current_pos;
   u16_save_current_pos = nav_filterlist_get();
   if( nav_file_isdir() )
   {
      // The current file is a dir then enter in this
      if( !nav_dir_cd() )
         return FALSE;
      if( nav_filterlist_next() )
      {
         // File present in this dir then valid the new position
         fs_g_nav.u8_flat_dir_level++;
         fs_g_nav.u16_flat_pos_offset += u16_save_current_pos+1;
         return TRUE;
      }else{
         // No file then return in parent dir
         if( !nav_filterlist_gotoparent() )
            return FALSE;
      }
   }
   // Find next file in current dir or parent dir
   while( !nav_filterlist_next() )
   {
      // End of current directory then goes to parent
      if( 0 == fs_g_nav.u8_flat_dir_level )
         return FALSE;  // End of list FLAT
      if( !nav_filterlist_gotoparent() )
         return FALSE;
      fs_g_nav.u8_flat_dir_level--;
   }
   fs_g_nav.u16_flat_pos_offset = (fs_g_nav.u16_flat_pos_offset +u16_save_current_pos +1) -nav_filterlist_get();
   return TRUE;
}
Bool nav_filterflat_previous (void)
This function goes to the previous position in filtered file list.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 155 of file nav_filterflat.c.
References fs_g_nav, nav_dir_cd(), nav_file_isdir(), nav_filterlist_get(), nav_filterlist_gotoparent(), nav_filterlist_next(), nav_filterlist_previous(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
Referenced by nav_filterflat_goto().
{
   U16 u16_save_current_pos;
   u16_save_current_pos = nav_filterlist_get();
   if( nav_filterlist_previous() )
   {
      while( 1 )
      {
         if( !nav_file_isdir() )
         {
            fs_g_nav.u16_flat_pos_offset = ((fs_g_nav.u16_flat_pos_offset +u16_save_current_pos) -nav_filterlist_get()) -1;
            return TRUE;   // New position valid
         }
         // The file is a dir then enter in this
         if( !nav_dir_cd() )
            return FALSE;
         if( !nav_filterlist_next() )
         {
            // Dir empty then goes to parent and dir is the new selection
            nav_filterlist_gotoparent();
            fs_g_nav.u16_flat_pos_offset = ((fs_g_nav.u16_flat_pos_offset +u16_save_current_pos) -nav_filterlist_get()) -1;
            return TRUE;
         }
         fs_g_nav.u8_flat_dir_level++;
         // Go to end of the dir
         while( nav_filterlist_next() );
      }
   }
   // Beginning of current directory then goes to parent
   if( 0 == fs_g_nav.u8_flat_dir_level )
      return FALSE;  // beginning of list FLAT
   if( !nav_filterlist_gotoparent() )
      return FALSE;
   fs_g_nav.u8_flat_dir_level--;
   fs_g_nav.u16_flat_pos_offset -= (nav_filterlist_get()+1);
   return TRUE;
}
Bool nav_filterflat_reset (void)
This function resets the pointer of selection, so "no file selected" in filtered file list.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 96 of file nav_filterflat.c.
References fs_g_nav, nav_dir_gotoparent(), nav_filterlist_reset(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
Referenced by nav_filterflat_goto(), and nav_filterflat_nb().
{
   while( 0 != fs_g_nav.u8_flat_dir_level )
   {
      fs_g_nav.u8_flat_dir_level--;
      nav_dir_gotoparent();
   }
   fs_g_nav.u16_flat_pos_offset = 0;
   return nav_filterlist_reset();
}
Bool nav_filterflat_root (void)
This function initializes the file filtered list on the root directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 83 of file nav_filterflat.c.
References fs_g_nav, nav_filterlist_root(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   fs_g_nav.u8_flat_dir_level = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   return nav_filterlist_root();
}