AVR32 - FAT Services: navigation.c File Reference
navigation.c File Reference
Detailed Description
FAT 12/16/32 Services.
This file defines a useful set of functions for file navigation.
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file navigation.c.
#include <ctype.h>
#include "conf_explorer.h"
#include "navigation.h"
#include "file.h"
#include "ctrl_access.h"
Defines
#define SIZE_OF_SPLIT_COPY ((1*1024*1024L)/512L)
Functions
void nav_checkdisk_disable (void)
This function disables the disk check before each actions on disk.
void nav_checkdisk_enable (void)
This function enables the disk check before each actions on disk.
Bool nav_copy (U8 u8_idnav)
This function copys the navigator information to another navigator.
Bool nav_dir_cd (void)
This function enters in the selected directory in file list.
Bool nav_dir_gotoparent (void)
This function goes to the parent directory.
Bool nav_dir_is_root (void)
This function check the current directory.
Bool nav_dir_make (const FS_STRING sz_name)
This function creates a directory in the directory corresponding at file list.
Bool nav_dir_name (FS_STRING sz_path, U8 u8_size_max)
This function returns the directory name corresponding at the file list.
Bool nav_dir_root (void)
This function initializes the file list on the root directory.
Bool nav_drive_format (U8 u8_fat_type)
This function formats the current drive (=disk).
U8 nav_drive_get (void)
This function returns the selected drive number.
U8 nav_drive_getname (void)
This function returns the selected drive letter.
U8 nav_drive_nb (void)
This function returns the number of devices availabled.
Bool nav_drive_set (U8 u8_number)
This function selects a drive in navigator but don't mount the disk partition.
void nav_exit (void)
This function flush ALL navigations before exit of file system core.
U8 nav_file_attributget (void)
This function returns the attribut of selected file.
Bool nav_file_attributset (U8 u8_attribut)
This function changes the attribut of selected file.
Bool nav_file_checkext (const FS_STRING sz_filterext)
This function checks the extension of selected file.
Bool nav_file_copy (void)
This function updates the COPY navigator with the selected file.
Bool nav_file_create (const FS_STRING sz_name)
This function creates a file with NULL size and NULL attribut.
Bool nav_file_dateget (FS_STRING sz_date, Bool type_date)
This function returns the date of selected file.
Bool nav_file_dateset (const FS_STRING sz_date, Bool type_date)
This function changes the date of selected file.
Bool nav_file_del (Bool b_only_empty)
This function deletes the selected file or directory.
Bool nav_file_getname (FS_STRING sz_name, U8 u8_size_max)
This function returns the name of selected file.
Bool nav_file_isdir (void)
This function returns the type of selected file.
Bool nav_file_isreadonly (void)
This function checks the write protection of disk and the attribut "read only" of selected file.
U32 nav_file_lgt (void)
This function returns the size of selected file (unit byte).
U16 nav_file_lgtsector (void)
This function returns the size of selected file (unit sector).
Bool nav_file_name (FS_STRING sz_name, U8 u8_size_max, Bool b_mode, Bool b_match_case)
This function returns the name of selected file or checks the string with the name of selected file.
Bool nav_file_paste_start (const FS_STRING sz_name)
This function pastes the selected file in COPY navigator in the file list of the current navigator.
U8 nav_file_paste_state (Bool b_stop)
This function executes the copy file.
Bool nav_file_rename (const FS_STRING sz_name)
This function renames the selected directory or file.
Bool nav_filelist_bol (void)
This function checks the beginning of file list.
Bool nav_filelist_eol (void)
This function checks the end of file list.
Bool nav_filelist_exist (Bool b_type)
This function checks the presence of files or directories in file list.
Bool nav_filelist_fileisnotopen (void)
This function checks if no file is open.
Bool nav_filelist_findname (const FS_STRING sz_name, Bool b_match_case)
This function searchs a file name in file list.
Bool nav_filelist_first (Bool b_type)
This function goes to at the first file or directory in file list.
U16 nav_filelist_get (void)
This function returns the position of selected file in file list.
Bool nav_filelist_goto (U16 u16_newpos)
This function goes at a position in file list.
Bool nav_filelist_last (Bool b_type)
This function goes to at the last file or directory in file list.
U16 nav_filelist_nb (Bool b_type)
This function computes the number of files or directories in file list.
Bool nav_filelist_reset (void)
This function resets the selection pointer, so "no file selected" in file list.
Bool nav_filelist_set (U16 u16_nb, Bool b_direction)
This function moves the selection pointer in file list.
Bool nav_filelist_single_disable (void)
To display in File List the directories AND files.
Bool nav_filelist_single_enable (Bool b_type)
To display in File List only the files OR directories.
Bool nav_filelist_validpos (void)
This function checks if a file is selected.
U8 nav_get (void)
This function returns the navigation identifier used.
Bool nav_getcwd (FS_STRING sz_path, U8 u8_size_path, Bool b_view_file_select)
This function returns the full path of the selection.
Fs_index nav_getindex (void)
This function returns a small index on the selected file.
Bool nav_gotoindex (const Fs_index _MEM_TYPE_SLOW_ *index)
This function selects a file in the navigator via a file index.
U8 nav_partition_cluster_size (void)
This function returns the partition cluster size.
U32 nav_partition_freespace (void)
This function returns the partition free space.
U8 nav_partition_freespace_percent (void)
This function returns the partition space free in percent.
Bool nav_partition_label (Bool b_action, FS_STRING sz_label)
This function reads or writes the label of selected partition.
Bool nav_partition_mount (void)
This function mounts the selected partition.
U8 nav_partition_nb (void)
This function returns the number of partitions present on drive.
Bool nav_partition_serialnumber (Bool b_action, U8 _MEM_TYPE_SLOW_ *a_u8_sn)
This function reads or writes the serial number on the selected partition.
Bool nav_partition_set (U8 partition_number)
This function selects a partition on drive.
U32 nav_partition_space (void)
This function returns partition total space.
U8 nav_partition_type (void)
This function gives the partition type.
void nav_reset (void)
This function resets ALL navigations to init file system core.
Bool nav_select (U8 u8_idnav)
This function selects the navigation to use.
Bool nav_setcwd (FS_STRING sz_path, Bool b_match_case, Bool b_create)
This function selects a disk position via a path.
void nav_string_ascii (void)
This function selects the ASCII mode for all routines with FS_STRING parameter.
void nav_string_length_disable (void)
This function deselects the LENGTH string mode for all routines with FS_STRING parameter.
void nav_string_length_enable (void)
This function selects the LENGTH string mode for all routines with FS_STRING parameter.
void nav_string_unicode (void)
This function selects the UNICODE mode for all routines with FS_STRING parameter.
Variables
_MEM_TYPE_SLOW_ U8 fs_g_u8_nav_selected
Holds the current navigator selected.
_MEM_TYPE_SLOW_ U8 g_id_trans_memtomem = ID_STREAM_ERR
Holds the current ID transfer used by the internal copy-paste routines.
_MEM_TYPE_SLOW_ Fs_file_segment g_segment_dest
_MEM_TYPE_SLOW_ Fs_file_segment g_segment_src
Define Documentation
#define SIZE_OF_SPLIT_COPY ((1*1024*1024L)/512L)
Definition at line 72 of file navigation.c.
Referenced by nav_file_paste_state().
Function Documentation
void nav_checkdisk_disable (void)
This function disables the disk check before each actions on disk.
//! By default, between each read/write access a check disk (test unit ready) is sended at device.
//! This check can reduce the speed access on specific disk.
//!
Definition at line 137 of file navigation.c.
References g_b_no_check_disk.
Referenced by reader_txt_get_line().
{
   g_b_no_check_disk = TRUE;
}
void nav_checkdisk_enable (void)
This function enables the disk check before each actions on disk.
//! By default, between each read/write access a check disk (test unit ready) is sended at device.
//! This check can reduce the speed access on specific disk.
//!
Definition at line 149 of file navigation.c.
References g_b_no_check_disk.
Referenced by reader_txt_get_line().
{
   g_b_no_check_disk = FALSE;
}
Bool nav_copy (U8 u8_idnav)
This function copys the navigator information to another navigator.
Parameters:
u8_idnav navigator identifier where the main navigator will be copied
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Use this routine to select quickly the same file in another navigator
//!
Definition at line 281 of file navigation.c.
References fat_copy_nav(), and fs_g_u8_nav_selected.
Referenced by nav_file_copy(), pl_main_open(), and pl_main_readline().
{
#if (FS_NB_NAVIGATOR > 1)
   if( fs_g_u8_nav_selected == u8_idnav )
      return FALSE;                    // It is the source and destination is the same navigator
   if( 0 == u8_idnav )
      u8_idnav = fs_g_u8_nav_selected; // the default navigator is invert with the current navigator
   if( 0 == u8_idnav)
      return FALSE;                    // It is the source and destination is the same navigator
   fat_copy_nav( u8_idnav );
   return TRUE;
#else
   u8_idnav++;
   return FALSE;                       // Copy impossible because only one navigator is available
#endif
}
Bool nav_dir_cd (void)
This function enters in the selected directory in file list.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After this routine the file list changes and contains the files and directories of the new directory.
//! By default no file is selected.
//!
Definition at line 1189 of file navigation.c.
References fat_check_mount_select_noopen(), fat_entry_is_dir(), fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, nav_filelist_reset(), Fs_management::u16_entry_pos_sel_dir, Fs_management_fast::u16_entry_pos_sel_file, Fs_management_entry::u32_cluster, and Fs_management::u32_cluster_sel_dir.
Referenced by nav_file_del(), nav_filterflat_cd(), nav_filterflat_next(), nav_filterflat_previous(), nav_filterlist_cd(), nav_flat_cd(), nav_flat_next(), nav_flat_previous(), nav_setcwd(), navauto_mov_explorer_is_dir(), navauto_mov_explorer_select_limit_dir_cur_folder(), and pl_add().
{
   if ( !fat_check_mount_select_noopen())
      return FALSE;
   // The current selection, is it a directory ?
   if ( !fat_entry_is_dir())
      return FALSE;
   // Select the current directory
   fs_g_nav.u16_entry_pos_sel_dir = fs_g_nav_fast.u16_entry_pos_sel_file;
   fs_g_nav.u32_cluster_sel_dir = fs_g_nav_entry.u32_cluster;
   // Reset file list
   if( FALSE == nav_filelist_reset())
      return FALSE;
   return TRUE;
}
Bool nav_dir_gotoparent (void)
This function goes to the parent directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After, the file list changes and contains the files and directories of the new directory.
//! By default, the file selected in file list is the previous (children) directory.
//!
Definition at line 1219 of file navigation.c.
References Fs_management::b_mode_nav, Fs_management::b_mode_nav_single, fat_check_mount_noopen(), fat_get_entry_info(), fat_read_dir(), FS_DIR, FS_ERR_FS, FS_ERR_IS_ROOT, FS_FIND_NEXT, fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, fs_g_status, nav_filelist_reset(), nav_filelist_set(), Fs_management_fast::u16_entry_pos_sel_file, Fs_management_entry::u32_cluster, and Fs_management::u32_cluster_sel_dir.
Referenced by nav_dir_name(), nav_file_del(), nav_filterflat_gotoparent(), nav_filterflat_reset(), nav_flat_gotoparent(), nav_flat_next(), nav_flat_previous(), nav_flat_reset(), nav_getcwd(), nav_setcwd(), navauto_mov_explorer_updir(), navauto_open(), and pl_add().
{
   U32 u32_cluster_old_dir;
   if (!fat_check_mount_noopen())
      return FALSE;
   if (0 == fs_g_nav.u32_cluster_sel_dir)
   {
      fs_g_status = FS_ERR_IS_ROOT;        // There aren't parent
      return FALSE;
   }
   // Select and read information about directory ".."
   fs_g_nav_fast.u16_entry_pos_sel_file = 1;
   if ( !fat_read_dir())
      return FALSE;
   fat_get_entry_info();
   // Save the children directory cluster
   u32_cluster_old_dir = fs_g_nav.u32_cluster_sel_dir;
   // Select the parent directory via information present in the current directory ".."
   fs_g_nav.u32_cluster_sel_dir = fs_g_nav_entry.u32_cluster;
   // Select the children directory in new directory (=parent directory)
   if( FALSE == nav_filelist_reset())
      return FALSE;
   if( fs_g_nav.b_mode_nav_single && (FS_DIR != fs_g_nav.b_mode_nav) )
      return TRUE;
   while( nav_filelist_set( 0 , FS_FIND_NEXT ) )
   {
      if (fs_g_nav_entry.u32_cluster == u32_cluster_old_dir)
         return TRUE;         // It is the children directory
   }
   fs_g_status = FS_ERR_FS;
   return FALSE;
}
Bool nav_dir_is_root (void)
This function check the current directory.
Returns:
FALSE the current directory selected is not the root directory
TRUE the current directory selected is the root directory
Definition at line 1170 of file navigation.c.
References fat_check_mount_noopen(), fs_g_nav, and Fs_management::u32_cluster_sel_dir.
{
   if (!fat_check_mount_noopen())
      return FALSE;
   return (0 == fs_g_nav.u32_cluster_sel_dir);
}
Bool nav_dir_make (const FS_STRING sz_name)
This function creates a directory in the directory corresponding at file list.
Parameters:
sz_name directory name (ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1361 of file navigation.c.
References fat_allocfreespace(), fat_cache_flush(), fat_check_mount_noopen(), fat_delete_file(), fat_initialize_dir(), fat_read_dir(), fat_write_entry_file(), FS_ATTR_DIRECTORY, FS_DIR, fs_g_nav_entry, fs_g_seg, nav_file_create(), nav_filelist_last(), Fs_segment::u32_addr, Fs_management_entry::u32_cluster, Fs_management_entry::u32_size, Fs_segment::u32_size_or_pos, and Fs_management_entry::u8_attr.
Referenced by main(), and nav_setcwd().
{
   if ( !fat_check_mount_noopen())
      return FALSE;
   // Create an entry file
   if ( !nav_file_create( sz_name ))
      return FALSE;
   // Allocate one cluster for the new directory
   MSB0(fs_g_seg.u32_addr)=0xFF;    // It is a new cluster list
   fs_g_seg.u32_size_or_pos = 1;    // Only one sector (= one cluster)
   if ( !fat_allocfreespace())
   {
      fat_delete_file( FALSE );
      fat_cache_flush();
      return FALSE;
   }
   // Save information about the new directory
   fs_g_nav_entry.u32_cluster = fs_g_seg.u32_addr; // First cluster of the directory returned by alloc_free_space
   fs_g_nav_entry.u32_size    = 0;                 // The directory size is null
   fs_g_nav_entry.u8_attr     = FS_ATTR_DIRECTORY; // Directory attribut
   // Initialize the values in the new directory
   if ( !fat_initialize_dir())
      return FALSE;
   // Write directory information in her entry file
   if ( !fat_read_dir())
      return FALSE;
   fat_write_entry_file();
   if( !fat_cache_flush())
      return FALSE;
   // Go to position of new directory (it is the last directory)
   return nav_filelist_last( FS_DIR );
}
Bool nav_dir_name (FS_STRING sz_path, U8 u8_size_max)
This function returns the directory name corresponding at the file list.
Parameters:
sz_path string to store the name (ASCII or UNICODE)
u8_size_max string size (unit ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1267 of file navigation.c.
References Fs_management::b_mode_nav, Fs_management::b_mode_nav_single, fat_check_mount_noopen(), FS_FILE, fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, FS_NAME_GET, g_b_string_length, Is_unicode, nav_dir_gotoparent(), nav_drive_getname(), nav_file_name(), Fs_management::u16_entry_pos_sel_dir, Fs_management_fast::u16_entry_pos_sel_file, Fs_management_entry::u32_cluster, Fs_management::u32_cluster_sel_dir, Fs_management_entry::u32_size, and Fs_management_entry::u8_attr.
Referenced by main().
{
   U8 u8_i, u8_character;
   Bool status = FALSE;
   U16 save_u16_entry_pos_sel_file;
   U32 save_u32_cluster_sel_dir;
   U8  save_u8_attr          ;
   U32 save_u32_cluster      ;
   U32 save_u32_size         ;
   Bool b_mode_nav_single_save;
   Bool b_mode_nav_mode_save;
   if ( !fat_check_mount_noopen())
      return FALSE;
   if (0 != fs_g_nav.u32_cluster_sel_dir)
   {
      // Save context
      save_u16_entry_pos_sel_file= fs_g_nav_fast.u16_entry_pos_sel_file;
      save_u32_cluster_sel_dir   = fs_g_nav.u32_cluster_sel_dir        ;
      save_u8_attr               = fs_g_nav_entry.u8_attr              ;
      save_u32_cluster           = fs_g_nav_entry.u32_cluster          ;
      save_u32_size              = fs_g_nav_entry.u32_size             ;
      b_mode_nav_single_save = fs_g_nav.b_mode_nav_single;
      b_mode_nav_mode_save   = fs_g_nav.b_mode_nav;
      fs_g_nav.b_mode_nav_single = TRUE;
      fs_g_nav.b_mode_nav = FS_FILE;
      // Go to parent directory and select the children directory
      if( !nav_dir_gotoparent() )
      {
         fs_g_nav.b_mode_nav_single = b_mode_nav_single_save;
         fs_g_nav.b_mode_nav = b_mode_nav_mode_save;
         return FALSE;
      }
      fs_g_nav.b_mode_nav_single = b_mode_nav_single_save ;
      fs_g_nav.b_mode_nav = b_mode_nav_mode_save;
      // Go to directory name position
      fs_g_nav_fast.u16_entry_pos_sel_file = fs_g_nav.u16_entry_pos_sel_dir;
      status = nav_file_name( sz_path  , u8_size_max , FS_NAME_GET , FALSE  );
      // Restore previous context
      fs_g_nav_fast.u16_entry_pos_sel_file= save_u16_entry_pos_sel_file;
      fs_g_nav.u32_cluster_sel_dir        = save_u32_cluster_sel_dir   ;
      fs_g_nav_entry.u8_attr              = save_u8_attr               ;
      fs_g_nav_entry.u32_cluster          = save_u32_cluster           ;
      fs_g_nav_entry.u32_size             = save_u32_size              ;
   }
   else
   {
      // No parent directory, then it is the root directory
      if( g_b_string_length )
      {
         ((FS_STR_UNICODE)sz_path )[0] = 3;  // 3 chars for path "x:"
         status = TRUE;
      }else
      // Create a device name
      for( u8_i = 0 ; u8_i<3 ; u8_i++ )
      {
         switch( u8_i )
         {
            case 0:
            u8_character = nav_drive_getname();    // Letter
            break;
            case 1:
            u8_character = ':';                     // ":"
            break;
            case 2:
            default:
            u8_character = 0;                       // end of string
            break;
         }
         if( Is_unicode )
         {
            ((FS_STR_UNICODE)sz_path )[0] = u8_character;
         }else{
            sz_path [0] = u8_character;
         }
         sz_path  += (Is_unicode? 2 : 1 );
      }
      status = TRUE;
   }
   return status;
}
Bool nav_dir_root (void)
This function initializes the file list on the root directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1159 of file navigation.c.
References nav_partition_mount().
Referenced by nav_filterlist_root(), nav_flat_root(), nav_partition_label(), nav_setcwd(), and navauto_mov_explorer_reset().
{
   return nav_partition_mount();
}
Bool nav_drive_format (U8 u8_fat_type)
This function formats the current drive (=disk).
Parameters:
u8_fat_type Select the format type
FS_FORMAT_DEFAULT, The system chooses the better FAT format
FS_FORMAT_FAT, The FAT12 or FAT16 is used to format the drive, if possible (disk space <2GB)
FS_FORMAT_FAT32, The FAT32 is used to format the drive, if possible (disk space >32MB)
FS_FORMAT_NOMBR_FLAG, if you don't want a MRB on the disk then add this flag (e.g. specific partition structure on a CD support)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! WARNING: This routine can't format a multi-partiton, if the disk contains a multi-partition
//! then this one is erased and replaced by a single partition on ALL disk space.
//!
Definition at line 399 of file navigation.c.
References fat_check_nav_access_disk(), fat_check_noopen(), fat_format(), and fat_mount().
Referenced by main().
{
   if ( !fat_check_noopen() )
      return FALSE;
   if ( !fat_check_nav_access_disk() )
      return FALSE;
   if ( !fat_format( u8_fat_type ) )
      return FALSE;
   return fat_mount();
}
U8 nav_drive_get (void)
This function returns the selected drive number.
Returns:
0 to nav_drive_nb()-1
0xFF in case of no drive selected
Definition at line 353 of file navigation.c.
References fs_g_nav, Fs_management::u8_lun, and Fs_management::u8_partition.
Referenced by main(), and navauto_mov_ok_loop().
{
#if (FS_MULTI_PARTITION  ==  ENABLED)
   if(0xFF == fs_g_nav.u8_lun)
      return 0xFF;
   return ((fs_g_nav.u8_lun*4) + fs_g_nav.u8_partition); // Maximum 4 partitions per device
#else
   return (fs_g_nav.u8_lun);
#endif
}
U8 nav_drive_getname (void)
This function returns the selected drive letter.
Returns:
'A','B',...
'X', in case of no drive selected
Definition at line 370 of file navigation.c.
References fs_g_nav, Fs_management::u8_lun, and Fs_management::u8_partition.
Referenced by nav_dir_name(), and nav_getcwd().
{
   if(0xFF == fs_g_nav.u8_lun)
      return 'X';
#if (FS_MULTI_PARTITION  ==  ENABLED)
   return ('A' + (fs_g_nav.u8_lun*4) + fs_g_nav.u8_partition); // Maximum 4 partitions per device
#else
   return ('A' + fs_g_nav.u8_lun);
#endif
}
U8 nav_drive_nb (void)
This function returns the number of devices availabled.
Returns:
number of devices, 0 = NO DEVICE AVAILABLED
//! This value may be dynamic because it depends of memory drivers (e.g. Mass Storage disk on USB host mode)
//!
Definition at line 311 of file navigation.c.
References get_nb_lun().
Referenced by main(), and navauto_mov_ok_loop().
{
   return get_nb_lun(); // Number of devices = Number of lun
}
Bool nav_drive_set (U8 u8_number)
This function selects a drive in navigator but don't mount the disk partition.
Parameters:
u8_number device number (0 to nav_drive_nb()-1)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 324 of file navigation.c.
References fat_check_noopen(), FS_ERR_END_OF_DRIVE, fs_g_nav, fs_g_nav_fast, fs_g_status, FS_TYPE_FAT_UNM, get_nb_lun(), Fs_management::u8_lun, Fs_management::u8_partition, and Fs_management_fast::u8_type_fat.
Referenced by main(), nav_filterlist_gotoindex(), nav_gotoindex(), nav_setcwd(), navauto_mov_explorer_reset(), and navauto_mov_ok_loop().
{
   if ( !fat_check_noopen() )
      return FALSE;
   if (u8_number >= get_nb_lun() )
   {
      fs_g_status = FS_ERR_END_OF_DRIVE;   // The drive number is bad
      return FALSE;
   }
   if ( fs_g_nav.u8_lun == u8_number)
      return TRUE;   // It is the same drive number
   // Go to the device
   fs_g_nav.u8_lun = u8_number;
   fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_UNM;
#if (FS_MULTI_PARTITION  ==  ENABLED)
   fs_g_nav.u8_partition=0;   // by default select the first partition
#endif
   return TRUE;
}
void nav_exit (void)
This function flush ALL navigations before exit of file system core.
//! Call this at the program exit or before a USB Device session
//!
Definition at line 211 of file navigation.c.
References fat_cache_flush(), file_close(), FS_NB_NAVIGATOR, and nav_select().
{
   // If you have opened files then close them
#if (FS_NB_NAVIGATOR > 1)
   U8 u8_i;
   for( u8_i=0; u8_i<FS_NB_NAVIGATOR; u8_i++)
   {
      nav_select(u8_i);
      file_close();
   }
#else
   nav_select(0);
   file_close();
#endif
   // Flush data eventually present in FAT cache
   fat_cache_flush();
}
U8 nav_file_attributget (void)
This function returns the attribut of selected file.
Returns:
attribut of selected file, see masks "FS_ATTR_" in fs_com.h file.
Definition at line 1948 of file navigation.c.
References fs_g_nav_entry, and Fs_management_entry::u8_attr.
{
   return fs_g_nav_entry.u8_attr;
}
Bool nav_file_attributset (U8 u8_attribut)
This function changes the attribut of selected file.
Parameters:
u8_attribut value to write on selected file, see masks "FS_ATTR_" in fs_com.h file.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1988 of file navigation.c.
References fat_cache_flush(), fat_check_mount_select(), fat_read_dir(), fat_write_entry_file(), FS_ATTR_ARCHIVE, FS_ATTR_HIDDEN, FS_ATTR_READ_ONLY, FS_ATTR_SYSTEM, fs_g_nav_entry, and Fs_management_entry::u8_attr.
{
   if ( !fat_check_mount_select())
      return FALSE;
   // Read selected entry in directory
   if ( !fat_read_dir())
      return FALSE;
   // Write the new attribut
   fs_g_nav_entry.u8_attr &= (~(FS_ATTR_READ_ONLY|FS_ATTR_HIDDEN|FS_ATTR_SYSTEM|FS_ATTR_ARCHIVE));
   fs_g_nav_entry.u8_attr |= u8_attribut & (FS_ATTR_READ_ONLY|FS_ATTR_HIDDEN|FS_ATTR_SYSTEM|FS_ATTR_ARCHIVE);
   fat_write_entry_file();
   return fat_cache_flush();  // To write all data and check write access before exit function
}
Bool nav_file_checkext (const FS_STRING sz_filterext)
This function checks the extension of selected file.
Parameters:
sz_filterext extension filter (ASCII format, e.g.: "txt" or "txt,d*,wk")
Returns:
TRUE, the file extension match with extension filter
FALSE, in other case
Definition at line 1905 of file navigation.c.
References fat_check_mount_select(), fat_entry_checkext(), and fat_read_dir().
Referenced by nav_filterlist_nb_ex(), nav_filterlist_next(), nav_filterlist_previous(), navauto_mov_explorer_is_file(), navauto_mov_explorer_select_limit_file_cur_folder(), navauto_open(), pl_add(), and pl_main_open().
{
   if ( fat_check_mount_select() )
   {
      // Read selected entry (=short name entry) in directory
      if ( fat_read_dir())
      {
         // Check the extension with filter
         if ( fat_entry_checkext( (FS_STRING) sz_filterext ) )
            return TRUE;
      }
   }
   return FALSE;
}
Bool nav_file_copy (void)
This function updates the COPY navigator with the selected file.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! If you use the COPY navigator after this routine then the copy information is lost (see FS_NAV_ID_COPYFILE in conf_explorer.h).
//!
Definition at line 2191 of file navigation.c.
References FS_ERR_COPY_DIR, fs_g_status, FS_NAV_ID_COPYFILE, nav_copy(), and nav_file_isdir().
Referenced by main(), and pl_main_modify().
{
   if( nav_file_isdir() )
   {
      fs_g_status = FS_ERR_COPY_DIR; // Impossible to copy a directory
      return FALSE;
   }
   // In "copy file" navigator select the file
   nav_copy( FS_NAV_ID_COPYFILE );
   return TRUE;
}
Bool nav_file_create (const FS_STRING sz_name)
This function creates a file with NULL size and NULL attribut.
Parameters:
sz_name file name to create (ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! If you ues this routine to create a file, then you must called file_open() to open this new file
//!
Definition at line 2156 of file navigation.c.
References Fs_management::b_mode_nav, fat_cache_flush(), fat_create_entry_file_name(), FS_ERR_FILE_EXIST, FS_FILE, fs_g_nav, fs_g_nav_entry, fs_g_status, nav_filelist_findname(), nav_filelist_reset(), Fs_management::u16_pos_sel_file, Fs_management_entry::u32_cluster, Fs_management_entry::u32_size, and Fs_management_entry::u8_attr.
Referenced by main(), nav_dir_make(), nav_file_paste_start(), nav_file_rename(), nav_setcwd(), and reader_txt_new().
{
   // Check if the name already exists
   if (!nav_filelist_reset())
      return FALSE;
   if (nav_filelist_findname(sz_name , FALSE))
   {
      fs_g_status = FS_ERR_FILE_EXIST;
      return FALSE;  // File exist -> it is not possible to create this name
   }
   // FYC: here, the selection is at the end of the list
   // Create name entrys
   if ( !fat_create_entry_file_name( sz_name ))
      return FALSE; // error
   // By default the information about the new file is NULL
   fs_g_nav_entry.u32_cluster = 0;     // No first cluster
   fs_g_nav_entry.u32_size    = 0;     // The size is null
   fs_g_nav_entry.u8_attr     = 0;     // Attribut is a file
   // It is the last FILE of the list
   fs_g_nav.u16_pos_sel_file++;
   fs_g_nav.b_mode_nav = FS_FILE;
   return fat_cache_flush();
}
Bool nav_file_dateget (FS_STRING sz_date, Bool type_date)
This function returns the date of selected file.
Parameters:
type_date FS_DATE_LAST_WRITE, to get the date of last write access
FS_DATE_CREATION, to get the date of file creation
sz_date ASCCI string (>17B) to store the information about date
"YYYYMMDDHHMMSSMS" = year, month, day, hour, minute, seconde, miliseconde
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1931 of file navigation.c.
References fat_check_mount_select(), fat_get_date(), and fat_read_dir().
{
   if ( !fat_check_mount_select())
      return FALSE;
   // Read selected entry in directory
   if ( !fat_read_dir())
      return FALSE;
   fat_get_date( sz_date , type_date );
   return TRUE;
}
Bool nav_file_dateset (const FS_STRING sz_date, Bool type_date)
This function changes the date of selected file.
Parameters:
type_date FS_DATE_LAST_WRITE, to get the date of last write access
FS_DATE_CREATION, to get the date of file creation
sz_date ASCCI string contains the date to write
"YYYYMMDDHHMMSSMS" = year, month, day, hour, minute, seconde, miliseconde
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1966 of file navigation.c.
References fat_cache_flush(), fat_check_mount_select(), fat_read_dir(), and fat_set_date().
{
   if ( !fat_check_mount_select())
      return FALSE;
   // Read selected entry in directory
   if ( !fat_read_dir())
      return FALSE;
   fat_set_date( sz_date , type_date );
   return fat_cache_flush();  // To write all data and check write access before exit function
}
Bool nav_file_del (Bool b_only_empty)
This function deletes the selected file or directory.
Parameters:
b_only_empty TRUE, delete the directory only if empty
FALSE, delete directories and files include in selected directory
If the selection is not a directory then this param is ignored.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 2016 of file navigation.c.
References fat_cache_flush(), fat_check_mount_select_noopen(), fat_check_nav_access_file(), fat_delete_file(), FS_ERR_DIR_NOT_EMPTY, FS_FIND_NEXT, fs_g_status, nav_dir_cd(), nav_dir_gotoparent(), nav_file_isdir(), nav_filelist_reset(), and nav_filelist_set().
Referenced by main(), nav_file_paste_state(), pl_main_close(), pl_main_modify(), and pl_main_save().
{
   U8 u8_folder_level = 0xFF;
   if ( !fat_check_mount_select_noopen())
      return FALSE;
   if( 0xFF == u8_folder_level )  // to remove a eventually compile warning
     goto nav_file_del_test_dir_or_file;
   // loop to scan and delete ALL folders and ALL files
   while(1)
   {
      while(1)
      {
         if( nav_filelist_set( 0 , FS_FIND_NEXT ) )
         {
            // Directory no empty
            if( b_only_empty )
            {
               fs_g_status = FS_ERR_DIR_NOT_EMPTY;      // Erase only the empty directory
               return FALSE;
            }
            break; // Exit loop to delete files or directories present
         }
         // HERE, directory empty
         // Go to parent directory and this one select the children directory
         if( !nav_dir_gotoparent() )
            return FALSE;
         // Delete children directory name and her cluster list
         if ( !fat_delete_file( TRUE ))
            return FALSE;
         if( 0 == u8_folder_level )
         {
            // All directory tree is deleted
            return TRUE; //********* END OF DEL TREE **************
         }
         u8_folder_level--;
      } // end of second while (1)
nav_file_del_test_dir_or_file:
      if( nav_file_isdir())
      {
         // here, a directory is found and is selected
         if( !nav_dir_cd())
            return FALSE;
         u8_folder_level++;
      }
      else
      {
         // here, a file is found and is selected
         if( !fat_check_nav_access_file( TRUE ) )
            return FALSE;
         // delete file entry name and cluster list
         if ( !fat_delete_file( TRUE ))
            return FALSE;
         if( 0xFF == u8_folder_level )
            break;   // only one file to delete
      } // if dir OR file
   } // end of first while(1)
   // Reset selection
   nav_filelist_reset();
   return fat_cache_flush();  // To write all data and check write access before exit function
}
Bool nav_file_getname (FS_STRING sz_name, U8 u8_size_max)
This function returns the name of selected file.
Parameters:
sz_name string to store the name file (ASCII or UNICODE)
u8_size_max string size (unit ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1748 of file navigation.c.
References FS_NAME_GET, and nav_file_name().
{
   return nav_file_name( sz_name, u8_size_max, FS_NAME_GET, FALSE );
}
Bool nav_file_isdir (void)
This function returns the type of selected file.
Returns:
TRUE, it is a directory
FALSE, in other case
Definition at line 1892 of file navigation.c.
References fat_entry_is_dir().
Referenced by main(), nav_file_copy(), nav_file_del(), nav_filterflat_next(), nav_filterflat_previous(), nav_filterlist_nb_ex(), nav_filterlist_next(), nav_filterlist_previous(), nav_flat_next(), nav_flat_previous(), navauto_mov_explorer_is_dir(), navauto_mov_explorer_is_file(), navauto_mov_explorer_rec(), and pl_add().
{
   return fat_entry_is_dir();
}
Bool nav_file_isreadonly (void)
This function checks the write protection of disk and the attribut "read only" of selected file.
Returns:
FALSE, it is possible to modify the selected file
TRUE, in other case
Definition at line 1877 of file navigation.c.
References fat_check_mount_select(), FS_ATTR_READ_ONLY, fs_g_nav, fs_g_nav_entry, mem_wr_protect(), Fs_management_entry::u8_attr, and Fs_management::u8_lun.
Referenced by pl_main_open().
{
   if( !fat_check_mount_select() )
      return TRUE;   // No file selected
   if( mem_wr_protect( fs_g_nav.u8_lun ) )
      return TRUE;   // Disk protected
   return (0!=(FS_ATTR_READ_ONLY & fs_g_nav_entry.u8_attr));   // Check attribut "read only"
}
U32 nav_file_lgt (void)
This function returns the size of selected file (unit byte).
Returns:
Size of selected file (unit byte)
Definition at line 1856 of file navigation.c.
References fs_g_nav_entry, and Fs_management_entry::u32_size.
Referenced by fsaccess_file_get_size(), main(), nav_file_paste_state(), and pl_add().
{
   return fs_g_nav_entry.u32_size;
}
U16 nav_file_lgtsector (void)
This function returns the size of selected file (unit sector).
Returns:
Size of selected file (unit 512B)
Definition at line 1866 of file navigation.c.
References FS_512B_SHIFT_BIT, fs_g_nav_entry, and Fs_management_entry::u32_size.
Referenced by main().
{
   return (fs_g_nav_entry.u32_size >> FS_512B_SHIFT_BIT);
}
Bool nav_file_name (FS_STRING sz_name, U8 u8_size_max, Bool b_mode, Bool b_match_case)
This function returns the name of selected file or checks the string with the name of selected file.
Parameters:
b_mode action mode:
FS_NAME_GET to get the name of selected file
FS_NAME_CHECK to check the name of selected file
sz_name if FS_NAME_GET then string to store the file name (ASCII or UNICODE)
if FS_NAME_CHECK then string to match with file name (ASCII or UNICODE), it must be terminated by NULL or '*' value
b_match_case FALSE, ignore the case (only used in "FS_NAME_CHECK" action)
u8_size_max string size (unit ASCII or UNICODE), only used in "FS_NAME_GET" action
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1769 of file navigation.c.
References fat_check_mount_select(), fat_entry_longname(), fat_entry_shortname(), fat_read_dir(), FS_ERR_ENTRY_BAD, fs_g_nav_fast, fs_g_status, FS_NAME_GET, FS_NO_LAST_LFN_ENTRY, FS_SIZE_LFN_ENTRY, g_b_string_length, Is_unicode, and Fs_management_fast::u16_entry_pos_sel_file.
Referenced by main(), nav_dir_name(), nav_file_getname(), nav_filelist_findname(), nav_filterflat_findname(), nav_filterlist_findname(), nav_flat_findname(), nav_getcwd(), and pl_main_close().
{
   _MEM_TYPE_SLOW_   U16 u16_lgt;   // Only used if LENGTH string mode enabled
   U16  u16_ptr_save_entry;
   Bool  b_readshortname = FALSE;
   if ( !fat_check_mount_select())
      return FALSE;
   // Check if the string size is not 0
   if( (FS_NAME_GET == b_mode)
   &&  (0 == u8_size_max) )
   {
      return TRUE;
   }
   // Save the current entry position
   u16_ptr_save_entry = fs_g_nav_fast.u16_entry_pos_sel_file;
   // if it is the beginning of the directory
   if ( 0 == fs_g_nav_fast.u16_entry_pos_sel_file )
   {
      b_readshortname = TRUE;                   // It isn't possibled to have a long name
   }
   else
   {
      fs_g_nav_fast.u16_entry_pos_sel_file--;   // Initialize entry position to search the first long name entry
   }
   // Loop in directory entry
   u16_lgt = 0;
   while( 1 )
   {
      if ( !fat_read_dir())
         break; // error
      if ( b_readshortname )
      {
         // No long name present then read short name
         return fat_entry_shortname( sz_name , u8_size_max , b_mode  );
      }
      // Check or read the part of long file name in this entry
      if ( fat_entry_longname( sz_name , u8_size_max , b_mode , b_match_case  ))
      {
         if( g_b_string_length )
         {
            ((FS_STR_UNICODE)sz_name )[0] += u16_lgt;
         }
         fs_g_nav_fast.u16_entry_pos_sel_file = u16_ptr_save_entry;
         return TRUE;
      }
      if ( FS_NO_LAST_LFN_ENTRY != fs_g_status )
      {
         // Go to the main entry file (=short name entry)
         fs_g_nav_fast.u16_entry_pos_sel_file = u16_ptr_save_entry;
         if ( FS_ERR_ENTRY_BAD == fs_g_status )
         {
            // It isn't a long name entry then there aren't long file name
            b_readshortname = TRUE;   // It is mandatory to use the short name
            continue;                 // restart the loop
         }
         // here, it is a error system or the string don't match with the file name
         break;
      }
      if( g_b_string_length )
      {
         u16_lgt += FS_SIZE_LFN_ENTRY;
      }
      else
      {
         // Increment the string to store the next part of file name
         sz_name += FS_SIZE_LFN_ENTRY * (Is_unicode? 2 : 1 );
         u8_size_max -= FS_SIZE_LFN_ENTRY;
      }
      fs_g_nav_fast.u16_entry_pos_sel_file--;   // Go to the next part of long file name
   }  // end of loop while(1)
   return FALSE;
}
Bool nav_file_paste_start (const FS_STRING sz_name)
This function pastes the selected file in COPY navigator in the file list of the current navigator.
Parameters:
sz_name file name of the new file (ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After this routine, you shall called nav_file_paste_state() to run and way the copy
//!
Definition at line 2215 of file navigation.c.
References file_close(), file_open(), FOPEN_MODE_R, FOPEN_MODE_W_PLUS, FS_ERR_COPY_RUNNING, fs_g_status, FS_NAV_ID_COPYFILE, g_id_trans_memtomem, g_segment_src, ID_STREAM_ERR, nav_file_create(), nav_get(), nav_select(), and Fs_file_segment::u16_size.
Referenced by main(), and pl_main_modify().
{
   U8 nav_id_save;
   Bool status;
   if( ID_STREAM_ERR != g_id_trans_memtomem )
   {
      fs_g_status = FS_ERR_COPY_RUNNING;  // A copy action is always running
      return FALSE;
   }
   // Create the file to paste
   if( !nav_file_create( sz_name  ) )
      return FALSE;
   // Open the file in write mode with size 0
   if( !file_open( FOPEN_MODE_W_PLUS ))
      return FALSE;
   // Open the file to copy
   nav_id_save = nav_get();
   nav_select( FS_NAV_ID_COPYFILE );
   status = file_open(FOPEN_MODE_R);
   nav_select( nav_id_save );
   // If error then close "paste file"
   if( !status )
   {
      file_close();
      return FALSE;
   }else{
      // Signal start copy
      g_id_trans_memtomem = ID_STREAM_ERR-1;
      g_segment_src.u16_size = 0;
      return TRUE;
   }
}
U8 nav_file_paste_state (Bool b_stop)
This function executes the copy file.
Parameters:
b_stop set TRUE to stop copy action
Returns:
copy status
COPY_BUSY, copy running COPY_FAIL, copy fail COPY_FINISH, copy finish
Definition at line 2263 of file navigation.c.
References COPY_BUSY, COPY_FAIL, COPY_FINISH, CTRL_BUSY, CTRL_FAIL, CTRL_GOOD, file_close(), file_eof(), file_read(), file_seek(), file_set_eof(), file_write(), FS_512B, FS_NAV_ID_COPYFILE, FS_SEEK_CUR_RE, FS_SEEK_SET, g_id_trans_memtomem, g_segment_dest, g_segment_src, ID_STREAM_ERR, nav_file_del(), nav_file_lgt(), nav_get(), nav_select(), SIZE_OF_SPLIT_COPY, stream_mem_to_mem(), stream_state(), stream_stop(), Fs_file_segment::u16_size, Fs_file_segment::u32_addr, and Fs_file_segment::u8_lun.
Referenced by main(), and pl_main_modify().
{
   Ctrl_status status_stream;
   U8 status_copy;
   U8 nav_id_save;
   _MEM_TYPE_SLOW_ U16 u16_nb_sector_trans;
   nav_id_save = nav_get();
   // Check, if the copy is running
   if( ID_STREAM_ERR == g_id_trans_memtomem )
      return COPY_FAIL;
   if( b_stop )
   {
      status_copy = COPY_FAIL;
   }
   else
   {
      if( (ID_STREAM_ERR-1) != g_id_trans_memtomem )
      {
         // It isn't the beginning of copy action, then check current stream
         status_stream = stream_state( g_id_trans_memtomem );
         switch( status_stream )
         {
         case CTRL_BUSY:
            status_copy = COPY_BUSY;
            break;
         case CTRL_GOOD:
            status_copy = COPY_FINISH;
            break;
         case CTRL_FAIL:
         default:
            status_copy = COPY_FAIL;
            break;
         }
      }else{
         status_copy = COPY_FINISH;
      }
      // Compute the new segment to copy
      if( COPY_FINISH == status_copy )
      {
         stream_stop( g_id_trans_memtomem );
         if( 0 != g_segment_src.u16_size )
         {
            status_copy = COPY_BUSY;            // start the next continue stream
         }
         else
         {
            // check eof source file
            nav_select( FS_NAV_ID_COPYFILE );
            if( 0 == file_eof() )
            {
               status_copy = COPY_BUSY;
               g_segment_src.u16_size = 0xFFFF; // Get the maximum segment supported by navigation (U16)
               if( !file_read( &g_segment_src ))
               {
                  status_copy = COPY_FAIL;
               }
            }
            nav_select( nav_id_save );
            // Check destination file
            if( COPY_BUSY == status_copy )
            {
                g_segment_dest.u16_size = g_segment_src.u16_size; // Ask the segment no more larger than source segment
                if( !file_write( &g_segment_dest ))
               {
                  status_copy = COPY_FAIL;
               }
            }
            // Start new segment copy
            if( COPY_BUSY == status_copy )
            {
               // Compute a minimal segment
                if( g_segment_src.u16_size > g_segment_dest.u16_size )
               {
                  // Reposition source file
                  nav_select( FS_NAV_ID_COPYFILE );
                   if( !file_seek( (U32)(g_segment_src.u16_size - g_segment_dest.u16_size)*FS_512B , FS_SEEK_CUR_RE ))
                  {
                     status_copy = COPY_FAIL;
                  }
                  nav_select( nav_id_save );
                   g_segment_src.u16_size = g_segment_dest.u16_size; // Update source to start a correct transfer
               }
            }
         }
         if( COPY_BUSY == status_copy )
         {
            // Split transfer by step of SIZE_OF_SPLIT_COPY
            if( g_segment_src.u16_size < SIZE_OF_SPLIT_COPY )
               u16_nb_sector_trans = g_segment_src.u16_size;
            else
               u16_nb_sector_trans = SIZE_OF_SPLIT_COPY;
            g_id_trans_memtomem = stream_mem_to_mem( g_segment_src.u8_lun , g_segment_src.u32_addr , g_segment_dest.u8_lun , g_segment_dest.u32_addr , u16_nb_sector_trans );
            if( ID_STREAM_ERR == g_id_trans_memtomem )
                  status_copy = COPY_FAIL;
            g_segment_src.u32_addr +=u16_nb_sector_trans;
            g_segment_dest.u32_addr+=u16_nb_sector_trans;
            g_segment_src.u16_size -=u16_nb_sector_trans;
         }
      }
   }
   // Check end of copy
   if( COPY_BUSY != status_copy )
   {
      U32 u32_size_exact;
      // Stop copy
      stream_stop( g_id_trans_memtomem );
      g_id_trans_memtomem = ID_STREAM_ERR;
      // Get exact size and close the source file
      nav_select( FS_NAV_ID_COPYFILE );
      u32_size_exact = nav_file_lgt();
      file_close();
      nav_select( nav_id_save );
      // If no error then set the exact size on the destination file
      if( COPY_FINISH == status_copy )
      {
         if( !file_seek( u32_size_exact , FS_SEEK_SET ))
         {
            status_copy = COPY_FAIL;
         }else{
            if( !file_set_eof() )
            {
               status_copy = COPY_FAIL;
            }
         }
      }
      file_close();
      // If error then delete the destination file
      if( COPY_FAIL == status_copy )
      {
         nav_file_del( TRUE );
      }
   }
   return status_copy;
}
Bool nav_file_rename (const FS_STRING sz_name)
This function renames the selected directory or file.
Parameters:
sz_name new name (ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 2096 of file navigation.c.
References Fs_management::b_mode_nav, fat_cache_flush(), fat_check_mount_select_noopen(), fat_check_nav_access_file(), fat_delete_file(), fat_read_dir(), fat_write_entry_file(), fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, nav_file_create(), nav_filelist_last(), Fs_management_fast::u16_entry_pos_sel_file, Fs_management_entry::u32_cluster, Fs_management_entry::u32_size, and Fs_management_entry::u8_attr.
Referenced by main(), and pl_main_close().
{
   U16 u16_save_entry_pos;
   Bool b_save_entry_type;
   U8 u8_attr;
   U32 u32_cluster;
   U32 u32_size;
   if ( !fat_check_mount_select_noopen())
      return FALSE;
   if( !fat_check_nav_access_file( TRUE ) )
      return FALSE;
   // Note: in case of error, create the new name before delete the current name
   // Save information about current name poisition
   u16_save_entry_pos = fs_g_nav_fast.u16_entry_pos_sel_file;
   b_save_entry_type  = fs_g_nav.b_mode_nav;
   // Save information about file
   u8_attr           = fs_g_nav_entry.u8_attr;
   u32_cluster       = fs_g_nav_entry.u32_cluster;
   u32_size          = fs_g_nav_entry.u32_size;
   // Create a name
   if ( !nav_file_create( sz_name  ))
      return FALSE; // error
   // Restore information about file or directory on the new name entry
   if ( !fat_read_dir())
      return FALSE;
   fs_g_nav_entry.u8_attr = u8_attr;
   fs_g_nav_entry.u32_cluster = u32_cluster;
   fs_g_nav_entry.u32_size = u32_size;
   fat_write_entry_file();
   // Delete old entry name
   fs_g_nav_fast.u16_entry_pos_sel_file = u16_save_entry_pos; // go to old entry name
   if ( !fat_delete_file(FALSE) )
      return FALSE;
   if ( !fat_cache_flush() )
      return FALSE;
   // Go to at the position of the new name entry (it is the last file or directory )
   return nav_filelist_last( b_save_entry_type );
}
Bool nav_filelist_bol (void)
This function checks the beginning of file list.
Returns:
FALSE, it is not the beginning of file list
TRUE, in case of the file selected is the first file, or in case of error
Definition at line 947 of file navigation.c.
References FS_FIND_NEXT, FS_FIND_PREV, and nav_filelist_set().
{
   if( FALSE == nav_filelist_set( 0 , FS_FIND_PREV ) )
      return TRUE;   // End of list or error (remark: the position haven't changed)
   // Go to previous position
   nav_filelist_set( 0 , FS_FIND_NEXT );
   return FALSE;
}
Bool nav_filelist_eol (void)
This function checks the end of file list.
Returns:
FALSE, NO end of file list
TRUE, in case of end of list or error
Definition at line 923 of file navigation.c.
References Fs_management::b_mode_nav, FS_DIR, FS_FIND_NEXT, FS_FIND_PREV, fs_g_nav, fs_g_nav_fast, FS_NO_SEL, nav_filelist_set(), Fs_management_fast::u16_entry_pos_sel_file, and Fs_management::u16_pos_sel_file.
{
   if( FALSE == nav_filelist_set( 0 , FS_FIND_NEXT ) )
      return TRUE;   // End of list or error (remark: the position haven't changed)
   if( 0 != fs_g_nav.u16_pos_sel_file )
   {
      // Go to previous position
      nav_filelist_set( 0 , FS_FIND_PREV );
   }else{
      // No select file before, then reset position
      fs_g_nav_fast.u16_entry_pos_sel_file= FS_NO_SEL;
      fs_g_nav.u16_pos_sel_file           = FS_NO_SEL;
      fs_g_nav.b_mode_nav                 = FS_DIR;
   }
   return FALSE;
}
Bool nav_filelist_exist (Bool b_type)
This function checks the presence of files or directories in file list.
Parameters:
b_type FS_DIR to check the directory presence
FS_FILE to check the file presence
Returns:
TRUE, in case of a file or a directory exists
FALSE, in case of no file or no directory exists, or error
Definition at line 965 of file navigation.c.
References FS_FIND_NEXT, fs_g_nav, FS_NO_SEL, nav_filelist_first(), nav_filelist_reset(), nav_filelist_set(), and Fs_management::u16_pos_sel_file.
{
   Bool status;
   U16   u16_save_position;
   // Save current position
   u16_save_position = fs_g_nav.u16_pos_sel_file;
   // Go to first file or directory
   status = nav_filelist_first( b_type );
   // Restore previous position
   nav_filelist_reset();
   if ( u16_save_position != FS_NO_SEL )
   {
      nav_filelist_set( u16_save_position , FS_FIND_NEXT );
   }
   return status;
}
Bool nav_filelist_fileisnotopen (void)
This function checks if no file is open.
Returns:
TRUE if no file is open
FALSE if a file is open
Definition at line 703 of file navigation.c.
References fat_check_noopen().
Referenced by nav_flat_fileisnotopen().
{
   return fat_check_noopen();
}
Bool nav_filelist_findname (const FS_STRING sz_name, Bool b_match_case)
This function searchs a file name in file list.
Parameters:
sz_name name to search (UNICODE or ASCII)
It must be terminate by NULL or '*' value
b_match_case FALSE to ignore the case
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! This function starts a search at the next position of the current in file list
//!
Definition at line 906 of file navigation.c.
References FS_FIND_NEXT, FS_NAME_CHECK, nav_file_name(), and nav_filelist_set().
Referenced by nav_file_create(), and nav_setcwd().
{
   while( 1 )
   {
      if ( !nav_filelist_set( 0, FS_FIND_NEXT ))
         return FALSE;
      if ( nav_file_name( sz_name , 0 , FS_NAME_CHECK , b_match_case ))
         return TRUE;
   }
}
Bool nav_filelist_first (Bool b_type)
This function goes to at the first file or directory in file list.
Parameters:
b_type FS_DIR to go at the first directory
FS_FILE to go at the first file
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1034 of file navigation.c.
References Fs_management::b_mode_nav, FS_ERR_NO_FIND, FS_FIND_NEXT, fs_g_nav, fs_g_status, nav_filelist_reset(), and nav_filelist_set().
Referenced by main(), nav_filelist_exist(), nav_filelist_last(), navauto_mov_explorer_select_limit_dir_cur_folder(), and navauto_mov_explorer_select_limit_file_cur_folder().
{
   // Reset position
   if ( !nav_filelist_reset())
      return FALSE;
   // Find the first file or directory
   while( nav_filelist_set( 0 , FS_FIND_NEXT ) )
   {
      if( b_type == fs_g_nav.b_mode_nav )
         return TRUE;   // First file or directory found
   }
   fs_g_status = FS_ERR_NO_FIND;
   return FALSE;
}
U16 nav_filelist_get (void)
This function returns the position of selected file in file list.
Returns:
position of selected file (0 is the first position)
FS_NO_SEL, in case of no file selected
Definition at line 846 of file navigation.c.
References fs_g_nav, and Fs_management::u16_pos_sel_file.
Referenced by nav_filelist_goto(), nav_filterlist_next(), nav_filterlist_previous(), nav_flat_get(), nav_flat_next(), and nav_flat_previous().
{
   return fs_g_nav.u16_pos_sel_file;
}
Bool nav_filelist_goto (U16 u16_newpos)
This function goes at a position in file list.
Parameters:
u16_newpos new position to select (0 is the first position)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 859 of file navigation.c.
References FS_FIND_NEXT, FS_FIND_PREV, FS_NO_SEL, nav_filelist_get(), nav_filelist_reset(), and nav_filelist_set().
Referenced by nav_filterlist_next(), and nav_filterlist_previous().
{
   U16 u16_current_pos;
   if( FS_NO_SEL == u16_newpos )
      return nav_filelist_reset();
   u16_current_pos = nav_filelist_get();
   if( u16_newpos < (u16_current_pos/2) )
   {
      // Restart at the beginning of list to accelerate the search
      if( !nav_filelist_reset() )
         return FALSE;
      u16_current_pos = FS_NO_SEL;
   }
   if (FS_NO_SEL == u16_current_pos)
   {
      return nav_filelist_set( u16_newpos, FS_FIND_NEXT );
   }
   else
   {
      if (u16_newpos < u16_current_pos)
      {
         return nav_filelist_set( u16_current_pos -u16_newpos -1 , FS_FIND_PREV );
      }
      if (u16_newpos > u16_current_pos)
      {
         return nav_filelist_set( u16_newpos -u16_current_pos - 1 , FS_FIND_NEXT );
      }
   }
   return TRUE;
}
Bool nav_filelist_last (Bool b_type)
This function goes to at the last file or directory in file list.
Parameters:
b_type FS_DIR to go at the last directory
FS_FILE to go at the last file
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1058 of file navigation.c.
References FS_ERR_NO_FIND, FS_FIND_NEXT, fs_g_status, nav_filelist_first(), nav_filelist_nb(), and nav_filelist_set().
Referenced by nav_dir_make(), nav_file_rename(), navauto_mov_explorer_select_limit_dir_cur_folder(), and navauto_mov_explorer_select_limit_file_cur_folder().
{
   U16 u16_nb;
   // Get number of file or directory
   u16_nb = nav_filelist_nb( b_type  );
   if( 0 == u16_nb )
   {
      fs_g_status = FS_ERR_NO_FIND;
      return FALSE;  // NO FILE FOUND
   }
   // Go to the first file or directory
   if ( !nav_filelist_first( b_type ))
      return FALSE;
   // If there are more one file or directory, then go to at the last of list
   if( 1 == u16_nb )
      return TRUE;
   u16_nb -= 2;
   return nav_filelist_set( u16_nb , FS_FIND_NEXT );
}
U16 nav_filelist_nb (Bool b_type)
This function computes the number of files or directories in file list.
Parameters:
b_type FS_DIR to compute the number of directories
FS_FILE to compute the number of files
Returns:
number of files or directories in file list
Definition at line 991 of file navigation.c.
References Fs_management::b_mode_nav, FS_FILE, FS_FIND_NEXT, fs_g_nav, FS_NO_SEL, nav_filelist_reset(), nav_filelist_set(), and Fs_management::u16_pos_sel_file.
Referenced by main(), nav_filelist_last(), and navauto_mov_explorer().
{
   U16   u16_save_position;
   U16   u16_save_number_dir;
   U16   u16_save_number_file;
   // Save current position
   u16_save_position = fs_g_nav.u16_pos_sel_file;
   // Reset position
   if ( !nav_filelist_reset())
      return 0;
   // Scan all directory
   u16_save_number_dir  = 0;
   u16_save_number_file = 0;
   while( nav_filelist_set( 0 , FS_FIND_NEXT ) )
   {
      if( FS_FILE == fs_g_nav.b_mode_nav )
         u16_save_number_file++;    // It is a file
      else
         u16_save_number_dir++;     // It is a directory
   }
   // Restore previous position
   nav_filelist_reset();
   if ( u16_save_position != FS_NO_SEL )
   {
      nav_filelist_set( u16_save_position , FS_FIND_NEXT );
   }
   // Return the value asked
   if( FS_FILE == b_type )
      return u16_save_number_file;
   else
      return u16_save_number_dir;
}
Bool nav_filelist_reset (void)
This function resets the selection pointer, so "no file selected" in file list.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 676 of file navigation.c.
References fat_check_mount_noopen(), and fat_clear_entry_info_and_ptr().
Referenced by main(), nav_dir_cd(), nav_dir_gotoparent(), nav_file_create(), nav_file_del(), nav_filelist_exist(), nav_filelist_first(), nav_filelist_goto(), nav_filelist_nb(), nav_filelist_single_disable(), nav_filelist_single_enable(), nav_filterlist_reset(), nav_flat_gotoparent(), nav_flat_reset(), nav_gotoindex(), nav_setcwd(), navauto_mov_explorer_limit(), navauto_open(), pl_add(), pl_main_open(), pl_main_readline(), and pl_nav_setpos().
{
   if ( !fat_check_mount_noopen())
      return FALSE;
   // No file selected and reset navigation
   fat_clear_entry_info_and_ptr();
   return TRUE;
}
Bool nav_filelist_set (U16 u16_nb, Bool b_direction)
This function moves the selection pointer in file list.
Parameters:
u16_nb numbers of file to jump before stopping action
0, stop at the first file found
1, stop at the second file found
b_direction search direction
FS_FIND_NEXT, move to next file or directory FS_FIND_PREV, move to previous file or directory
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Note: if no file is selected then nav_filelist_set(0 , FS_NEXT) goes to the first entry of the file list.
//!
Definition at line 726 of file navigation.c.
References Fs_management::b_mode_nav, Fs_management::b_mode_nav_single, fat_check_mount_noopen(), fat_entry_check(), fat_get_entry_info(), fat_read_dir(), FS_DIR, FS_END_FIND, FS_ERR_ENTRY_EMPTY, FS_ERR_FS, FS_ERR_NO_FIND, FS_ERR_OUT_LIST, FS_FILE, FS_FIND_NEXT, fs_g_nav, fs_g_nav_fast, fs_g_status, FS_NO_SEL, Fs_management_fast::u16_entry_pos_sel_file, and Fs_management::u16_pos_sel_file.
Referenced by main(), nav_dir_gotoparent(), nav_file_del(), nav_filelist_bol(), nav_filelist_eol(), nav_filelist_exist(), nav_filelist_findname(), nav_filelist_first(), nav_filelist_goto(), nav_filelist_last(), nav_filelist_nb(), nav_filterlist_nb_ex(), nav_filterlist_next(), nav_filterlist_previous(), nav_flat_next(), nav_flat_previous(), nav_gotoindex(), navauto_mov_explorer_is_dir(), navauto_mov_explorer_is_file(), navauto_mov_explorer_select_limit_file_cur_folder(), navauto_open(), and pl_add().
{
   U16   u16_ptr_save_entry;
   U16   u16_save_pos_sel_file;
   Bool  b_save_entry_type;
   Bool  b_find_last_entry = FALSE;
   if ( !fat_check_mount_noopen())
      return FALSE;
   // Save the current selection
   u16_ptr_save_entry      = fs_g_nav_fast.u16_entry_pos_sel_file;
   u16_save_pos_sel_file   = fs_g_nav.u16_pos_sel_file;
   b_save_entry_type       = fs_g_nav.b_mode_nav;
   // Loop in directory
   while( 1 )
   {
      if(( FS_FIND_NEXT == b_direction )
      || ( b_find_last_entry ) )
      {
         if ( FS_END_FIND == fs_g_nav_fast.u16_entry_pos_sel_file )
         {
            // Too many files in directory (case impossible)
            fs_g_status = FS_ERR_FS;
            break;
         }
         fs_g_nav_fast.u16_entry_pos_sel_file++;      // Update entry position
      }
      else
      {
         if ( FS_NO_SEL == fs_g_nav_fast.u16_entry_pos_sel_file )
         {
            // No selected file then previous action impossible
            fs_g_status = FS_ERR_NO_FIND;
            break;
         }
         if ( 0 == fs_g_nav_fast.u16_entry_pos_sel_file )
         {
            // beginning of directory
            if ( (FS_DIR == fs_g_nav.b_mode_nav ) || fs_g_nav.b_mode_nav_single )
            {
               // End of directory scan, then no previous action possible
               fs_g_status = FS_ERR_NO_FIND;
               break;
            }
            // End of file scan, then find last directory
            b_find_last_entry = TRUE;
         }else{
            fs_g_nav_fast.u16_entry_pos_sel_file--;   // Update entry position
         }
      }
      if( !fat_read_dir())
      {
         if( FS_ERR_OUT_LIST != fs_g_status )
            break; // Error
      }else{
         if ( fat_entry_check( fs_g_nav.b_mode_nav ) )
         {
           // HERE, the file entry match with the type seached
           if( b_find_last_entry )
             continue;  // The search of last directory is on going then continue the search
           // Update position in directory
           if ( FS_FIND_NEXT == b_direction )
              fs_g_nav.u16_pos_sel_file++;
           else
              fs_g_nav.u16_pos_sel_file--;
           if (0 == u16_nb)
           {
              // It is the end of move then update file information
              fat_get_entry_info();
              return TRUE;         // NB FILE FIND
           }
           u16_nb--;
           continue;
         }
      }
      // Here error, check type of error
      if(( FS_ERR_ENTRY_EMPTY == fs_g_status )
      || ( FS_ERR_OUT_LIST    == fs_g_status ) )
      {
         // Here, end of the directory
         if( b_find_last_entry )
         {
            // Re enable the previous command at the end of directory to find the last directory entry
            b_find_last_entry = FALSE;
            fs_g_nav.b_mode_nav = FS_DIR;
            continue;
         }
         // Here, a next action is on going
         if ( (FS_FILE == fs_g_nav.b_mode_nav) || fs_g_nav.b_mode_nav_single )
         {
            // End of next file action then end of next action
            fs_g_status = FS_ERR_NO_FIND; // No file found
            break;                        // end of search
         }else{
            // End of next dir action then starts the next file action at the beginning of directory
            fs_g_nav_fast.u16_entry_pos_sel_file = 0xFFFF;
            fs_g_nav.b_mode_nav = FS_FILE;
         }
      }
   }  // end of loop while(1)
   fs_g_nav.b_mode_nav                    = b_save_entry_type;
   fs_g_nav_fast.u16_entry_pos_sel_file   = u16_ptr_save_entry;
   fs_g_nav.u16_pos_sel_file              = u16_save_pos_sel_file;
   return FALSE;
}
Bool nav_filelist_single_disable (void)
To display in File List the directories AND files.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 664 of file navigation.c.
References Fs_management::b_mode_nav_single, fs_g_nav, and nav_filelist_reset().
Referenced by nav_filterlist_nb_ex().
{
   fs_g_nav.b_mode_nav_single = FALSE;
   return nav_filelist_reset();
}
Bool nav_filelist_single_enable (Bool b_type)
To display in File List only the files OR directories.
Parameters:
b_type FS_DIR to display only directories presence
FS_FILE to dispaly only files presence
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 648 of file navigation.c.
References Fs_management::b_mode_nav, Fs_management::b_mode_nav_single, fs_g_nav, and nav_filelist_reset().
Referenced by nav_filterlist_nb_ex().
{
   if ( !nav_filelist_reset())
      return FALSE;
   fs_g_nav.b_mode_nav_single = TRUE;
   fs_g_nav.b_mode_nav        = b_type;
   return TRUE;
}
Bool nav_filelist_validpos (void)
This function checks if a file is selected.
Returns:
TRUE if a file is selected
FALSE if no file is selected
Definition at line 692 of file navigation.c.
References fat_check_mount_select_noopen().
Referenced by nav_flat_validpos(), navauto_mov_explorer_rec(), navauto_mov_playlist(), navauto_open(), and pl_sel_isvalid().
{
   return fat_check_mount_select_noopen();
}
U8 nav_get (void)
This function returns the navigation identifier used.
Returns:
u8_idnav navigator identifier selected
Definition at line 260 of file navigation.c.
References fs_g_u8_nav_selected.
Referenced by nav_file_paste_start(), nav_file_paste_state(), pl_add(), pl_main_close(), pl_main_modify(), pl_main_open(), pl_main_save(), pl_nav_readentry(), pl_nav_setpos(), pl_rem_dead(), pl_rem_sel(), and pl_rem_sel_all().
{
#if (FS_NB_NAVIGATOR > 1)
   return fs_g_u8_nav_selected;
#else
   return 0;
#endif
}
Bool nav_getcwd (FS_STRING sz_path, U8 u8_size_path, Bool b_view_file_select)
This function returns the full path of the selection.
Parameters:
sz_path string to store the path (ASCII or UNICODE)
u8_size_path string size (unit ASCII or UNICODE)
b_view_file_select TRUE, to include in path the selected file name
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1411 of file navigation.c.
References fat_check_mount_noopen(), fat_check_select(), FS_ERR_BUFFER_FULL, FS_ERR_IS_ROOT, fs_g_status, FS_NAME_GET, g_b_string_length, Is_unicode, nav_dir_gotoparent(), nav_drive_getname(), nav_file_name(), nav_getindex(), and nav_gotoindex().
Referenced by pl_add().
{
   _MEM_TYPE_SLOW_   Fs_index index;
   _MEM_TYPE_SLOW_   U16 u16_lgt=0;    // Only used if LENGTH string mode enabled
   U8 u8_save_size_path=0, u8_i;
   Bool status = FALSE;                // Error by default
   if ( !fat_check_mount_noopen())
      return FALSE;
   index = nav_getindex();             // Save current position
   if( g_b_string_length )
   {
      u16_lgt = 1;   // 1 for NULL terminate
   }
   else
   {
      u8_save_size_path = u8_size_path;
      // Set NULL terminator at the end of path
      u8_size_path--;
      if( Is_unicode )
      {
         ((FS_STR_UNICODE)sz_path )[u8_size_path] = 0;
      }else{
         sz_path [u8_size_path]   = 0;
      }
   }
   // For each directory of path
   while( 1 )
   {
      if( b_view_file_select )
      {
         // Write the selected file or directory in path
         b_view_file_select = FALSE;
         if( !fat_check_select() )
            continue;   // No selected file or directory, then restart loop to go at the first directory of path
      }
      else
      {
         // Go to parent directory and selects the children directory
         if( !nav_dir_gotoparent() )
            break;
      }
      // Read name of selected file or directory
      if( !nav_file_name( sz_path  , u8_size_path , FS_NAME_GET, FALSE  ))
         break;
      if( g_b_string_length )
      {
         // Update total length
         u16_lgt += ((FS_STR_UNICODE)sz_path )[0]; // 0 = -1 to remove NULL terminated and +1 for '\\'
         continue;
      }
      // Compute the size of name
      u8_i = 0;
      while( 1 )
      {
         if( Is_unicode )
         {
            if( 0 == ((FS_STR_UNICODE)sz_path )[u8_i])
               break;
         }else{
            if( 0 == sz_path [u8_i])
               break;
         }
         u8_i++;
      }
      // Check the string size
      if( (u8_i+1) == u8_size_path )
      {
         fs_g_status = FS_ERR_BUFFER_FULL;   // The path string is full
         break;
      }
      // Move the name at the end of path
      while( 0 != u8_i )
      {
         u8_i--;
         u8_size_path--;
         if( Is_unicode )
         {
            ((FS_STR_UNICODE)sz_path )[u8_size_path] = ((FS_STR_UNICODE)sz_path )[u8_i];
         }else{
            sz_path [u8_size_path]   = sz_path [u8_i];
         }
      }
      // Set '\' char before the name
      u8_size_path--;
      if( Is_unicode )
      {
         ((FS_STR_UNICODE)sz_path )[u8_size_path] = '\\';
      }else{
         sz_path [u8_size_path]   = '\\';
      }
   }
   if ( FS_ERR_IS_ROOT == fs_g_status )
   {
      if( g_b_string_length )
      {
         // Update and write total length
         ((FS_STR_UNICODE)sz_path )[0] = u16_lgt +2 ; //+2 for "x:"
         status = TRUE;
      }
      else
      {
         // End of path then add device name
         if( 2 > u8_size_path )
         {
            fs_g_status = FS_ERR_BUFFER_FULL;   // The path string is full
         }
         else
         {
            // Create a device name
            if( Is_unicode )
            {
               ((FS_STR_UNICODE)sz_path )[0] = nav_drive_getname();    // Letter
               ((FS_STR_UNICODE)sz_path )[1] = ':';                   // ":"
            }else{
               sz_path [0] = nav_drive_getname();    // Letter
               sz_path [1] = ':';                      // ":"
            }
            // The path is stored at the end, then move the path at the beginning
            u8_i = 2;
            while( u8_save_size_path != u8_size_path )
            {
               if( Is_unicode )
               {
                  ((FS_STR_UNICODE)sz_path )[u8_i] = ((FS_STR_UNICODE)sz_path )[u8_size_path];
               }else{
                  sz_path [u8_i] = sz_path [u8_size_path];
               }
               u8_i++;
               u8_size_path++;
            }
            status = TRUE;
         }
      }
   } // else Error system
   nav_gotoindex( &index );   // Restore the position
   return status;
}
Fs_index nav_getindex (void)
This function returns a small index on the selected file.
Returns:
It is a small index structure with information on selected file (disk, partition, dir, file/dir selected)
//! This routine is interresting to save a file position in small variable.
//! This pointer allow to reinit a navigator quickly with nav_gotoindex() routine.
//!
Definition at line 1093 of file navigation.c.
References fs_g_nav, fs_g_nav_fast, Fs_management_fast::u16_entry_pos_sel_file, Fs_index::u16_entry_pos_sel_file, Fs_management::u32_cluster_sel_dir, Fs_index::u32_cluster_sel_dir, Fs_management::u8_lun, Fs_index::u8_lun, Fs_management::u8_partition, and Fs_index::u8_partition.
Referenced by main(), nav_filterflat_gotoparent(), nav_flat_gotoparent(), nav_getcwd(), nav_partition_label(), nav_setcwd(), navauto_open(), pl_main_close(), pl_main_modify(), and pl_main_save().
{
   Fs_index index;
   // Fill index structure
   index.u8_lun                  = fs_g_nav.u8_lun;
#if (FS_MULTI_PARTITION  ==  ENABLED)
   index.u8_partition            = fs_g_nav.u8_partition;
#endif
   index.u32_cluster_sel_dir     = fs_g_nav.u32_cluster_sel_dir;
   index.u16_entry_pos_sel_file  = fs_g_nav_fast.u16_entry_pos_sel_file;
   return index;
}
Bool nav_gotoindex (const Fs_index _MEM_TYPE_SLOW_ * index)
This function selects a file in the navigator via a file index.
Parameters:
index structure with information about file to select (disk, partition, dir, file/dir selected)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! This routine allow to reinit a navigator quickly via a file index (disk, partition, dir, file/dir selected)
//! To get a file index, you shall used the routine nav_getindex().
//!
Definition at line 1120 of file navigation.c.
References FS_FIND_NEXT, fs_g_nav, fs_g_nav_fast, nav_drive_set(), nav_filelist_reset(), nav_filelist_set(), nav_partition_mount(), nav_partition_set(), Fs_management_fast::u16_entry_pos_sel_file, and Fs_management::u32_cluster_sel_dir.
Referenced by main(), nav_filterflat_gotoparent(), nav_flat_gotoparent(), nav_getcwd(), nav_partition_label(), nav_setcwd(), navauto_open(), pl_main_close(), pl_main_modify(), pl_main_save(), and pl_rem_dead().
{
   // Select the drive and partition corresponding at file index
   if( !nav_drive_set( index->u8_lun ))
      return FALSE;
#if (FS_MULTI_PARTITION  ==  ENABLED)
   if( !nav_partition_set(index->u8_partition))
      return FALSE;
#endif
   if( !nav_partition_mount())
      return FALSE;
   // Select the directory corresponding at file index
   fs_g_nav.u32_cluster_sel_dir   = index->u32_cluster_sel_dir;
   // Search the file position corresponding at file index
   if ( !nav_filelist_reset())
      return FALSE;
   while( fs_g_nav_fast.u16_entry_pos_sel_file != index->u16_entry_pos_sel_file )
   {
      if( !nav_filelist_set( 0 , FS_FIND_NEXT ) )
      {
         nav_filelist_reset();
         return FALSE;
      }
   }
   return TRUE;
}
U8 nav_partition_cluster_size (void)
This function returns the partition cluster size.
Returns:
cluster size (unit sector)
Definition at line 595 of file navigation.c.
References fs_g_nav, and Fs_management::u8_BPB_SecPerClus.
{
   return fs_g_nav.u8_BPB_SecPerClus;
}
U32 nav_partition_freespace (void)
This function returns the partition free space.
Returns:
number of free sectors
0 in case of error or full partition
//! You shall mounted the partition before call this routine
//!
Definition at line 609 of file navigation.c.
References fat_check_device(), fat_getfreespace(), fs_g_nav_fast, FS_TYPE_FAT_UNM, and Fs_management_fast::u8_type_fat.
Referenced by main().
{
   fat_check_device();
   if (FS_TYPE_FAT_UNM == fs_g_nav_fast.u8_type_fat)
      return 0;
   return fat_getfreespace();
}
U8 nav_partition_freespace_percent (void)
This function returns the partition space free in percent.
Returns:
percent of free space (0% to 100%)
0% in case of error or full partition
//! To speed up the compute, the resultat have an error delta of 1%
//!
Definition at line 627 of file navigation.c.
References fat_check_device(), fat_getfreespace_percent(), fs_g_nav_fast, FS_TYPE_FAT_UNM, and Fs_management_fast::u8_type_fat.
{
   fat_check_device();
   if (FS_TYPE_FAT_UNM == fs_g_nav_fast.u8_type_fat)
      return 0;
   return fat_getfreespace_percent();
}
Bool nav_partition_label (Bool b_action, FS_STRING sz_label)
This function reads or writes the label of selected partition.
Parameters:
b_action to select the action
FS_LABEL_READ to read label
FS_LABEL_WRITE to write label
sz_label pointer on a ASCII string (11 chars + NULL terminator =12 bytes)
if FS_LABEL_READ, then the string is used to store label
if FS_LABEL_WRITE, then the string is used to give the new label
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 529 of file navigation.c.
References fat_entry_label(), fat_read_dir(), FS_ERR_ENTRY_EMPTY, fs_g_nav_fast, fs_g_status, FS_LABEL_READ, FS_LABEL_WRITE, nav_dir_root(), nav_getindex(), nav_gotoindex(), and Fs_management_fast::u16_entry_pos_sel_file.
{
   _MEM_TYPE_SLOW_   Fs_index index;
   Bool status = TRUE;
   index = nav_getindex();    // Save current position
   // Go to root dir
   if( nav_dir_root())
   {
      // Find field label
      fs_g_nav_fast.u16_entry_pos_sel_file = 0; // Go to first entry
      while( 1 )
      {
         if ( !fat_read_dir())
         {
            status = FALSE;
            break;               // error
         }
         if( fat_entry_label( FS_LABEL_READ , NULL ) )
            break;
         if( FS_ERR_ENTRY_EMPTY == fs_g_status )
            break;
         fs_g_nav_fast.u16_entry_pos_sel_file++;
      }
      if( TRUE == status )
      {
         // Find OK
         if( FS_LABEL_READ == b_action )
         {
            // Read field label
            if( !fat_entry_label( FS_LABEL_READ , sz_label ) )
               sz_label[0]=0;    // empty name
         }else{
            // Change field label
            status = fat_entry_label( FS_LABEL_WRITE , sz_label );
         }
      }
   }
   nav_gotoindex( &index );   // Restore the position
   return status;
}
Bool nav_partition_mount (void)
This function mounts the selected partition.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! If the FS_MULTI_PARTITION option is disabled
//! then the mount routine selects the first partition supported by file system. <br>
//! After mount, the file list contains files and directories of ROOT directory
//!
Definition at line 461 of file navigation.c.
References fat_check_noopen(), fat_clear_entry_info_and_ptr(), fat_mount(), fs_g_nav, fs_g_nav_fast, FS_TYPE_FAT_UNM, Fs_management::u32_cluster_sel_dir, and Fs_management_fast::u8_type_fat.
Referenced by main(), nav_dir_root(), nav_filterlist_gotoindex(), nav_filterlist_mount(), nav_flat_mount(), nav_gotoindex(), nav_partition_type(), nav_setcwd(), and navauto_mov_ok_loop().
{
   if ( !fat_check_noopen() )
      return FALSE;
   if( FS_TYPE_FAT_UNM != fs_g_nav_fast.u8_type_fat)
   {
      // Already mounted
      // Go to root directory
      fs_g_nav.u32_cluster_sel_dir   = 0;
      // No file is selected by default
      fat_clear_entry_info_and_ptr();
      return TRUE;
   }
   return fat_mount();
}
U8 nav_partition_nb (void)
This function returns the number of partitions present on drive.
Returns:
u8_number number of partitions
Definition at line 421 of file navigation.c.
References fat_get_nbpartition().
{
   return fat_get_nbpartition();
}
Bool nav_partition_serialnumber (Bool b_action, U8 _MEM_TYPE_SLOW_ * a_u8_sn)
This function reads or writes the serial number on the selected partition.
Parameters:
b_action to select the action
FS_SN_READ to read serial number
FS_SN_WRITE to write serial number
a_u8_sn pointer on an array (4 bytes)
if FS_SN_READ, then the array is used to store the serial number
if FS_SN_WRITE, then the array is used to give the new serial number
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 508 of file navigation.c.
References fat_check_mount(), and fat_serialnumber().
{
   if( !fat_check_mount())
      return FALSE;
   return fat_serialnumber( b_action , a_u8_sn );
}
Bool nav_partition_set (U8 partition_number)
This function selects a partition on drive.
Parameters:
partition_number partition number (0 to 3)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 434 of file navigation.c.
References fat_check_noopen(), fs_g_nav, fs_g_nav_fast, FS_TYPE_FAT_UNM, Fs_management::u8_partition, and Fs_management_fast::u8_type_fat.
Referenced by nav_filterlist_gotoindex(), and nav_gotoindex().
{
   if ( fs_g_nav.u8_partition == partition_number)
      return TRUE;   // It is the same
   if ( !fat_check_noopen() )
      return FALSE;
   // Go to partition
   fs_g_nav.u8_partition = partition_number;
   fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_UNM;
   return TRUE;
}
U32 nav_partition_space (void)
This function returns partition total space.
Returns:
number of sectors
0, in case of error
//! You shall mounted the partition before call this routine
//!
Definition at line 582 of file navigation.c.
References fat_check_device(), fs_g_nav, fs_g_nav_fast, FS_TYPE_FAT_UNM, Fs_management::u32_CountofCluster, Fs_management::u8_BPB_SecPerClus, and Fs_management_fast::u8_type_fat.
Referenced by main().
{
   fat_check_device();
   if (FS_TYPE_FAT_UNM == fs_g_nav_fast.u8_type_fat)
      return 0;
   return (fs_g_nav.u32_CountofCluster * fs_g_nav.u8_BPB_SecPerClus);
}
U8 nav_partition_type (void)
This function gives the partition type.
Returns:
partition type: FS_TYPE_FAT_12, FS_TYPE_FAT_16, FS_TYPE_FAT_32
FS_TYPE_FAT_UNM, in case of error or unknow format
Definition at line 485 of file navigation.c.
References fat_check_device(), fs_g_nav_fast, FS_TYPE_FAT_UNM, nav_partition_mount(), and Fs_management_fast::u8_type_fat.
Referenced by main().
{
   fat_check_device();
   if( FS_TYPE_FAT_UNM == fs_g_nav_fast.u8_type_fat)
   {
      nav_partition_mount();
   }
   return fs_g_nav_fast.u8_type_fat;
}
void nav_reset (void)
This function resets ALL navigations to init file system core.
//! Call this at the program startup or before a new session (e.g. USB Device exit)
//!
Definition at line 165 of file navigation.c.
References Fs_management::b_mode_nav_single, fat_cache_clusterlist_reset(), fat_cache_reset(), Fat_file_close, fs_g_nav, fs_g_nav_fast, fs_g_u8_nav_selected, FS_NB_NAVIGATOR, FS_TYPE_FAT_UNM, g_b_no_check_disk, g_b_string_length, g_b_unicode, nav_select(), Fs_management::u8_lun, Fs_management::u8_partition, and Fs_management_fast::u8_type_fat.
Referenced by b_fsaccess_init(), and main().
{
#if ((FS_ASCII   == ENABLED) && (FS_UNICODE == ENABLED))
   g_b_unicode = TRUE;
#endif
   g_b_string_length = FALSE;
   g_b_no_check_disk = FALSE;
   fat_cache_reset();
   fat_cache_clusterlist_reset();
#if (FS_NB_NAVIGATOR > 1)
   {
   U8 i;
   // Reset variables of each navigators
   for( i=0 ; i!=FS_NB_NAVIGATOR ; i++ )
   {
      nav_select(i);
      fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_UNM; // By default the fat isn't mounted
      fs_g_nav.u8_lun = 0xFF;                      // By default don't select a drive
#if (FS_MULTI_PARTITION  ==  ENABLED)
      fs_g_nav.u8_partition=0;                     // By default select the first partition
#endif
      Fat_file_close();                            // By default no file is opened
      fs_g_nav.b_mode_nav_single = FALSE;          // By default display files and directories
   }
   // By default select the navigator 0
   fs_g_u8_nav_selected = 0;
   }
#else
   fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_UNM;    // By default the fat isn't mounted
   fs_g_nav.u8_lun = 0xFF;                         // By default don't select a drive
#  if (FS_MULTI_PARTITION  ==  ENABLED)
   fs_g_nav.u8_partition=0;                        // By default select the first partition
#  endif
   Fat_file_close();                               // By default no file is opened
#endif // (FS_NB_NAVIGATOR > 1)
}
Bool nav_select (U8 u8_idnav)
This function selects the navigation to use.
Parameters:
u8_idnav navigator identifier to select (0 to FS_NB_NAVIGATOR-1)
Returns:
FALSE if ID navigator don't exist
TRUE otherwise
Definition at line 237 of file navigation.c.
References fat_invert_nav(), FS_ERR_BAD_NAV, fs_g_status, fs_g_u8_nav_selected, and FS_NB_NAVIGATOR.
Referenced by close(), fsaccess_file_get_size(), fsaccess_IsDirPresent(), nav_exit(), nav_file_paste_start(), nav_file_paste_state(), nav_reset(), open(), pl_add(), pl_main_close(), pl_main_modify(), pl_main_open(), pl_main_readline(), pl_main_save(), pl_nav_readentry(), pl_nav_setpos(), pl_rem_dead(), pl_rem_sel(), pl_rem_sel_all(), read(), and write().
{
   if( FS_NB_NAVIGATOR <= u8_idnav )
   {
      fs_g_status = FS_ERR_BAD_NAV;             // The navigator doesn't exist
      return FALSE;
   }
#if (FS_NB_NAVIGATOR > 1)
   if( fs_g_u8_nav_selected != u8_idnav )
   {
      fat_invert_nav( fs_g_u8_nav_selected );   // Deselect previous navigator = Select default navigator
      fat_invert_nav( u8_idnav );               // Select new navigator
      fs_g_u8_nav_selected = u8_idnav;
   }
#endif
   return TRUE;
}
Bool nav_setcwd (FS_STRING sz_path, Bool b_match_case, Bool b_create)
This function selects a disk position via a path.
Parameters:
sz_path path string (ASCII or UNICODE)
b_match_case FALSE to ignore the case
b_create TRUE, if path no exists then create it
FALSE, no create path
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! The syntact "./../../file_name" is supported.
//! With syntact "./dir_parent/directory_name"  the file list corresponding at "dir_parent" and "directory_name" is selected.
//! With syntact "./dir_parent/directory_name/" the file list corresponding at "directory_name" and no file is selected.
//!
Definition at line 1578 of file navigation.c.
References fat_check_noopen(), fat_entry_is_dir(), Is_unicode, nav_dir_cd(), nav_dir_gotoparent(), nav_dir_make(), nav_dir_root(), nav_drive_set(), nav_file_create(), nav_filelist_findname(), nav_filelist_reset(), nav_getindex(), nav_gotoindex(), and nav_partition_mount().
Referenced by fsaccess_IsDirPresent(), main(), open(), and pl_main_readline().
{
   _MEM_TYPE_SLOW_   Fs_index index;
#if (FSFEATURE_WRITE == (FS_LEVEL_FEATURES & FSFEATURE_WRITE)) ||              \
    (FSFEATURE_WRITE_COMPLET == (FS_LEVEL_FEATURES & FSFEATURE_WRITE_COMPLET))
   FS_STRING sz_save_path = 0;
#endif
   Bool b_create_name = FALSE;
   if ( !fat_check_noopen())
      return FALSE;
   index = nav_getindex();             // Save current position
   // Check syntact "\path..."
   if( (( Is_unicode) && (('\\'  == ((FS_STR_UNICODE)sz_path )[0]) || ('/'  == ((FS_STR_UNICODE)sz_path )[0])) )
   ||  ((!Is_unicode) && (('\\'  == sz_path [0]) || ('/'  == sz_path [0])) ) )
   {
      // Go to the root of current drive
      if( !nav_dir_root())
         goto nav_setcwd_fail;
      sz_path  += (Is_unicode? 2 : 1 );
   }else
   // Check syntact "x:\path..."
   if( (( Is_unicode) && (( ':'  == ((FS_STR_UNICODE)sz_path )[1] ) && (('\\'  == ((FS_STR_UNICODE)sz_path )[2] ) || ('/'  == ((FS_STR_UNICODE)sz_path )[2]))) )
   ||  ((!Is_unicode) && (( ':'  == sz_path [1] ) && (('\\'  == sz_path [2] ) || ('/'  == sz_path [2]))) ) )
   {
      // Go to the drive
      if( Is_unicode )
      {
         if( !nav_drive_set( toupper(((FS_STR_UNICODE)sz_path )[0])-'A' ) )
            goto nav_setcwd_fail;
      }else{
         if( !nav_drive_set( toupper(sz_path [0])-'A' ) )
            goto nav_setcwd_fail;
      }
      if( !nav_partition_mount())
         goto nav_setcwd_fail;
      sz_path  += 3*(Is_unicode? 2 : 1 );
   }else
   // Check syntact ".\path..."
   if( (( Is_unicode) && (( '.'  == ((FS_STR_UNICODE)sz_path )[0] ) && (('\\'  == ((FS_STR_UNICODE)sz_path )[1] ) || ('/'  == ((FS_STR_UNICODE)sz_path )[1] ))) )
   ||  ((!Is_unicode) && (( '.'  == sz_path [0] ) && (('\\'  == sz_path [1] ) || ('/'  == sz_path [1] ))) ) )
   {
      // Search in current directory
      sz_path  += 2*(Is_unicode? 2 : 1 );
   }else
   {
      // Check syntact "..\..\path..."
      if( Is_unicode )
      {
         while(( '.'  == ((FS_STR_UNICODE)sz_path )[0] )
         &&    ( '.'  == ((FS_STR_UNICODE)sz_path )[1] )
         &&    (('\\'  == ((FS_STR_UNICODE)sz_path )[2]) || ('/'  == ((FS_STR_UNICODE)sz_path )[2]) || (0  == ((FS_STR_UNICODE)sz_path )[2])) )
         {
            // Go to parent directory
            if( !nav_dir_gotoparent() )
               goto nav_setcwd_fail;
            sz_path  += (2*2); // jump ".."
            if( 0 != ((FS_STR_UNICODE)sz_path )[0])
               sz_path  += (2*1); // jump "/"
         }
      }else{
         while(( '.'  == sz_path [0] )
         &&    ( '.'  == sz_path [1] )
         &&    (('\\'  == sz_path [2]) || ('/'  == sz_path [2]) || (0  == sz_path [2])) )
         {
         // Go to parent directory
         if( !nav_dir_gotoparent() )
            goto nav_setcwd_fail;
            sz_path  += 2; // jump ".."
            if( 0 != sz_path [0])
               sz_path  +=1; // jump "/"
         }
      }
   }
   // Reset list to start the search at the beginning
   if( !nav_filelist_reset())
      goto nav_setcwd_fail;
   while( 1 )
   {
      if( (( Is_unicode) && ( 0 == ((FS_STR_UNICODE)sz_path )[0] ) )
      ||  ((!Is_unicode) && ( 0 == sz_path [0] ) ) )
      {
         return TRUE;   // path (without file) is found or create
      }
      if( !nav_filelist_findname( sz_path  , b_match_case  ))
      {
         // The file or directory is not found
         if( !b_create )
            goto nav_setcwd_fail;   // don't creat the directory then exit
         // Set flag to create the directory
         b_create_name = TRUE;
#if (FSFEATURE_WRITE == (FS_LEVEL_FEATURES & FSFEATURE_WRITE)) ||              \
    (FSFEATURE_WRITE_COMPLET == (FS_LEVEL_FEATURES & FSFEATURE_WRITE_COMPLET))
         sz_save_path = sz_path;
#endif
      }
      while( 1 )
      {
         sz_path  += (Is_unicode? 2 : 1 );
         if( (( Is_unicode) && ( 0 == ((FS_STR_UNICODE)sz_path )[0] ) )
         ||  ((!Is_unicode) && ( 0 == sz_path [0] ) ) )
         {
            // Is it the last name of path and it is a file
            if( b_create_name )
            {
#if (FSFEATURE_WRITE == (FS_LEVEL_FEATURES & FSFEATURE_WRITE))
               // The file must be created
               if( !nav_file_create( sz_save_path ) )
                  goto nav_setcwd_fail;
#else
               goto nav_setcwd_fail;
#endif
            }
            break;   // The file include in path is found or created, then end of set_cwd
         }
         if( (( Is_unicode) && (('\\' == ((FS_STR_UNICODE)sz_path )[0] ) || ('/' == ((FS_STR_UNICODE)sz_path )[0] )) )
         ||  ((!Is_unicode) && (('\\' == sz_path [0] ) || ('/' == sz_path [0] )) ) )
         {
            // Is it a folder name
            if( b_create_name )
            {
#if (FSFEATURE_WRITE_COMPLET == (FS_LEVEL_FEATURES & FSFEATURE_WRITE_COMPLET))
               // The folder doesn't exist and it must be created
               if( !nav_dir_make( sz_save_path ))
                  goto nav_setcwd_fail;
#else
               goto nav_setcwd_fail;
#endif
            }
            if( !fat_entry_is_dir() )
               goto nav_setcwd_fail;
            // jump '\'
            sz_path  += (Is_unicode? 2 : 1 );
            if( !nav_dir_cd())
               goto nav_setcwd_fail;
            break;
         }
      }
   }
nav_setcwd_fail:
   nav_gotoindex( &index );   // Restore the position
   return FALSE;
}
void nav_string_ascii (void)
This function selects the ASCII mode for all routines with FS_STRING parameter.
//! If you have enabled the FS_ASCII AND FS_UNICODE define
//! then FS_STRING parameter can be a ASCII or UNICODE string.
//!
Definition at line 98 of file navigation.c.
References g_b_unicode.
Referenced by pl_add(), and pl_main_modify().
{
   g_b_unicode = FALSE;
}
void nav_string_length_disable (void)
This function deselects the LENGTH string mode for all routines with FS_STRING parameter.
//! In LENGTH string mode when you call a routine with FS_STRING parameter
//! only the size (16bits, unit ASCII or UNICODE) is returned in the first 16bits of string array.
//!
Definition at line 122 of file navigation.c.
References g_b_string_length.
Referenced by pl_main_close().
{
   g_b_string_length = FALSE;
}
void nav_string_length_enable (void)
This function selects the LENGTH string mode for all routines with FS_STRING parameter.
//! In LENGTH string mode when you call a routine with FS_STRING parameter
//! only the size (16bits, unit ASCII or UNICODE) is returned in the first 16bits of string array.
//!
Definition at line 111 of file navigation.c.
References g_b_string_length.
Referenced by pl_main_close().
{
   g_b_string_length = TRUE;
}
void nav_string_unicode (void)
This function selects the UNICODE mode for all routines with FS_STRING parameter.
//! If you have enabled the FS_ASCII AND FS_UNICODE define
//! then FS_STRING parameter can be a ASCII or UNICODE string.
//!
Definition at line 87 of file navigation.c.
References g_b_unicode.
Referenced by pl_add(), and pl_main_modify().
{
   g_b_unicode = TRUE;
}
Variable Documentation
_MEM_TYPE_SLOW_ U8 fs_g_u8_nav_selected
Holds the current navigator selected.
Definition at line 64 of file navigation.c.
Referenced by nav_copy(), nav_get(), nav_reset(), and nav_select().
_MEM_TYPE_SLOW_ U8 g_id_trans_memtomem = ID_STREAM_ERR
Holds the current ID transfer used by the internal copy-paste routines.
Definition at line 59 of file navigation.c.
Referenced by nav_file_paste_start(), and nav_file_paste_state().
_MEM_TYPE_SLOW_ Fs_file_segment g_segment_dest
Definition at line 69 of file navigation.c.
Referenced by nav_file_paste_state().
_MEM_TYPE_SLOW_ Fs_file_segment g_segment_src
Definition at line 68 of file navigation.c.
Referenced by nav_file_paste_start(), and nav_file_paste_state().