AVR32 - FAT Services: ctrl_access.h File Reference
ctrl_access.h File Reference
Detailed Description
Abstraction layer for memory interfaces.
This module contains the interfaces:
MEM <-> USB;
MEM <-> RAM;
MEM <-> MEM.
This module may be configured and expanded to support the following features:
write-protected globals;
password-protected data;
specific features;
etc.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices can be used.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file ctrl_access.h.
#include "compiler.h"
#include "conf_access.h"
#include "virtual_mem.h"
#include "at45dbx_mem.h"
#include "sd_mmc_spi_mem.h"
#include <LUN_3_INCLUDE>
#include <LUN_4_INCLUDE>
#include <LUN_5_INCLUDE>
#include <LUN_6_INCLUDE>
#include <LUN_7_INCLUDE>
#include "host_mem.h"
Streaming MEM <-> MEM Interface
#define ID_STREAM_ERR 0xFF
Erroneous streaming data transfer ID.
Ctrl_status stream_mem_to_mem (U8 src_lun, U32 src_addr, U8 dest_lun, U32 dest_addr, U16 nb_sector)
Copies data from one memory to another.
Ctrl_status stream_state (U8 id)
Returns the state of a streaming data transfer.
U16 stream_stop (U8 id)
Stops a streaming data transfer.
Defines
LUN IDs
#define LUN_ID_0 (0)
First static LUN.
#define LUN_ID_1 (LUN_ID_0 + LUN_0)
#define LUN_ID_2 (LUN_ID_1 + LUN_1)
#define LUN_ID_3 (LUN_ID_2 + LUN_2)
#define LUN_ID_4 (LUN_ID_3 + LUN_3)
#define LUN_ID_5 (LUN_ID_4 + LUN_4)
#define LUN_ID_6 (LUN_ID_5 + LUN_5)
#define LUN_ID_7 (LUN_ID_6 + LUN_6)
#define LUN_ID_USB (MAX_LUN)
First dynamic LUN (USB host mass storage).
#define MAX_LUN (LUN_ID_7 + LUN_7)
Number of static LUNs.
Enumerations
enum Ctrl_status { CTRL_GOOD = PASS, CTRL_FAIL = FAIL, CTRL_NO_PRESENT = FAIL + 1, CTRL_BUSY = FAIL + 2 }
Status returned by CTRL_ACCESS interfaces.
Functions
Control Interface
U8 get_cur_lun (void)
Returns the current LUN.
U8 get_nb_lun (void)
Returns the number of LUNs.
const char * mem_name (U8 lun)
Returns a pointer to the LUN name.
Ctrl_status mem_read_capacity (U8 lun, U32 *u32_nb_sector)
Returns the address of the last valid sector (512 bytes) in the memory.
Bool mem_removal (U8 lun)
Tells whether the memory is removable.
U8 mem_sector_size (U8 lun)
Returns the size of the physical sector.
Ctrl_status mem_test_unit_ready (U8 lun)
Tests the memory state and initializes the memory if required.
Bool mem_wr_protect (U8 lun)
Returns the write-protection state of the memory.
MEM <-> RAM Interface
Ctrl_status memory_2_ram (U8 lun, U32 addr, void *ram)
Copies 1 data sector from the memory to RAM.
Ctrl_status ram_2_memory (U8 lun, U32 addr, const void *ram)
Copies 1 data sector from RAM to the memory.
MEM <-> USB Interface
Ctrl_status memory_2_usb (U8 lun, U32 addr, U16 nb_sector)
Tranfers data from the memory to USB.
Ctrl_status usb_2_memory (U8 lun, U32 addr, U16 nb_sector)
Tranfers data from USB to the memory.
Variables
Bool g_wr_protect
Write protect.
Define Documentation
#define ID_STREAM_ERR 0xFF
Erroneous streaming data transfer ID.
Definition at line 325 of file ctrl_access.h.
Referenced by nav_file_paste_start(), and nav_file_paste_state().
#define LUN_ID_0 (0)
First static LUN.
Definition at line 108 of file ctrl_access.h.
Referenced by get_cur_lun().
#define LUN_ID_1 (LUN_ID_0 + LUN_0)
Definition at line 109 of file ctrl_access.h.
#define LUN_ID_2 (LUN_ID_1 + LUN_1)
Definition at line 110 of file ctrl_access.h.
#define LUN_ID_3 (LUN_ID_2 + LUN_2)
Definition at line 111 of file ctrl_access.h.
#define LUN_ID_4 (LUN_ID_3 + LUN_3)
Definition at line 112 of file ctrl_access.h.
#define LUN_ID_5 (LUN_ID_4 + LUN_4)
Definition at line 113 of file ctrl_access.h.
#define LUN_ID_6 (LUN_ID_5 + LUN_5)
Definition at line 114 of file ctrl_access.h.
#define LUN_ID_7 (LUN_ID_6 + LUN_6)
Definition at line 115 of file ctrl_access.h.
#define LUN_ID_USB (MAX_LUN)
First dynamic LUN (USB host mass storage).
Definition at line 117 of file ctrl_access.h.
Referenced by mem_read_capacity(), mem_sector_size(), mem_test_unit_ready(), and mem_wr_protect().
#define MAX_LUN (LUN_ID_7 + LUN_7)
Number of static LUNs.
Definition at line 116 of file ctrl_access.h.
Referenced by get_nb_lun(), mem_name(), mem_read_capacity(), mem_removal(), mem_sector_size(), mem_test_unit_ready(), mem_wr_protect(), memory_2_ram(), memory_2_usb(), ram_2_memory(), and usb_2_memory().
Enumeration Type Documentation
enum Ctrl_status
Status returned by CTRL_ACCESS interfaces.
Enumerator:
CTRL_GOOD Success, memory ready.
CTRL_FAIL An error occurred.
CTRL_NO_PRESENT Memory unplugged.
CTRL_BUSY Memory not initialized or changed.
Definition at line 65 of file ctrl_access.h.
{
  CTRL_GOOD       = PASS,
  CTRL_FAIL       = FAIL,
  CTRL_NO_PRESENT = FAIL + 1,
  CTRL_BUSY       = FAIL + 2
} Ctrl_status;
Function Documentation
U8 get_cur_lun (void)
Returns the current LUN.
Returns:
Current LUN.
Todo:
Implement.
Definition at line 277 of file ctrl_access.c.
References LUN_ID_0.
{
  return LUN_ID_0;
}
U8 get_nb_lun (void)
Returns the number of LUNs.
Returns:
Number of LUNs in the system.
Definition at line 259 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, and MAX_LUN.
Referenced by nav_drive_nb(), and nav_drive_set().
{
#if MEM_USB == ENABLE
  U8 nb_lun;
  if (!Ctrl_access_lock()) return MAX_LUN;
  nb_lun = MAX_LUN + host_get_lun();
  Ctrl_access_unlock();
  return nb_lun;
#else
  return MAX_LUN;
#endif
}
const char* mem_name (U8 lun)
Returns a pointer to the LUN name.
Parameters:
lun Logical Unit Number.
Returns:
Pointer to the LUN name string.
Definition at line 393 of file ctrl_access.c.
References LUN_USB, LUN_USB_NAME, and MAX_LUN.
Referenced by main().
{
  return
#if MAX_LUN
         (lun < MAX_LUN) ? lun_desc[lun].name :
#endif
#if LUN_USB == ENABLE
                           LUN_USB_NAME;
#else
                           NULL;
#endif
}
Ctrl_status mem_read_capacity (U8 lun, U32 * u32_nb_sector)
Returns the address of the last valid sector (512 bytes) in the memory.
Parameters:
lun Logical Unit Number.
u32_nb_sector Pointer to the address of the last valid sector.
Returns:
Status.
Definition at line 305 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, CTRL_FAIL, LUN_ID_USB, Lun_usb_read_capacity, and MAX_LUN.
Referenced by fat_format(), and main().
{
  Ctrl_status status;
  if (!Ctrl_access_lock()) return CTRL_FAIL;
  status =
#if MAX_LUN
           (lun < MAX_LUN) ? lun_desc[lun].read_capacity(u32_nb_sector) :
#endif
#if LUN_USB == ENABLE
                             Lun_usb_read_capacity(lun - LUN_ID_USB, u32_nb_sector);
#else
                             CTRL_FAIL;
#endif
  Ctrl_access_unlock();
  return status;
}
Bool mem_removal (U8 lun)
Tells whether the memory is removable.
Parameters:
lun Logical Unit Number.
Returns:
TRUE if the memory is removable, else FALSE.
Definition at line 371 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, Lun_usb_removal, and MAX_LUN.
{
  Bool removal;
  if (!Ctrl_access_lock()) return TRUE;
  removal =
#if MAX_LUN
            (lun < MAX_LUN) ? lun_desc[lun].removal() :
#endif
#if LUN_USB == ENABLE
                              Lun_usb_removal();
#else
                              TRUE;
#endif
  Ctrl_access_unlock();
  return removal;
}
U8 mem_sector_size (U8 lun)
Returns the size of the physical sector.
Parameters:
lun Logical Unit Number.
Returns:
Sector size (unit: 512 bytes).
Definition at line 327 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, LUN_ID_USB, LUN_USB, Lun_usb_read_sector_size, and MAX_LUN.
Referenced by fat_mount().
{
  U8 sector_size;
  if (!Ctrl_access_lock()) return 0;
  sector_size =
#if MAX_LUN
                (lun < MAX_LUN) ? 1 :
#endif
#if LUN_USB == ENABLE
                                  Lun_usb_read_sector_size(lun - LUN_ID_USB);
#else
                                  0;
#endif
  Ctrl_access_unlock();
  return sector_size;
}
Ctrl_status mem_test_unit_ready (U8 lun)
Tests the memory state and initializes the memory if required.
The TEST UNIT READY SCSI primary command allows an application client to poll a LUN until it is ready without having to allocate memory for returned data.
This command may be used to check the media status of LUNs with removable media.
Parameters:
lun Logical Unit Number.
Returns:
Status.
Definition at line 283 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, CTRL_FAIL, LUN_ID_USB, Lun_usb_test_unit_ready, and MAX_LUN.
Referenced by fat_check_device(), and main().
{
  Ctrl_status status;
  if (!Ctrl_access_lock()) return CTRL_FAIL;
  status =
#if MAX_LUN
           (lun < MAX_LUN) ? lun_desc[lun].test_unit_ready() :
#endif
#if LUN_USB == ENABLE
                             Lun_usb_test_unit_ready(lun - LUN_ID_USB);
#else
                             CTRL_FAIL;
#endif
  Ctrl_access_unlock();
  return status;
}
Bool mem_wr_protect (U8 lun)
Returns the write-protection state of the memory.
Parameters:
lun Logical Unit Number.
Returns:
TRUE if the memory is write-protected, else FALSE.
Note:
Only used by removable memories with hardware-specific write protection.
Definition at line 349 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, LUN_ID_USB, Lun_usb_wr_protect, and MAX_LUN.
Referenced by fat_cache_flush(), file_open(), and nav_file_isreadonly().
{
  Bool wr_protect;
  if (!Ctrl_access_lock()) return TRUE;
  wr_protect =
#if MAX_LUN
               (lun < MAX_LUN) ? lun_desc[lun].wr_protect() :
#endif
#if LUN_USB == ENABLE
                                 Lun_usb_wr_protect(lun - LUN_ID_USB);
#else
                                 TRUE;
#endif
  Ctrl_access_unlock();
  return wr_protect;
}
Ctrl_status memory_2_ram (U8 lun, U32 addr, void * ram)
Copies 1 data sector from the memory to RAM.
Parameters:
lun Logical Unit Number.
addr Address of first memory sector to read.
ram Pointer to RAM buffer to write.
Returns:
Status.
Definition at line 469 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, CTRL_FAIL, Lun_usb_mem_2_ram, MAX_LUN, memory_start_read_action, and memory_stop_read_action.
Referenced by fat_cache_read_sector(), file_read_buf(), and stream_mem_to_mem().
{
  Ctrl_status status;
  if (!Ctrl_access_lock()) return CTRL_FAIL;
  memory_start_read_action(1);
  status =
#if MAX_LUN
           (lun < MAX_LUN) ? lun_desc[lun].mem_2_ram(addr, ram) :
#endif
#if LUN_USB == ENABLE
                             Lun_usb_mem_2_ram(addr, ram);
#else
                             CTRL_FAIL;
#endif
  memory_stop_read_action();
  Ctrl_access_unlock();
  return status;
}
Ctrl_status memory_2_usb (U8 lun, U32 addr, U16 nb_sector)
Tranfers data from the memory to USB.
Parameters:
lun Logical Unit Number.
addr Address of first memory sector to read.
nb_sector Number of sectors to transfer.
Returns:
Status.
Definition at line 417 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, CTRL_FAIL, MAX_LUN, memory_start_read_action, and memory_stop_read_action.
{
  Ctrl_status status;
  if (!Ctrl_access_lock()) return CTRL_FAIL;
  memory_start_read_action(nb_sector);
  status =
#if MAX_LUN
           (lun < MAX_LUN) ? lun_desc[lun].usb_read_10(addr, nb_sector) :
#endif
                             CTRL_FAIL;
  memory_stop_read_action();
  Ctrl_access_unlock();
  return status;
}
Ctrl_status ram_2_memory (U8 lun, U32 addr, const void * ram)
Copies 1 data sector from RAM to the memory.
Parameters:
lun Logical Unit Number.
addr Address of first memory sector to write.
ram Pointer to RAM buffer to read.
Returns:
Status.
Definition at line 493 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, CTRL_FAIL, Lun_usb_ram_2_mem, MAX_LUN, memory_start_write_action, and memory_stop_write_action.
Referenced by fat_cache_flush(), file_write_buf(), and stream_mem_to_mem().
{
  Ctrl_status status;
  if (!Ctrl_access_lock()) return CTRL_FAIL;
  memory_start_write_action(1);
  status =
#if MAX_LUN
           (lun < MAX_LUN) ? lun_desc[lun].ram_2_mem(addr, ram) :
#endif
#if LUN_USB == ENABLE
                             Lun_usb_ram_2_mem(addr, ram);
#else
                             CTRL_FAIL;
#endif
  memory_stop_write_action();
  Ctrl_access_unlock();
  return status;
}
Ctrl_status stream_mem_to_mem (U8 src_lun, U32 src_addr, U8 dest_lun, U32 dest_addr, U16 nb_sector)
Copies data from one memory to another.
Parameters:
src_lun Source Logical Unit Number.
src_addr Source address of first memory sector to read.
dest_lun Destination Logical Unit Number.
dest_addr Destination address of first memory sector to write.
nb_sector Number of sectors to copy.
Returns:
Status.
Definition at line 533 of file ctrl_access.c.
References CTRL_GOOD, FS_512B, memory_2_ram(), and ram_2_memory().
Referenced by nav_file_paste_state().
{
#if (defined __GNUC__) && (defined __AVR32__)
  __attribute__((__aligned__(4)))
#elif (defined __ICCAVR32__)
  #pragma data_alignment = 4
#endif
  static U8 sector_buf[FS_512B];
  Ctrl_status status = CTRL_GOOD;
  while (nb_sector--)
  {
    if ((status = memory_2_ram(src_lun, src_addr++, sector_buf)) != CTRL_GOOD) break;
    if ((status = ram_2_memory(dest_lun, dest_addr++, sector_buf)) != CTRL_GOOD) break;
  }
  return status;
}
Ctrl_status stream_state (U8 id)
Returns the state of a streaming data transfer.
Parameters:
id Transfer ID.
Returns:
Status.
Todo:
Implement.
Definition at line 555 of file ctrl_access.c.
References CTRL_GOOD.
Referenced by nav_file_paste_state().
{
  return CTRL_GOOD;
}
U16 stream_stop (U8 id)
Stops a streaming data transfer.
Parameters:
id Transfer ID.
Returns:
Number of remaining sectors.
Todo:
Implement.
Definition at line 561 of file ctrl_access.c.
Referenced by nav_file_paste_state().
{
  return 0;
}
Ctrl_status usb_2_memory (U8 lun, U32 addr, U16 nb_sector)
Tranfers data from USB to the memory.
Parameters:
lun Logical Unit Number.
addr Address of first memory sector to write.
nb_sector Number of sectors to transfer.
Returns:
Status.
Definition at line 437 of file ctrl_access.c.
References Ctrl_access_lock, Ctrl_access_unlock, CTRL_FAIL, MAX_LUN, memory_start_write_action, and memory_stop_write_action.
{
  Ctrl_status status;
  if (!Ctrl_access_lock()) return CTRL_FAIL;
  memory_start_write_action(nb_sector);
  status =
#if MAX_LUN
           (lun < MAX_LUN) ? lun_desc[lun].usb_write_10(addr, nb_sector) :
#endif
                             CTRL_FAIL;
  memory_stop_write_action();
  Ctrl_access_unlock();
  return status;
}
Variable Documentation
Bool g_wr_protect
Write protect.
Definition at line 214 of file ctrl_access.c.