AVR32 - FAT Services: nav_automatic.h File Reference
nav_automatic.h File Reference
Detailed Description
Navigation automatic Services.
Automatic navigation has been developed for the player and viewer. The plug-in provides a specific "file list". The "file list" contains all files included in a playlist or it is built with the following user specifications :
extension filter
limitation scan (folder, folder and sub folder, one disk, all disks) The plug-in can manage a random feature. Note: The play list limitations is 65535 files.
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file nav_automatic.h.
#include "fs_com.h"
#include "fat.h"
#include "navigation.h"
#include "play_list.h"
Data Structures
union Navauto_mov_bitfield_status
struct Navauto_mov_state
Structure to store the status from function navauto_mov().
Defines
Definition of the directory limitations of the file list
#define NAVAUTO_MODE_DIRONLY 2
#define NAVAUTO_MODE_DIRSUB 3
#define NAVAUTO_MODE_DISK 1
#define NAVAUTO_MODE_DISKS 0
#define NAVAUTO_MODE_NB 4
Status list of function navauto_mov()
#define NAVAUTO_MOV_DISKERROR 4
#define NAVAUTO_MOV_DISKNOPRESENT 3
#define NAVAUTO_MOV_EMPTY 2
#define NAVAUTO_MOV_OK 0
#define NAVAUTO_MOV_OK_LOOP 1
Definition of the random states
#define NAVAUTO_RAND_OFF 0
#define NAVAUTO_RAND_ON 1
Typedefs
typedef U8 Navauto_mode
Structure to store the directory limitation of the file list.
typedef U8 Navauto_rand
Structure to store the random state.
Enumerations
enum navauto_mov_options_t { NAVAUTO_MOV_OPTS_NONE = 0, NAVAUTO_MOV_OPTS_STAY_CURRENT_DIR = 1 }
Functions
U16 navauto_close (void)
This function closes the file list.
Navauto_mode navauto_getmode (void)
This function returns the directory limitation of the file list.
U16 navauto_getnb (void)
This function returns the file list size.
U16 navauto_getpos (void)
This function returns the current position in the file list.
Navauto_rand navauto_getrand (void)
This function returns the random state used.
void navauto_init (const FS_STRING sz_filterext)
This function initializes the file extension filter used to create the file list.
Navauto_mov_state navauto_mov (Bool b_direction, navauto_mov_options_t options)
This function jumps to the next or previous file in file list.
Bool navauto_open (Bool b_playlist, U16 pos)
This function opens a file list at the current position in navigator.
Bool navauto_setmode (Navauto_mode exp_mode)
This function sets the directory limitation of the file list.
Bool navauto_setpos (U16 u16_pos)
This function selects a new position in fiel list.
void navauto_setrand (Navauto_rand rand)
This function changes the random state.
Define Documentation
#define NAVAUTO_MODE_DIRONLY 2
Definition at line 65 of file nav_automatic.h.
Referenced by navauto_mov_explorer(), navauto_mov_explorer_is_file(), and navauto_mov_explorer_updir().
#define NAVAUTO_MODE_DIRSUB 3
Definition at line 66 of file nav_automatic.h.
Referenced by navauto_mov_explorer_updir().
#define NAVAUTO_MODE_DISK 1
Definition at line 64 of file nav_automatic.h.
Referenced by navauto_mov_explorer_reset().
#define NAVAUTO_MODE_DISKS 0
Definition at line 63 of file nav_automatic.h.
Referenced by navauto_mov_explorer_reset(), and navauto_mov_ok_loop().
#define NAVAUTO_MODE_NB 4
Definition at line 67 of file nav_automatic.h.
#define NAVAUTO_MOV_DISKERROR 4
Definition at line 103 of file nav_automatic.h.
Referenced by navauto_mov_playlist().
#define NAVAUTO_MOV_DISKNOPRESENT 3
Definition at line 102 of file nav_automatic.h.
#define NAVAUTO_MOV_EMPTY 2
Definition at line 101 of file nav_automatic.h.
Referenced by navauto_mov_explorer(), navauto_mov_explorer_is_file(), and navauto_mov_explorer_new_dir().
#define NAVAUTO_MOV_OK 0
Definition at line 99 of file nav_automatic.h.
Referenced by navauto_mov_explorer(), navauto_mov_explorer_is_dir(), navauto_mov_explorer_is_file(), navauto_mov_explorer_new_dir(), navauto_mov_playlist(), navauto_open(), and navauto_setpos().
#define NAVAUTO_MOV_OK_LOOP 1
Definition at line 100 of file nav_automatic.h.
Referenced by navauto_mov_explorer(), navauto_mov_explorer_is_file(), navauto_mov_ok_loop(), navauto_mov_playlist(), and navauto_open().
#define NAVAUTO_RAND_OFF 0
Definition at line 75 of file nav_automatic.h.
Referenced by navauto_open().
#define NAVAUTO_RAND_ON 1
Definition at line 76 of file nav_automatic.h.
Referenced by navauto_mov_explorer(), and navauto_mov_playlist().
Typedef Documentation
typedef U8 Navauto_mode
Structure to store the directory limitation of the file list.
Definition at line 59 of file nav_automatic.h.
typedef U8 Navauto_rand
Structure to store the random state.
Definition at line 71 of file nav_automatic.h.
Enumeration Type Documentation
enum navauto_mov_options_t
Enumerator:
NAVAUTO_MOV_OPTS_NONE
NAVAUTO_MOV_OPTS_STAY_CURRENT_DIR
Definition at line 116 of file nav_automatic.h.
{
  NAVAUTO_MOV_OPTS_NONE               = 0,
  NAVAUTO_MOV_OPTS_STAY_CURRENT_DIR   = 1
} navauto_mov_options_t;
Function Documentation
U16 navauto_close (void)
This function closes the file list.
Returns:
If a play list file is open then it is the last position in the file list else it is the directory level corresponding at the last selected file
//! At the end of this routine, the selected file of current navigator is :
//! - the play list file (in case of a play list file has been opened)
//! - the last selected file (in other case)
//!
Definition at line 516 of file nav_automatic.c.
References g_navauto_b_playlist, g_navauto_u16_dir_level, g_navauto_u16_pos, and pl_main_close().
{
   if( g_navauto_b_playlist )
   {
      pl_main_close();
      return g_navauto_u16_pos;
   }
   return g_navauto_u16_dir_level;
}
Navauto_mode navauto_getmode (void)
This function returns the directory limitation of the file list.
Returns:
Used navigation mode (NAVAUTO_MODE_DISKS, NAVAUTO_MODE_DIRONLY, NAVAUTO_MODE_DIRSUB)
//! This parameter is ignored then a play list file is selected
//!
Definition at line 167 of file nav_automatic.c.
References g_navauto_exp_mode.
{
   return g_navauto_exp_mode;
}
U16 navauto_getnb (void)
This function returns the file list size.
Definition at line 529 of file nav_automatic.c.
References g_navauto_u16_nb.
{
   return g_navauto_u16_nb;
}
U16 navauto_getpos (void)
This function returns the current position in the file list.
Definition at line 536 of file nav_automatic.c.
References g_navauto_u16_pos.
{
   return g_navauto_u16_pos;
}
Navauto_rand navauto_getrand (void)
This function returns the random state used.
Returns:
random used
Definition at line 200 of file nav_automatic.c.
References g_navauto_rand.
Referenced by navauto_open(), and navauto_setpos().
{
   return g_navauto_rand;
}
void navauto_init (const FS_STRING sz_filterext)
This function initializes the file extension filter used to create the file list.
Parameters:
sz_filterext file extension filter
//! This parameter is ignored then a play list file is selected
//!
Definition at line 298 of file nav_automatic.c.
References g_navauto_filter, g_navauto_u16_dir_level_root, and g_navauto_u16_nb.
{
   g_navauto_filter = sz_filterext;
   g_navauto_u16_dir_level_root = 0;
   g_navauto_u16_nb = 0;
}
Navauto_mov_state navauto_mov (Bool b_direction, navauto_mov_options_t options)
This function jumps to the next or previous file in file list.
Parameters:
b_direction jump direction (FS_FIND_NEXT or FS_FIND_PREV)
options jump direction (FS_FIND_NEXT or FS_FIND_PREV)
Returns:
the status of the action
//! When the random is ON, the direction is ignored
//!
Definition at line 580 of file nav_automatic.c.
References g_navauto_b_playlist, navauto_mov_explorer(), and navauto_mov_playlist().
Referenced by navauto_open(), and navauto_setpos().
{
   if( g_navauto_b_playlist )
      return navauto_mov_playlist( b_direction );
   else
      return navauto_mov_explorer( b_direction, options );
}
Bool navauto_open (Bool b_playlist, U16 pos)
This function opens a file list at the current position in navigator.
Parameters:
b_playlist if TRUE then the current selected file is a play list file to open else create a file list with files included in a disk part
pos If b_playlist TRUE, then position in the play list to start else folder level of the current position
Returns:
FALSE, in case of error or file list empty
Definition at line 315 of file nav_automatic.c.
References FS_FIND_NEXT, FS_FIND_PREV, g_navauto_b_playlist, g_navauto_filter, g_navauto_u16_dir_level, g_navauto_u16_dir_level_root, g_navauto_u16_nb, g_navauto_u16_pos, nav_dir_gotoparent(), nav_file_checkext(), nav_filelist_reset(), nav_filelist_set(), nav_filelist_validpos(), nav_getindex(), nav_gotoindex(), navauto_getrand(), navauto_mov(), navauto_mov_explorer(), navauto_mov_explorer_reset(), NAVAUTO_MOV_OK, NAVAUTO_MOV_OK_LOOP, NAVAUTO_MOV_OPTS_NONE, navauto_rand_init(), NAVAUTO_RAND_OFF, navauto_setrand(), pl_main_open(), pl_nav_getnbfile(), pl_nav_setpos(), Navauto_mov_state::status, Fs_index::u16_entry_pos_sel_file, Fs_index::u32_cluster_sel_dir, and Fs_index::u8_lun.
Referenced by navauto_setmode().
{
   Navauto_mov_state state;
   g_navauto_b_playlist     = b_playlist;
   g_navauto_u16_dir_level_root = 0;
   g_navauto_u16_nb = 0;
   if( b_playlist )
   {
      g_navauto_u16_pos        = pos;
      if( !pl_main_open(FALSE) )
         return FALSE;
      g_navauto_u16_nb = pl_nav_getnbfile();
      if( 0 == g_navauto_u16_nb )
         return FALSE;
      if( NAVAUTO_RAND_OFF == navauto_getrand() )
      {
         if( pl_nav_setpos( g_navauto_u16_pos ))
         {
            if( nav_filelist_validpos() )
               return TRUE;
         }
      }else{
         navauto_rand_init();
      }
      // Error position then restart at the beginning
      g_navauto_u16_pos = 0;
   }
   else
   {
#if(FS_NAV_AUTOMATIC_NBFILE == ENABLE)
      Fs_index       index;
      Fs_index       index2;
      Navauto_rand   rand_mode;
      U16            u16_current_pos=0;
      index.u8_lun = 0xFF;    // Reset index (by default no valid selected file)
      g_navauto_u16_dir_level  = pos;
      rand_mode = navauto_getrand();               // Save random mode
      navauto_setrand( NAVAUTO_RAND_OFF );
      // If no valid file then found the first valid file
      if( !nav_file_checkext( g_navauto_filter ))
      {
         // Go to previous position because "navauto_mov_explorer()" execute a next before search valid file
         if( !nav_filelist_set( 0 , FS_FIND_PREV ) )
           nav_filelist_reset();
         state = navauto_mov_explorer(FS_FIND_NEXT, NAVAUTO_MOV_OPTS_NONE);
         if((NAVAUTO_MOV_OK_LOOP != state.status)
         && (NAVAUTO_MOV_OK      != state.status) )
         {
           navauto_setrand(rand_mode);
           return FALSE;  // List empty
         }
      }
      index = nav_getindex();
      // Compute the size of file list and search the position of selected file
      navauto_mov_explorer_reset();                // Go to begining of loop
      // Note: the number of file is updated in navauto_mov_explorer() routine when the end of list is detected
      while( navauto_mov_explorer( FS_FIND_NEXT, NAVAUTO_MOV_OPTS_NONE ).status == NAVAUTO_MOV_OK )
      {
         index2 = nav_getindex();
         // Check the current position with the selected file
         if( (index.u8_lun == index2.u8_lun)
         &&  (index.u32_cluster_sel_dir == index2.u32_cluster_sel_dir)
         &&  (index.u16_entry_pos_sel_file == index2.u16_entry_pos_sel_file) )
         {
            u16_current_pos = g_navauto_u16_pos;   // Save the position number found
            g_navauto_u16_dir_level_root = g_navauto_u16_dir_level;
         }
      }
      navauto_setrand(rand_mode);                  // Restore random mode
      if( 0 == g_navauto_u16_nb )
         return FALSE;  // loop empty
      // Go to a file from file list
      if( NAVAUTO_RAND_OFF == navauto_getrand() )
      {
         if( 0xFF != index.u8_lun )
         {
            // Reselect the file selected at startup
            nav_gotoindex( &index );               // Go to this one
            g_navauto_u16_dir_level  = g_navauto_u16_dir_level_root;        // Update position file
            g_navauto_u16_pos = u16_current_pos;   // Update folder level corresponding at file
         }
         // Else, the first file is already selected at the end of "compute file list size" loop
         return TRUE;
      }else{
         navauto_rand_init();
      }
#else
      Fs_index       index;
      Navauto_rand   rand_mode;
      rand_mode = navauto_getrand();
      navauto_setrand(NAVAUTO_RAND_OFF);
      // If no valid file then find the first valid file
      if( !nav_file_checkext( g_navauto_filter ))
      {
         // Go to previous position because "navauto_mov_explorer()" execute a next before search valid file
         if( !nav_filelist_set( 0 , FS_FIND_PREV ) )
           nav_filelist_reset();
         state = navauto_mov_explorer(FS_FIND_NEXT, NAVAUTO_MOV_OPTS_NONE);
         if((NAVAUTO_MOV_OK_LOOP != state.status)
         && (NAVAUTO_MOV_OK      != state.status) )
         {
           navauto_setrand(rand_mode);
           return FALSE;  // List empty
         }
      }
      index = nav_getindex();
      navauto_setrand(rand_mode);
      navauto_mov_explorer_reset();
      // Compute directory level
      g_navauto_u16_dir_level = 0;
      while(nav_dir_gotoparent())
        g_navauto_u16_dir_level++;
      g_navauto_u16_dir_level_root = g_navauto_u16_dir_level;
      //g_navauto_u16_dir_level  = pos;
      // Restore index
      nav_gotoindex(&index);
      g_navauto_u16_nb = 0xFFFF;
      if( NAVAUTO_RAND_OFF == navauto_getrand() )
        navauto_rand_init();
      if( nav_file_checkext( g_navauto_filter ))
      {
        // Valid file then update position with the first position but it is not the first !
        g_navauto_u16_pos = 1;
        return TRUE;
      }
#endif
   }
   // Find first file or use the random feature
   state = navauto_mov(FS_FIND_NEXT, NAVAUTO_MOV_OPTS_NONE);
   if((NAVAUTO_MOV_OK_LOOP != state.status)
   && (NAVAUTO_MOV_OK      != state.status) )
      return FALSE;  // List empty
   return TRUE;
}
Bool navauto_setmode (Navauto_mode exp_mode)
This function sets the directory limitation of the file list.
Parameters:
exp_mode mode to select (NAVAUTO_MODE_DISKS, NAVAUTO_MODE_DIRONLY, NAVAUTO_MODE_DIRSUB)
Returns:
TRUE, mode changed
FALSE, mode can't be changed (note: the selected file must be close)
//! This parameter is ignored then a play list file is selected
//! When the mode change, the folder level is reseted at the current position.
//!
Definition at line 185 of file nav_automatic.c.
References g_navauto_b_playlist, g_navauto_exp_mode, and navauto_open().
{
   if( g_navauto_exp_mode == exp_mode )
      return TRUE;
   g_navauto_exp_mode = exp_mode;
   if( g_navauto_b_playlist )
      return TRUE;
   return navauto_open( FALSE , 0 );   // Reopen navigation to recompute the file list size
}
Bool navauto_setpos (U16 u16_pos)
This function selects a new position in fiel list.
Parameters:
u16_pos new position to select
Returns:
FALSE in case of error
Definition at line 548 of file nav_automatic.c.
References FS_FIND_NEXT, FS_FIND_PREV, g_navauto_u16_pos, navauto_getrand(), navauto_mov(), NAVAUTO_MOV_OK, NAVAUTO_MOV_OPTS_NONE, navauto_setrand(), and Navauto_mov_state::status.
{
   Bool b_direction;
   Navauto_rand rand_mode;
   Navauto_mov_state state;
   rand_mode = navauto_getrand();               // Save random mode
   state.status = NAVAUTO_MOV_OK;
   while( (u16_pos != g_navauto_u16_pos ) )
   {
     b_direction = ( u16_pos > g_navauto_u16_pos )? FS_FIND_NEXT : FS_FIND_PREV;
     state = navauto_mov( b_direction, NAVAUTO_MOV_OPTS_NONE );
   }
   navauto_setrand(rand_mode);                  // Restore random mode
   return (NAVAUTO_MOV_OK == state.status);
}
void navauto_setrand (Navauto_rand rand)
This function changes the random state.
Parameters:
rand random mode to use
Definition at line 210 of file nav_automatic.c.
References g_navauto_rand, g_navauto_rand_tab, g_navauto_u16_pos, and navauto_rand_init().
Referenced by navauto_open(), and navauto_setpos().
{
   g_navauto_rand = rand;
   navauto_rand_init();
   // If current file in rand table
   if( g_navauto_u16_pos <= (NAVAUTO_MAX_RANGE_RAND*8) )
   {
      // Set current position in rand table
      U8 u8_pos_rand = g_navauto_u16_pos-1;
      g_navauto_rand_tab[u8_pos_rand/8] |= 1<<(u8_pos_rand%8);
   }
}