AVR32 UC3 - FSACCESS Services: fsaccess.c File Reference
fsaccess.c File Reference
Detailed Description
Management of the file system access.
This file provides a set of file access functions.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices with FAT module can be used.
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file fsaccess.c.
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "fsaccess.h"
#include "compiler.h"
#include "file.h"
#include "navigation.h"
#include "ctrl_access.h"
Functions
Bool b_fsaccess_init (void)
This function initializes mutex and navigators.
int close (int fd)
This function closes a file.
long fsaccess_alloc_nav_id (void)
This function returns a free navigator id.
size_t fsaccess_file_get_size (int fd)
This function returns the opened file size.
void fsaccess_free_nav_id (int fd)
This function frees a navigator id.
void fsaccess_give_mutex (void)
This function frees the mutex.
S8 fsaccess_IsDirPresent (const char *pcStringDirName)
Is a directory present?
void fsaccess_take_mutex (void)
This function gives the mutex to the caller.
int open (const char *pathname, int flags,...)
Mutex to access the File System.
ssize_t read (int fd, void *buf, size_t count)
This function reads from a file.
ssize_t write (int fd, const void *buf, size_t count)
This function writes to a file.
Variables
static unsigned int pvNavUsed = 0
bitfield for navigator currently used. bit[0..31] is 1 if used, 0 if not.
Function Documentation
Bool b_fsaccess_init (void)
This function initializes mutex and navigators.
Definition at line 334 of file fsaccess.c.
References nav_reset().
Referenced by main().
{
  nav_reset();
#ifdef FREERTOS_USED
  if (xFs_Access == NULL)
  {
    vSemaphoreCreateBinary( xFs_Access );
    if( xFs_Access == NULL )
      return( FALSE );
    else
      return( TRUE );
  }
#endif
  return( TRUE );
}
int close (int fd)
This function closes a file.
Parameters:
fd file descriptor.
Returns:
int : -1 if error, 0 otherwise
Definition at line 274 of file fsaccess.c.
References file_close(), fsaccess_free_nav_id(), fsaccess_give_mutex(), fsaccess_take_mutex(), and nav_select().
Referenced by fsaccess_example_read(), and fsaccess_example_write().
{
  if (fd < 0)
  {
    return (-1);
  }
  // take the mutex for nav access
  fsaccess_take_mutex();
  nav_select( fd );
  file_close();
  fsaccess_free_nav_id(fd);
  // give the mutex for nav access
  fsaccess_give_mutex();
  return (0);
}
long fsaccess_alloc_nav_id (void)
This function returns a free navigator id.
Returns:
long : Id navigator allocated or -1 if none free
Definition at line 301 of file fsaccess.c.
References FS_NB_NAVIGATOR, FS_NB_RESERVED_NAV, and pvNavUsed.
Referenced by fsaccess_IsDirPresent(), and open().
{
unsigned int j;
  // get a free nav id
  // NOTE: we start at FS_NB_RESERVED_NAV, because 2 is usually used as
  // the navigator for file copy. 0 & 1 may be used independently of the fsaccess module.
  for (j = FS_NB_RESERVED_NAV ; j < FS_NB_NAVIGATOR ; j++)
  {
    if (!Tst_bits(pvNavUsed, (1 << j)))
    {
      Set_bits(pvNavUsed, (1 << j));
      return (j);
    }
  }
  // no nav free for now
  return(-1);
}
size_t fsaccess_file_get_size (int fd)
This function returns the opened file size.
Parameters:
fd file descriptor.
Returns:
size_t : size of the file pointed to by the descriptor
Definition at line 182 of file fsaccess.c.
References fsaccess_give_mutex(), fsaccess_take_mutex(), nav_file_lgt(), and nav_select().
Referenced by fsaccess_example_read(), and fsaccess_example_write().
{
size_t size;
  if (fd < 0)
  {
    return (0);
  }
  // take the mutex for nav access
  fsaccess_take_mutex();
  // select the navigator
  nav_select( fd );
  // get the file size
  size = nav_file_lgt();
  // give the mutex for nav access
  fsaccess_give_mutex();
  return (size);
}
void fsaccess_free_nav_id (int fd)
This function frees a navigator id.
Parameters:
fd file descriptor.
Definition at line 325 of file fsaccess.c.
References pvNavUsed.
Referenced by close(), fsaccess_IsDirPresent(), and open().
{
  // mark NavId as free
  Clr_bits(pvNavUsed, (1 << fd));
}
void fsaccess_give_mutex (void)
This function frees the mutex.
Definition at line 365 of file fsaccess.c.
Referenced by close(), fsaccess_file_get_size(), fsaccess_IsDirPresent(), open(), read(), and write().
{
#ifdef FREERTOS_USED
  // Release the mutex.
  xSemaphoreGive( xFs_Access );
#endif
}
S8 fsaccess_IsDirPresent (const char * pcStringDirName)
Is a directory present?
Parameters:
pcStringDirName Input. Directory name string.
Returns:
1 if the directory exists, 0 if the directory doesn't exist, else -1
Definition at line 381 of file fsaccess.c.
References fsaccess_alloc_nav_id(), fsaccess_free_nav_id(), fsaccess_give_mutex(), fsaccess_take_mutex(), nav_select(), and nav_setcwd().
{
   signed short TempoNavId;
   S8           RetVal;
   fsaccess_take_mutex(); // Take the mutex on the file system access.
   TempoNavId = fsaccess_alloc_nav_id(); // Get a navigator.
   if( -1 == TempoNavId ) // No navigator.
   {
      // give the mutex for nav access
      fsaccess_give_mutex();
      return( -1 );
   }
   // select the navigator
   nav_select( TempoNavId );
   // Try to enter in the directory.
   RetVal = (S8)nav_setcwd( (FS_STRING)pcStringDirName, TRUE, FALSE );
   fsaccess_free_nav_id( TempoNavId ); // mark NavId as free
   fsaccess_give_mutex(); // give the mutex for nav access
   return( RetVal );
}
void fsaccess_take_mutex (void)
This function gives the mutex to the caller.
Definition at line 354 of file fsaccess.c.
Referenced by close(), fsaccess_file_get_size(), fsaccess_IsDirPresent(), open(), read(), and write().
{
#ifdef FREERTOS_USED
  // wait for semaphore
  while( xSemaphoreTake( xFs_Access, portMAX_DELAY ) != pdTRUE );
#endif
}
int open (const char * pathname, int flags, ...)
Mutex to access the File System.
This function opens a file.
This function opens a file.
Parameters:
pathname path of the file to open.
flags flags to give file access rights should be O_CREAT : create file if not exist O_APPEND : add data to the end of file O_RDONLY : Read Only O_WRONLY : Write Only O_RDWR : Read/Write
Returns:
int : file descriptor (>= 0 if OK (NavID), -1 otherwise)
Definition at line 107 of file fsaccess.c.
References file_open(), FOPEN_MODE_APPEND, FOPEN_MODE_R, FOPEN_MODE_R_PLUS, FOPEN_MODE_W, fsaccess_alloc_nav_id(), fsaccess_free_nav_id(), fsaccess_give_mutex(), fsaccess_take_mutex(), nav_select(), nav_setcwd(), O_APPEND, O_CREAT, O_RDWR, and O_WRONLY.
Referenced by fsaccess_example_read(), and fsaccess_example_write().
{
int CurrentNavId = -1;
  // take the mutex for nav access
  fsaccess_take_mutex();
  // if no navigator available, return an error
  if ((CurrentNavId = fsaccess_alloc_nav_id()) < 0) goto error_exit;
  // select the navigator
  nav_select( CurrentNavId );
  // the filesystem is now at the root directory
  if ((flags & O_CREAT) == O_CREAT)
  {
    // try to create, the flag is set
    if(nav_setcwd((FS_STRING)pathname, FALSE, TRUE) == FALSE)
    {
       goto error_free_nav;
    }
  }
  else
  {
    // do not try to create, if it doesn't exist, error
    if(nav_setcwd((FS_STRING)pathname, FALSE, FALSE) == FALSE)
    {
       goto error_free_nav;
    }
  }
  // if user wants to append in file
  if ((flags & O_APPEND) == O_APPEND)
  {
    // open the file
    if (file_open(FOPEN_MODE_APPEND) == FALSE) goto error_free_nav;
  }
  else if ((flags & O_RDWR) == O_RDWR)
  {
    // open as read/write
    if (file_open(FOPEN_MODE_R_PLUS) == FALSE) goto error_free_nav;
  }
  else if ((flags & O_WRONLY) == O_WRONLY)
  {
    // open as write
    if (file_open(FOPEN_MODE_W) == FALSE) goto error_free_nav;
  }
  else
  {
    // open as read
    if (file_open(FOPEN_MODE_R) == FALSE) goto error_free_nav;
  }
  // give the mutex for nav access
  fsaccess_give_mutex();
  return (CurrentNavId);
error_free_nav:
  // mark NavId as free
  fsaccess_free_nav_id(CurrentNavId);
error_exit:
  // give the mutex for nav access
  fsaccess_give_mutex();
  return(-1);
}
ssize_t read (int fd, void * buf, size_t count)
This function reads from a file.
Parameters:
fd file descriptor.
buf pointer for data that are read.
count amount of bytes to read
Returns:
ssize_t : amount of data read (-1 if error)
Definition at line 210 of file fsaccess.c.
References file_eof(), file_read_buf(), fsaccess_give_mutex(), fsaccess_take_mutex(), and nav_select().
Referenced by fsaccess_example_read(), and fsaccess_example_write().
{
ssize_t ReadCount = -1;
  if (fd < 0)
  {
    return (-1);
  }
  // take the mutex for nav access
  fsaccess_take_mutex();
  nav_select( fd );
  if ( file_eof() )
  {
     // give the mutex for nav access
     fsaccess_give_mutex();
     return(-1);
  }
  ReadCount = (ssize_t)file_read_buf((U8 *)buf , (U16)count);
  // give the mutex for nav access
  fsaccess_give_mutex();
  return(ReadCount);
}
ssize_t write (int fd, const void * buf, size_t count)
This function writes to a file.
Parameters:
fd file descriptor.
buf pointer from where data are written.
count amount of bytes to write
Returns:
ssize_t : amount of data written (-1 if error)
Definition at line 247 of file fsaccess.c.
References file_write_buf(), fsaccess_give_mutex(), fsaccess_take_mutex(), and nav_select().
Referenced by fsaccess_example_write().
{
ssize_t WriteCount = -1;
  if (fd < 0)
  {
    return (-1);
  }
  // take the mutex for nav access
  fsaccess_take_mutex();
  nav_select( fd );
  WriteCount = (ssize_t)file_write_buf((U8 *)buf , (U16)count);
  // give the mutex for nav access
  fsaccess_give_mutex();
  return(WriteCount);
}
Variable Documentation
unsigned int pvNavUsed = 0 [static]
bitfield for navigator currently used. bit[0..31] is 1 if used, 0 if not.
Definition at line 87 of file fsaccess.c.
Referenced by fsaccess_alloc_nav_id(), and fsaccess_free_nav_id().