AVR32 UC3 - FSACCESS Services: fat.h File Reference
fat.h File Reference
Detailed Description
FAT services.
This file is the header for FAT services
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file fat.h.
#include "fs_com.h"
Data Structures
struct Fs_clusterlist_cache
Struture to store the cluster list cache.
struct Fs_management
Struture to save the variables frequently used by file system mounted.
struct Fs_management_entry
Struture to save the frequently variables of file system mounted.
struct Fs_management_fast
Struture to save the variables very frequently used by file system mounted.
union Fs_rootdir
Union to define a root directory.
struct Fs_sector_cache
Struture to store the information about sector cache (=last sector read or write on disk).
struct Fs_segment
Struture to define a segment.
struct st_fs_cluster
Struture to store cluster information.
Variables used to manage the sector cache
typedef U8 _MEM_TYPE_SLOW_ * PTR_CACHE
_GLOBEXT_ _MEM_TYPE_SLOW_ U8 fs_g_sector [FS_CACHE_SIZE]
Use "FAT sector cache" to store a sector from a file (see file_putc(), file_getc(), file_read_buf(), file_write_buf()).
_GLOBEXT_ _MEM_TYPE_SLOW_
Fs_sector_cache fs_g_sectorcache
_GLOBEXT_ _MEM_TYPE_SLOW_ U32 fs_gu32_addrsector
Store the address of futur cache (unit 512B).
Defines
#define _GLOBEXT_ extern
#define FS_BUF_SECTOR_EMPTY 0xFF
Signal that sector cache is not valid.
#define FS_MBR_OFFSET_PART_ENTRY(num) ((U16)((U16)(0x1BE)+(0x10 * num)))
Position (unit byte) in the MBR of a partition entry.
#define Is_fat12 (FS_TYPE_FAT_12 == fs_g_nav_fast.u8_type_fat)
#define Is_fat16 (FS_TYPE_FAT_16 == fs_g_nav_fast.u8_type_fat)
#define Is_fat32 (FS_TYPE_FAT_32 == fs_g_nav_fast.u8_type_fat)
#define Is_unicode (g_b_unicode)
Macro to check the file open mode
#define Fat_file_close() (fs_g_nav_entry.u8_open_mode =0)
#define Fat_file_is_open() (fs_g_nav_entry.u8_open_mode !=0)
#define Fat_file_isnot_open() (fs_g_nav_entry.u8_open_mode ==0)
The unit sector of 512B is many used in file System stack
#define FS_512B 512
#define FS_512B_MASK (512-1)
#define FS_512B_SHIFT_BIT 9
#define FS_CACHE_SIZE 512
#define FS_MASK_SIZE_OF_SECTOR FS_512B_MASK
#define FS_SHIFT_B_TO_SECTOR FS_512B_SHIFT_BIT
#define FS_SIZE_OF_SECTOR FS_512B
Constants used in MBR sector
#define FS_BOOT_SIGN 0x29
#define FS_PART_BOOTABLE 0x80
#define FS_PART_HARD_DISK 0x81
#define FS_PART_NO_BOOTABLE 0x00
#define FS_PART_NO_REMOVE_MEDIA 0xF8
#define FS_PART_REMOVE_MEDIA 0xF0
#define FS_PART_TYPE_FAT12 0x01
#define FS_PART_TYPE_FAT16_INF32M 0x04
#define FS_PART_TYPE_FAT16_SUP32M 0x06
#define FS_PART_TYPE_FAT16_SUP32M_BIS 0x0E
#define FS_PART_TYPE_FAT32 0x0B
#define FS_PART_TYPE_FAT32_BIS 0x0C
Constante used to sign a MBR or PBR sectors
#define FS_BR_SIGNATURE_HIGH 0xAA
#define FS_BR_SIGNATURE_LOW 0x55
Status of the fat_checkcluster() function
#define FS_CLUS_BAD 1
#define FS_CLUS_END 2
#define FS_CLUS_OK 0
Options of the fat_cluster_list() function
#define FS_CLUST_ACT_CLR 0x03
#define FS_CLUST_ACT_ONE 0x02
#define FS_CLUST_ACT_SEG 0x01
Options of the fat_cluster_val() function
#define FS_CLUST_VAL_EOL 0x0FFFFFFF
#define FS_CLUST_VAL_READ FALSE
#define FS_CLUST_VAL_WRITE TRUE
Value used in "Fs_management_fast.u16_entry_pos_sel_file"
#define FS_END_FIND 0xFFFE
Signal that a file entry is the last file entry accessibled by system.
#define FS_NO_SEL 0xFFFF
Signal that a file entry isn't selected.
Constants used in the first byte of file entry
#define FS_ENTRY_DEL 0xE5
#define FS_ENTRY_END 0x00
#define FS_ENTRY_LFN_LAST 0x40
Maximum of FAT cluster
#define FS_FAT12_MAX_CLUSTERS 4085
#define FS_FAT16_MAX_CLUSTERS 65525
LIMITATIONS OF FILE SYSTEM
#define FS_NB_FAT 2
Constantes used to manage the file entry
#define FS_SHIFT_B_TO_FILE_ENTRY 5
#define FS_SIZE_FILE_ENTRY 32
#define FS_SIZE_LFN_ENTRY 13
#define FS_SIZE_SFNAME 11
#define FS_SIZE_SFNAME_EXT_ONLY 3
#define FS_SIZE_SFNAME_WITHOUT_EXT 8
FAT type ID, used in "Fs_management_fast.u8_type_fat"
#define FS_TYPE_FAT_12 1
#define FS_TYPE_FAT_16 2
#define FS_TYPE_FAT_32 3
#define FS_TYPE_FAT_UNM 0
Partition not mounted.
Macro to access at fields in BPB sector (only used in fat_mount() function)
The name prefixed by "BPB_" are defined in "Hardware White Paper FAT"
#define HIGH_16_BPB_BytsPerSec fs_g_sector[12]
#define HIGH_16_BPB_FATSz16 fs_g_sector[23]
#define HIGH_16_BPB_FSInfo fs_g_sector[49]
#define HIGH_16_BPB_ResvSecCnt fs_g_sector[15]
#define HIGH_16_BPB_RootEntCnt fs_g_sector[18]
#define HIGH_16_BPB_TotSec16 fs_g_sector[20]
#define LOW0_32_BPB_FATSz32 fs_g_sector[36]
#define LOW0_32_BPB_RootClus fs_g_sector[44]
#define LOW0_32_BPB_TotSec32 fs_g_sector[32]
#define LOW1_32_BPB_FATSz32 fs_g_sector[37]
#define LOW1_32_BPB_RootClus fs_g_sector[45]
#define LOW1_32_BPB_TotSec32 fs_g_sector[33]
#define LOW2_32_BPB_FATSz32 fs_g_sector[38]
#define LOW2_32_BPB_RootClus fs_g_sector[46]
#define LOW2_32_BPB_TotSec32 fs_g_sector[34]
#define LOW3_32_BPB_FATSz32 fs_g_sector[39]
#define LOW3_32_BPB_RootClus fs_g_sector[47]
#define LOW3_32_BPB_TotSec32 fs_g_sector[35]
#define LOW_16_BPB_BytsPerSec fs_g_sector[11]
#define LOW_16_BPB_FATSz16 fs_g_sector[22]
#define LOW_16_BPB_FSInfo fs_g_sector[48]
#define LOW_16_BPB_ResvSecCnt fs_g_sector[14]
#define LOW_16_BPB_RootEntCnt fs_g_sector[17]
#define LOW_16_BPB_TotSec16 fs_g_sector[19]
#define U8_BPB_NumFATs fs_g_sector[16]
#define U8_BPB_SecPerClus fs_g_sector[13]
Typedefs
Main sructures
typedef struct st_fs_cluster Fs_cluster
Functions
Bool fat_format (U8 u8_fat_type)
This function formats the drive.
U8 fat_get_nbpartition (void)
This function returns the number of partition present on selected drive.
Bool fat_mount (void)
This function mounts a partition.
Bool fat_serialnumber (Bool b_action, U8 _MEM_TYPE_SLOW_ *a_u8_sn)
This function reads or writes a serial number.
Functions to manage the cluster list
Bool fat_allocfreespace (void)
This function allocs a cluster list.
void fat_cache_clusterlist_reset (void)
This function resets the cluster list caches.
U8 fat_checkcluster (void)
This function checks the cluster value.
Bool fat_clear_cluster (void)
This function clears one cluster.
void fat_clear_info_fat_mod (void)
This function clears the cache information about FAT modifications.
Bool fat_cluster_list (U8 opt_action, Bool b_for_file)
This function gets or clears a cluster list.
Bool fat_cluster_readnext (void)
This function is optimized to read a continue cluster list on FAT16 and FAT32.
Bool fat_cluster_val (Bool b_mode)
This function returns or modifys a cluster value in FAT.
Bool fat_update_fat2 (void)
This function copys the modifications of the first FAT to the second FAT.
Functions to manage the cache
void fat_cache_clear (void)
This function clears the sector cache.
Bool fat_cache_flush (void)
This function flushs the sector cache on the memory if necessary.
void fat_cache_mark_sector_as_dirty (void)
This function sets a flag to signal that sector cache is modified.
Bool fat_cache_read_sector (Bool b_load)
This function loads a memory sector in internal cache sector.
void fat_cache_reset (void)
This function resets the sector cache.
Functions to verify navigator state
}@
Bool fat_check_device (void)
This function checks device state.
Bool fat_check_is_file (void)
This function checks if the selected file entry is a file and not a directory.
Bool fat_check_mount (void)
This function checks if the partition is mounted.
Bool fat_check_mount_noopen (void)
This function checks if the partition is mounted and no file is opened.
Bool fat_check_mount_select (void)
This function checks if the partition is mounted and if a file is selected.
Bool fat_check_mount_select_noopen (void)
This function checks if the partition is mounted and if no file is opened and a file is selected.
Bool fat_check_mount_select_open (void)
This function checks if the partition is mounted and if a file is opened.
Bool fat_check_noopen (void)
This function checks if a file is not opened on current navigator.
Bool fat_check_open (void)
This function checks if a file is opened on current navigator.
Bool fat_check_select (void)
This function checks if a file is selected on current navigator.
Functions to manage the entry field (fat.c)
Bool fat_check_eof_name (U16 character)
Check end of name.
void fat_clear_entry_info_and_ptr (void)
This function resets the selection pointers.
Bool fat_entry_check (Bool b_type)
This function checks the entry.
Bool fat_entry_checkext (FS_STRING sz_filter)
This function checks the file extension.
Bool fat_entry_is_dir (void)
This function checks if the entry file is a directory.
Bool fat_entry_longname (FS_STRING sz_name, U8 u8_size_max, Bool b_mode, Bool b_match_case)
This function returns or compares the long name entry.
Bool fat_entry_shortname (FS_STRING sz_name, U8 u8_size_max, Bool b_mode)
This function returns or compares the short name entry.
void fat_get_entry_info (void)
This function reads information about selected file.
PTR_CACHE fat_get_ptr_entry (void)
This function returns a cache pointer on the current entry.
void fat_write_entry_file (void)
This function writes the information about selected file.
Functions to control access disk
Bool fat_check_nav_access_disk (void)
This function checks write access.
Bool fat_check_nav_access_file (Bool mode)
This function checks all access at current file.
Functions to manage navigator switch
void fat_copy_nav (U8 u8_idnav)
This function copys the main navigator to another navigator.
void fat_invert_nav (U8 u8_idnav)
This function inverts the current navigation with another.
Functions to manage the entry field (fat_unusual.c)
Bool fat_create_entry_file_name (FS_STRING sz_name)
This function creates the short and the long name of a new entry.
Bool fat_delete_file (Bool b_cluster_list)
This function deletes the file entries and cluster list.
Bool fat_entry_label (Bool b_action, FS_STRING sz_label)
This function reads or writes a label in the partition.
void fat_get_date (FS_STRING sz_date, Bool type_date)
This function reads the information about a date.
void fat_set_date (const FS_STRING sz_date, Bool type_date)
This function changes the date information.
Functions to compute free space on a partition
U32 fat_getfreespace (void)
This function returns the space free in the partition.
U8 fat_getfreespace_percent (void)
This function returns the space free in percent.
U32 fat_read_fat32_FSInfo (void)
This function returns the space free in the selected FAT32 partition.
Bool fat_write_fat32_FSInfo (U32 u32_nb_free_cluster)
This function writes the space free number in selected FAT32 partition.
Functions to read or to write a file or a directory
Bool fat_initialize_dir (void)
This function writes the directory information.
Bool fat_read_dir (void)
This function fill the internal cache with a sector from current directory.
Bool fat_read_file (U8 mode)
This function gets or clears a cluster list at the current position in the selected file.
Bool fat_write_file (U8 mode, U32 u32_nb_sector_write)
This function gets and eventually allocs a cluster list at the current position in the selected file.
Variables
_GLOBEXT_ _MEM_TYPE_FAST_
Fs_cluster fs_g_cluster
To take time in functions: fat_getfreespace, fat_cluster_list, fat_cluster_val, fat_checkcluster.
_GLOBEXT_ _MEM_TYPE_FAST_
Fs_segment fs_g_seg
Variable frequently used by many function (optimization, no parameter in function).
_GLOBEXT_ Bool g_b_no_check_disk
Variables to enable/disable the disk check before each action on disk.
_GLOBEXT_ Bool g_b_string_length
Variables to select LENGTH string mode (initialised in nav_reset()).
_GLOBEXT_ Bool g_b_unicode
Variables to select string format (initialised in nav_reset()).
Variables initialised in drive_mount()
_GLOBEXT_ _MEM_TYPE_SLOW_
Fs_management fs_g_nav
_GLOBEXT_ _MEM_TYPE_SLOW_
Fs_management_entry fs_g_nav_entry
_GLOBEXT_ _MEM_TYPE_FAST_
Fs_management_fast fs_g_nav_fast
Variables used to update the second FAT zone
_GLOBEXT_ _MEM_TYPE_SLOW_ U16 fs_g_u16_first_mod_fat
Offset (unit 512B) in fat of the first sector (unit 512B).
_GLOBEXT_ _MEM_TYPE_SLOW_ U16 fs_g_u16_last_mod_fat
Offset (unit 512B) in fat of the last sector (unit 512B).
Define Documentation
#define _GLOBEXT_ extern
    - File system vocabulary :
    MBR : Master Boot Record (constains four PE)
    PE  : Partition Entry (constains a location informations about PBR)
    PBR : Partition Boot Record
    BPB : BIOS Parameter Block (see Hardware White Paper FAT)
    PBR = BPB
    FAT : File Allocation Table
Definition at line 64 of file fat.h.
#define Fat_file_close () (fs_g_nav_entry.u8_open_mode =0)
Definition at line 376 of file fat.h.
Referenced by fat_check_device(), fat_clear_entry_info_and_ptr(), file_close(), and nav_reset().
#define Fat_file_is_open () (fs_g_nav_entry.u8_open_mode !=0)
Definition at line 374 of file fat.h.
Referenced by fat_check_noopen().
#define Fat_file_isnot_open () (fs_g_nav_entry.u8_open_mode ==0)
Definition at line 375 of file fat.h.
Referenced by fat_check_open().
#define FS_512B 512
Definition at line 216 of file fat.h.
Referenced by fat_mount(), fat_select_filesystem(), fat_write_MBR(), file_read(), file_read_buf(), file_write(), file_write_buf(), nav_file_paste_state(), and stream_mem_to_mem().
#define FS_512B_MASK (512-1)
Definition at line 217 of file fat.h.
Referenced by fat_get_ptr_entry(), fat_read_file(), file_getc(), file_putc(), and file_read().
#define FS_512B_SHIFT_BIT 9
Definition at line 218 of file fat.h.
Referenced by fat_read_dir(), fat_read_file(), file_read(), and nav_file_lgtsector().
#define FS_BOOT_SIGN 0x29
Definition at line 176 of file fat.h.
#define FS_BR_SIGNATURE_HIGH 0xAA
Definition at line 146 of file fat.h.
Referenced by fat_get_nbpartition(), fat_mount(), fat_read_fat32_FSInfo(), fat_write_fat32_FSInfo(), fat_write_MBR(), and fat_write_PBR().
#define FS_BR_SIGNATURE_LOW 0x55
Definition at line 145 of file fat.h.
Referenced by fat_get_nbpartition(), fat_mount(), fat_read_fat32_FSInfo(), fat_write_fat32_FSInfo(), fat_write_MBR(), and fat_write_PBR().
#define FS_BUF_SECTOR_EMPTY 0xFF
Signal that sector cache is not valid.
Definition at line 226 of file fat.h.
Referenced by fat_cache_reset().
#define FS_CACHE_SIZE 512
Definition at line 222 of file fat.h.
Referenced by fat_cache_clear(), fat_clean_zone(), fat_cluster_readnext(), and fat_cluster_val().
#define FS_CLUS_BAD 1
Definition at line 232 of file fat.h.
Referenced by fat_checkcluster(), and fat_cluster_list().
#define FS_CLUS_END 2
Definition at line 233 of file fat.h.
Referenced by fat_checkcluster(), and fat_cluster_list().
#define FS_CLUS_OK 0
Definition at line 231 of file fat.h.
Referenced by fat_checkcluster().
#define FS_CLUST_ACT_CLR 0x03
Definition at line 241 of file fat.h.
Referenced by fat_cluster_list(), fat_delete_file(), fat_read_file(), and file_set_eof().
#define FS_CLUST_ACT_ONE 0x02
Definition at line 240 of file fat.h.
Referenced by fat_clear_cluster(), fat_cluster_list(), fat_read_dir(), fat_read_file(), file_getc(), file_putc(), file_read_buf(), and file_write_buf().
#define FS_CLUST_ACT_SEG 0x01
Definition at line 239 of file fat.h.
Referenced by fat_cluster_list(), fat_read_file(), fat_write_file(), file_read(), file_read_buf(), file_write(), and file_write_buf().
#define FS_CLUST_VAL_EOL 0x0FFFFFFF
Definition at line 248 of file fat.h.
Referenced by fat_allocfreespace(), and fat_cluster_list().
#define FS_CLUST_VAL_READ FALSE
Definition at line 246 of file fat.h.
Referenced by fat_allocfreespace(), fat_cluster_list(), fat_getfreespace(), and fat_getfreespace_percent().
#define FS_CLUST_VAL_WRITE TRUE
Definition at line 247 of file fat.h.
Referenced by fat_allocfreespace(), and fat_cluster_list().
#define FS_END_FIND 0xFFFE
Signal that a file entry is the last file entry accessibled by system.
Definition at line 368 of file fat.h.
Referenced by nav_filelist_set().
#define FS_ENTRY_DEL 0xE5
Definition at line 190 of file fat.h.
Referenced by fat_delete_file(), fat_entry_check(), fat_entry_longname(), fat_entry_shortname_compare(), and fat_garbage_collector_entry().
#define FS_ENTRY_END 0x00
Definition at line 189 of file fat.h.
Referenced by fat_alloc_entry_free(), fat_entry_check(), fat_entry_label(), fat_entry_longname(), fat_entry_shortname_compare(), and fat_garbage_collector_entry().
#define FS_ENTRY_LFN_LAST 0x40
Definition at line 191 of file fat.h.
Referenced by fat_create_entry_file_name(), fat_delete_file(), and fat_entry_longname().
#define FS_FAT12_MAX_CLUSTERS 4085
Definition at line 182 of file fat.h.
Referenced by fat_mount().
#define FS_FAT16_MAX_CLUSTERS 65525
Definition at line 183 of file fat.h.
Referenced by fat_mount().
#define FS_MASK_SIZE_OF_SECTOR FS_512B_MASK
Definition at line 220 of file fat.h.
#define FS_MBR_OFFSET_PART_ENTRY (num) ((U16)((U16)(0x1BE)+(0x10 * num)))
Position (unit byte) in the MBR of a partition entry.
Definition at line 108 of file fat.h.
Referenced by fat_get_nbpartition(), fat_mount(), and fat_write_MBR().
#define FS_NB_FAT 2
Definition at line 208 of file fat.h.
Referenced by fat_mount().
#define FS_NO_SEL 0xFFFF
Signal that a file entry isn't selected.
Definition at line 367 of file fat.h.
Referenced by fat_check_select(), fat_clear_entry_info_and_ptr(), nav_filelist_eol(), nav_filelist_exist(), nav_filelist_goto(), nav_filelist_nb(), nav_filelist_set(), nav_filterflat_goto(), nav_filterlist_cd(), nav_filterlist_goto(), nav_filterlist_mount(), nav_filterlist_nb_ex(), nav_filterlist_next(), nav_filterlist_reset(), and nav_filterlist_root().
#define FS_PART_BOOTABLE 0x80
Definition at line 152 of file fat.h.
Referenced by fat_mount().
#define FS_PART_HARD_DISK 0x81
Definition at line 175 of file fat.h.
#define FS_PART_NO_BOOTABLE 0x00
Definition at line 153 of file fat.h.
Referenced by fat_mount(), and fat_write_MBR().
#define FS_PART_NO_REMOVE_MEDIA 0xF8
Definition at line 174 of file fat.h.
#define FS_PART_REMOVE_MEDIA 0xF0
Definition at line 173 of file fat.h.
#define FS_PART_TYPE_FAT12 0x01
Definition at line 167 of file fat.h.
Referenced by fat_mount(), and fat_write_MBR().
#define FS_PART_TYPE_FAT16_INF32M 0x04
Definition at line 168 of file fat.h.
Referenced by fat_mount(), and fat_write_MBR().
#define FS_PART_TYPE_FAT16_SUP32M 0x06
Definition at line 169 of file fat.h.
Referenced by fat_mount(), and fat_write_MBR().
#define FS_PART_TYPE_FAT16_SUP32M_BIS 0x0E
Definition at line 170 of file fat.h.
Referenced by fat_mount().
#define FS_PART_TYPE_FAT32 0x0B
Definition at line 171 of file fat.h.
Referenced by fat_mount(), and fat_write_MBR().
#define FS_PART_TYPE_FAT32_BIS 0x0C
Definition at line 172 of file fat.h.
Referenced by fat_mount().
#define FS_SHIFT_B_TO_FILE_ENTRY 5
Definition at line 198 of file fat.h.
Referenced by fat_read_dir().
#define FS_SHIFT_B_TO_SECTOR FS_512B_SHIFT_BIT
Definition at line 221 of file fat.h.
#define FS_SIZE_FILE_ENTRY 32
Definition at line 197 of file fat.h.
Referenced by fat_create_long_name_entry(), fat_entry_longname(), fat_garbage_collector_entry(), fat_get_ptr_entry(), fat_initialize_dir(), and fat_mount().
#define FS_SIZE_LFN_ENTRY 13
Definition at line 199 of file fat.h.
Referenced by fat_check_name(), fat_create_entry_file_name(), and nav_file_name().
#define FS_SIZE_OF_SECTOR FS_512B
Definition at line 219 of file fat.h.
Referenced by fsaccess_example_read(), and fsaccess_example_write().
#define FS_SIZE_SFNAME 11
Definition at line 200 of file fat.h.
Referenced by fat_create_short_entry_name(), and fat_entry_shortname().
#define FS_SIZE_SFNAME_EXT_ONLY 3
Definition at line 202 of file fat.h.
#define FS_SIZE_SFNAME_WITHOUT_EXT 8
Definition at line 201 of file fat.h.
Referenced by fat_create_short_entry_name(), and fat_entry_shortname().
#define FS_TYPE_FAT_12 1
Definition at line 359 of file fat.h.
Referenced by fat_mount(), and fat_select_filesystem().
#define FS_TYPE_FAT_16 2
Definition at line 360 of file fat.h.
Referenced by fat_mount(), and fat_select_filesystem().
#define FS_TYPE_FAT_32 3
Definition at line 361 of file fat.h.
Referenced by fat_allocfreespace(), fat_mount(), and fat_select_filesystem().
#define FS_TYPE_FAT_UNM 0
Partition not mounted.
Definition at line 358 of file fat.h.
Referenced by fat_check_device(), fat_check_mount(), fat_check_nav_access_disk(), fat_check_nav_access_file(), fat_check_noopen(), fat_mount(), nav_drive_set(), nav_partition_freespace(), nav_partition_freespace_percent(), nav_partition_mount(), nav_partition_set(), nav_partition_space(), nav_partition_type(), and nav_reset().
#define HIGH_16_BPB_BytsPerSec fs_g_sector[12]
Definition at line 115 of file fat.h.
Referenced by fat_mount().
#define HIGH_16_BPB_FATSz16 fs_g_sector[23]
Definition at line 120 of file fat.h.
Referenced by fat_mount(), and fat_write_PBR().
#define HIGH_16_BPB_FSInfo fs_g_sector[49]
Definition at line 139 of file fat.h.
#define HIGH_16_BPB_ResvSecCnt fs_g_sector[15]
Definition at line 132 of file fat.h.
Referenced by fat_mount().
#define HIGH_16_BPB_RootEntCnt fs_g_sector[18]
Definition at line 118 of file fat.h.
Referenced by fat_mount().
#define HIGH_16_BPB_TotSec16 fs_g_sector[20]
Definition at line 126 of file fat.h.
Referenced by fat_mount().
#define Is_fat12 (FS_TYPE_FAT_12 == fs_g_nav_fast.u8_type_fat)
Definition at line 75 of file fat.h.
Referenced by fat_checkcluster(), fat_cluster_list(), fat_cluster_val(), fat_getfreespace(), fat_getfreespace_percent(), fat_initialize_fat(), fat_select_filesystem(), fat_serialnumber(), fat_write_MBR(), and fat_write_PBR().
#define Is_fat16 (FS_TYPE_FAT_16 == fs_g_nav_fast.u8_type_fat)
Definition at line 80 of file fat.h.
Referenced by fat_checkcluster(), fat_cluster_list(), fat_cluster_val(), fat_getfreespace_percent(), fat_initialize_fat(), fat_select_filesystem(), fat_serialnumber(), and fat_write_MBR().
#define Is_fat32 (FS_TYPE_FAT_32 == fs_g_nav_fast.u8_type_fat)
Definition at line 85 of file fat.h.
Referenced by fat_allocfreespace(), fat_checkcluster(), fat_clean_zone(), fat_cluster_list(), fat_cluster_readnext(), fat_cluster_val(), fat_getfreespace(), fat_getfreespace_percent(), fat_initialize_fat(), fat_select_filesystem(), fat_write_MBR(), and fat_write_PBR().
#define Is_unicode (g_b_unicode)
Definition at line 92 of file fat.h.
Referenced by fat_check_name(), fat_create_entry_file_name(), fat_create_long_name_entry(), fat_create_short_entry_name(), fat_entry_longname(), fat_entry_shortname(), nav_dir_name(), nav_file_name(), nav_getcwd(), nav_setcwd(), pl_main_close(), and pl_main_readline().
#define LOW0_32_BPB_FATSz32 fs_g_sector[36]
Definition at line 121 of file fat.h.
Referenced by fat_mount(), and fat_write_PBR().
#define LOW0_32_BPB_RootClus fs_g_sector[44]
Definition at line 134 of file fat.h.
Referenced by fat_mount().
#define LOW0_32_BPB_TotSec32 fs_g_sector[32]
Definition at line 127 of file fat.h.
Referenced by fat_mount().
#define LOW1_32_BPB_FATSz32 fs_g_sector[37]
Definition at line 122 of file fat.h.
Referenced by fat_mount(), and fat_write_PBR().
#define LOW1_32_BPB_RootClus fs_g_sector[45]
Definition at line 135 of file fat.h.
Referenced by fat_mount().
#define LOW1_32_BPB_TotSec32 fs_g_sector[33]
Definition at line 128 of file fat.h.
Referenced by fat_mount().
#define LOW2_32_BPB_FATSz32 fs_g_sector[38]
Definition at line 123 of file fat.h.
Referenced by fat_mount().
#define LOW2_32_BPB_RootClus fs_g_sector[46]
Definition at line 136 of file fat.h.
Referenced by fat_mount().
#define LOW2_32_BPB_TotSec32 fs_g_sector[34]
Definition at line 129 of file fat.h.
Referenced by fat_mount().
#define LOW3_32_BPB_FATSz32 fs_g_sector[39]
Definition at line 124 of file fat.h.
Referenced by fat_mount().
#define LOW3_32_BPB_RootClus fs_g_sector[47]
Definition at line 137 of file fat.h.
Referenced by fat_mount().
#define LOW3_32_BPB_TotSec32 fs_g_sector[35]
Definition at line 130 of file fat.h.
Referenced by fat_mount().
#define LOW_16_BPB_BytsPerSec fs_g_sector[11]
Definition at line 114 of file fat.h.
#define LOW_16_BPB_FATSz16 fs_g_sector[22]
Definition at line 119 of file fat.h.
Referenced by fat_mount(), and fat_write_PBR().
#define LOW_16_BPB_FSInfo fs_g_sector[48]
Definition at line 138 of file fat.h.
Referenced by fat_mount().
#define LOW_16_BPB_ResvSecCnt fs_g_sector[14]
Definition at line 131 of file fat.h.
Referenced by fat_mount().
#define LOW_16_BPB_RootEntCnt fs_g_sector[17]
Definition at line 117 of file fat.h.
Referenced by fat_mount().
#define LOW_16_BPB_TotSec16 fs_g_sector[19]
Definition at line 125 of file fat.h.
Referenced by fat_mount().
#define U8_BPB_NumFATs fs_g_sector[16]
Definition at line 133 of file fat.h.
#define U8_BPB_SecPerClus fs_g_sector[13]
Definition at line 116 of file fat.h.
Referenced by fat_mount().
Typedef Documentation
typedef struct st_fs_cluster Fs_cluster
typedef U8 _MEM_TYPE_SLOW_* PTR_CACHE
Definition at line 418 of file fat.h.
Function Documentation
Bool fat_allocfreespace (void)
This function allocs a cluster list.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_seg.u32_addr          Last cluster value of a cluster list to link with the new cluster list
//!                              If no cluster list to link then set MSB0(fs_g_seg.u32_addr) to 0xFF
//!   fs_g_seg.u32_size_or_pos   Maximum size of cluster list to alloc (unit sector)
//! OUT:
//!   fs_g_seg.u32_addr          Return the first cluster value of the new cluster list
//!   fs_g_seg.u32_size_or_pos   The number of sector remainning (no allocated sectors, because disk fragmented or disk full)
//!
Definition at line 2294 of file fat_unusual.c.
References fat_clear_info_fat_mod(), fat_cluster_val(), fat_update_fat2(), fat_write_fat32_FSInfo(), FS_CLUST_VAL_EOL, FS_CLUST_VAL_READ, FS_CLUST_VAL_WRITE, FS_ERR_NO_FREE_SPACE, fs_g_cluster, fs_g_nav, fs_g_nav_fast, fs_g_seg, fs_g_status, FS_TYPE_FAT_32, Is_fat32, Fs_management::rootdir, Fs_segment::u32_addr, Fs_rootdir::u32_cluster, Fs_management::u32_CountofCluster, st_fs_cluster::u32_pos, Fs_segment::u32_size_or_pos, st_fs_cluster::u32_val, Fs_management::u8_BPB_SecPerClus, and Fs_management_fast::u8_type_fat.
Referenced by fat_alloc_entry_free(), fat_write_file(), and nav_dir_make().
{
   // Flag to signal the first step which search the first free cluster of the new list
   Bool first_cluster_free_is_found = FALSE;
   // If TRUE then use a quick procedure but don't scan all FAT else use a slow proceudre but scan all FAT
   Bool b_quick_find = TRUE;
   if( Is_fat32 )
   {
      // Clear info about free space
      if( !fat_write_fat32_FSInfo( 0xFFFFFFFF ))
         return FALSE;
   }
   if( 0xFF == MSB0(fs_g_seg.u32_addr) )
   {
fat_allocfreespace_start:
      // New cluster list, then research at the beginning of FAT
      fs_g_cluster.u32_pos = 2;
   }else{
      // Continue the cluster list then start after the end of the cluster list
      fs_g_cluster.u32_pos = fs_g_seg.u32_addr+1;
   }
   fat_clear_info_fat_mod();
   // Read ALL FAT1
   for(
   ;     fs_g_cluster.u32_pos < fs_g_nav.u32_CountofCluster
   ;     fs_g_cluster.u32_pos++ )
   {
      // Get the value of the cluster
      if ( !fat_cluster_val( FS_CLUST_VAL_READ ) )
         return FALSE;
      if ( 0 == fs_g_cluster.u32_val )
      {
         // A free cluster is found
         fs_g_cluster.u32_val = fs_g_cluster.u32_pos;    // value of the cluster is the new free cluster
         if( TRUE == first_cluster_free_is_found )
         {
            // Link the new cluster with previous cluster
            fs_g_cluster.u32_pos--;                      // select the previous cluster
            if ( !fat_cluster_val( FS_CLUST_VAL_WRITE ) )
               return FALSE;
         }
         else
         {
            // It is the first cluster of the new list
            first_cluster_free_is_found = TRUE;
            if( 0xFF != MSB0(fs_g_seg.u32_addr) )
            {
               // Link this new cluster with the current cluster list
               // Select the last cluster of the current list
               if( 0 == fs_g_seg.u32_addr )
               {  // The current cluster list is the cluster list of root directory
                  if( FS_TYPE_FAT_32 != fs_g_nav_fast.u8_type_fat )
                  {
                     // Impossible to increment ROOT DIR size of FAT12 or FAT16
                     fs_g_status = FS_ERR_NO_FREE_SPACE;
                     return FALSE;
                  }
                  fs_g_cluster.u32_pos = fs_g_nav.rootdir.u32_cluster;
               }
               else
               {
                  fs_g_cluster.u32_pos = fs_g_seg.u32_addr;
               }
               if ( !fat_cluster_val( FS_CLUST_VAL_WRITE ) )
                  return FALSE;
            }  // else no writing the first cluster value in FAT because no current cluster list
            fs_g_seg.u32_addr = fs_g_cluster.u32_val;    // save the first cluster value
         }
         // At the new cluster position, set the flag end of list
         fs_g_cluster.u32_pos = fs_g_cluster.u32_val;    // Select the new cluster
         fs_g_cluster.u32_val = FS_CLUST_VAL_EOL;        // Cluster value is the flag end of list
         if ( !fat_cluster_val( FS_CLUST_VAL_WRITE ) )
            return FALSE;
         // Compute the remaining sectors
         if ( fs_g_seg.u32_size_or_pos <= fs_g_nav.u8_BPB_SecPerClus )
         {
            fs_g_seg.u32_size_or_pos = 0; // All space found
            break;                        // Stop loop
         }
         fs_g_seg.u32_size_or_pos -= fs_g_nav.u8_BPB_SecPerClus;
      }
      else
      {
         // The next cluster is not free
         if( TRUE == first_cluster_free_is_found )
         {
            // To have a segment memory continue, the cluster list must be continue
            // then stop allocation
            break;
         }
         else
         {
            // It is the first step to search the first free cluster
            // then ignore this cluster no free and continue search
            if( b_quick_find )
            {
               fs_g_cluster.u32_pos += 500;
            }
         }
      }
   }
   // End of alloc
   if( FALSE == first_cluster_free_is_found )
   {
      if( b_quick_find )
      {
         // Retry in normal mode to scann all FAT (= no quick mode)
         b_quick_find = FALSE;
         goto fat_allocfreespace_start;
      }
      fs_g_status = FS_ERR_NO_FREE_SPACE; // NO FREE CLUSTER FIND
      return FALSE;
   }
   return fat_update_fat2();
}
#endif  // FS_LEVEL_FEATURES
void fat_cache_clear (void)
This function clears the sector cache.
Definition at line 1840 of file fat.c.
References FS_CACHE_SIZE, and fs_g_sector.
Referenced by fat_clean_zone(), fat_clear_cluster(), fat_write_fat32_FSInfo(), fat_write_MBR(), and fat_write_PBR().
{
   memset( fs_g_sector , 0 , FS_CACHE_SIZE );
}
void fat_cache_clusterlist_reset (void)
This function resets the cluster list caches.
Definition at line 882 of file fat.c.
References Fs_clusterlist_cache::b_cache_file, fs_g_cache_clusterlist, fs_g_u8_current_cache, FS_NB_CACHE_CLUSLIST, Fs_clusterlist_cache::u8_level_use, and Fs_clusterlist_cache::u8_lun.
Referenced by fat_check_device(), fat_cluster_list(), and nav_reset().
{
   U8 u8_i;
   fs_g_u8_current_cache=0;
   for( u8_i=0; u8_i<(FS_NB_CACHE_CLUSLIST*2); u8_i++ )
   {
      // The cache list is splited in two cache (file cluster list and directory cluster list)
      fs_g_cache_clusterlist[u8_i].b_cache_file = (u8_i<FS_NB_CACHE_CLUSLIST)?TRUE:FALSE;
      fs_g_cache_clusterlist[u8_i].u8_lun = 0xFF;
      fs_g_cache_clusterlist[u8_i].u8_level_use = 0xFF;
   }
}
Bool fat_cache_flush (void)
This function flushs the sector cache on the memory if necessary.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1860 of file fat.c.
References CTRL_GOOD, FS_ERR_HW, fs_g_sector, fs_g_sectorcache, fs_g_status, FS_LUN_WP, mem_wr_protect(), ram_2_memory(), Fs_sector_cache::u32_addr, Fs_sector_cache::u8_dirty, and Fs_sector_cache::u8_lun.
Referenced by fat_cache_read_sector(), fat_clean_zone(), fat_entry_label(), fat_format(), fat_serialnumber(), file_close(), file_set_eof(), nav_dir_make(), nav_exit(), nav_file_attributset(), nav_file_create(), nav_file_dateset(), nav_file_del(), and nav_file_rename().
{
   // If the cache is modified, then write the sector cache on the device
   if ( TRUE == fs_g_sectorcache.u8_dirty )
   {
      fs_g_sectorcache.u8_dirty = FALSE; // Always clear, although an error occur
      if( mem_wr_protect( fs_g_sectorcache.u8_lun  ))
      {
         fs_g_status = FS_LUN_WP;
         return FALSE;
      }
      if (CTRL_GOOD != ram_2_memory( fs_g_sectorcache.u8_lun , fs_g_sectorcache.u32_addr , fs_g_sector ))
      {
         fs_g_status = FS_ERR_HW;
         return FALSE;
      }
   }
   return TRUE;
}
void fat_cache_mark_sector_as_dirty (void)
This function sets a flag to signal that sector cache is modified.
Definition at line 1848 of file fat.c.
References fs_g_sectorcache, and Fs_sector_cache::u8_dirty.
Referenced by fat_clean_zone(), fat_clear_cluster(), fat_cluster_val(), fat_create_long_name_entry(), fat_create_short_entry_name(), fat_delete_file(), fat_entry_label(), fat_garbage_collector_entry(), fat_initialize_dir(), fat_initialize_fat(), fat_serialnumber(), fat_set_date(), fat_update_fat2(), fat_write_entry_file(), fat_write_fat32_FSInfo(), fat_write_MBR(), fat_write_PBR(), file_putc(), and file_write_buf().
{
   fs_g_sectorcache.u8_dirty = TRUE;
}
Bool fat_cache_read_sector (Bool b_load)
This function loads a memory sector in internal cache sector.
Parameters:
b_load TRUE, load the cache with the memory sector corresponding
FALSE, Don't change the sector cache but change the memory address of cache
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variable used
//! IN :
//!   fs_g_nav.u8_lun      drive number to read
//!   fs_gu32_addrsector   address to read (unit sector)
//!
Definition at line 1794 of file fat.c.
References CTRL_GOOD, fat_cache_flush(), fat_cache_reset(), FS_ERR_HW, fs_g_nav, fs_g_sector, fs_g_sectorcache, fs_g_status, fs_gu32_addrsector, memory_2_ram(), Fs_sector_cache::u32_addr, Fs_management::u8_lun, and Fs_sector_cache::u8_lun.
Referenced by fat_clean_zone(), fat_clear_cluster(), fat_cluster_readnext(), fat_cluster_val(), fat_get_nbpartition(), fat_getfreespace_percent(), fat_initialize_fat(), fat_mount(), fat_read_dir(), fat_read_fat32_FSInfo(), fat_read_file(), fat_serialnumber(), fat_update_fat2(), fat_write_fat32_FSInfo(), fat_write_MBR(), fat_write_PBR(), and file_write_buf().
{
   // Check if the sector asked is the same in cache
   if( (fs_g_sectorcache.u8_lun     == fs_g_nav.u8_lun )
   &&  (fs_g_sectorcache.u32_addr   == fs_gu32_addrsector ) )
   {
      return TRUE;
   }
   // Write previous cache before fill cache with a new sector
   if( !fat_cache_flush())
      return FALSE;
   // Delete informations about the caches
   fat_cache_reset();
   // Init sector cache
   fs_g_sectorcache.u32_addr = fs_gu32_addrsector;
   if( b_load )
   {
      // Load the sector from memory
      if( CTRL_GOOD != memory_2_ram( fs_g_nav.u8_lun  , fs_g_sectorcache.u32_addr, fs_g_sector))
      {
         fs_g_status = FS_ERR_HW;
         return FALSE;
      }
   }
   // Valid sector cache
   fs_g_sectorcache.u8_lun = fs_g_nav.u8_lun;
   return TRUE;
}
void fat_cache_reset (void)
This function resets the sector cache.
Definition at line 1829 of file fat.c.
References FS_BUF_SECTOR_EMPTY, fs_g_sectorcache, Fs_sector_cache::u32_clusterlist_start, Fs_sector_cache::u8_dirty, and Fs_sector_cache::u8_lun.
Referenced by fat_cache_read_sector(), fat_check_device(), and nav_reset().
{
   fs_g_sectorcache.u8_lun                = FS_BUF_SECTOR_EMPTY;
   fs_g_sectorcache.u8_dirty              = FALSE;
   fs_g_sectorcache.u32_clusterlist_start = 0xFFFFFFFF;
}
Bool fat_check_device (void)
This function checks device state.
Returns:
TRUE device ready
FALSE otherwise
//! This function updates all navigator datas when the device state change.
//!
Definition at line 91 of file fat.c.
References CTRL_BUSY, CTRL_GOOD, CTRL_NO_PRESENT, fat_cache_clusterlist_reset(), fat_cache_reset(), Fat_file_close, FS_ERR_HW, FS_ERR_HW_NO_PRESENT, fs_g_nav, fs_g_nav_fast, fs_g_navext, fs_g_navext_entry, fs_g_navext_fast, fs_g_sectorcache, fs_g_status, FS_NB_NAVIGATOR, FS_TYPE_FAT_UNM, g_b_no_check_disk, mem_test_unit_ready(), Fs_sector_cache::u8_lun, Fs_management::u8_lun, Fs_management_entry::u8_open_mode, and Fs_management_fast::u8_type_fat.
Referenced by fat_check_mount(), fat_check_noopen(), fat_get_nbpartition(), fat_mount(), nav_partition_freespace(), nav_partition_freespace_percent(), nav_partition_space(), and nav_partition_type().
{
   U8 retry=0;
#if (FS_NB_NAVIGATOR > 1)
   U8 i;
#endif
   Ctrl_status status;
   // Possibility to ignore the disk check. Used to take time during multi read/write access
   if( g_b_no_check_disk )
      return TRUE;
   if( 0xFF == fs_g_nav.u8_lun )
   {
      fs_g_status = FS_ERR_HW;
      return FALSE;                                // No device selected
   }
   for( retry=0 ; retry<100 ; retry++ )
   {
      // Check device
      status = mem_test_unit_ready( fs_g_nav.u8_lun );
      if( CTRL_GOOD       == status )
         return TRUE;                              // drive ready
      //* HERE error or state change
      // Clean all navigator datas which use this device
      fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_UNM; // By default the fat isn't mounted
      Fat_file_close();                            // By default the file is not open
#if (FS_NB_NAVIGATOR > 1)
      for( i=0 ; i!=(FS_NB_NAVIGATOR-1) ; i++ )
      {
         if( fs_g_nav.u8_lun == fs_g_navext[i].u8_lun )
         {
            fs_g_navext_fast[i].u8_type_fat     = FS_TYPE_FAT_UNM;   // By default the fat isn't mounted
            fs_g_navext_entry[i].u8_open_mode   = 0;                 // By default the file is not open
         }
      }
#endif
      // If the internal cache corresponding at device then clean it
      if( fs_g_nav.u8_lun == fs_g_sectorcache.u8_lun )
      {
         fat_cache_reset();
      }
      fat_cache_clusterlist_reset();
      fs_g_status = FS_ERR_HW;                     // By default HW error
      if( CTRL_BUSY == status )
         continue;                                 // If device busy then retry
      if( CTRL_NO_PRESENT == status )
         fs_g_status = FS_ERR_HW_NO_PRESENT;       // Update error flag
      break;                                       // FAIL or NOT PRESENT = fatal error = no retry
   }
   return FALSE;
}
Bool fat_check_eof_name (U16 character)
Check end of name.
Parameters:
character value of character to check
Returns:
TRUE, it is a character to signal a end of name (0,'\','/')
FALSE, otherwise
Definition at line 1763 of file fat.c.
Referenced by fat_check_name(), fat_create_short_entry_name(), and fat_entry_longname().
{
   return (('\0'==character)||('\\'==character)||('/'==character));
}
Bool fat_check_is_file (void)
This function checks if the selected file entry is a file and not a directory.
Returns:
TRUE It is a file and not a directory
FALSE otherwise
Definition at line 283 of file fat.c.
References Fat_is_not_a_file, FS_ERR_NO_FILE, and fs_g_status.
Referenced by file_ispresent(), and file_open().
{
   if( Fat_is_not_a_file )
   {
      fs_g_status = FS_ERR_NO_FILE;   // It isn't a file, it is a directory or a volume id
      return FALSE;
   }
   return TRUE;
}
Bool fat_check_mount (void)
This function checks if the partition is mounted.
Returns:
TRUE partition mounted
FALSE otherwise
Definition at line 154 of file fat.c.
References fat_check_device(), fat_mount(), FS_ERR_NO_MOUNT, fs_g_nav_fast, fs_g_status, FS_TYPE_FAT_UNM, and Fs_management_fast::u8_type_fat.
Referenced by fat_check_mount_noopen(), fat_check_mount_select(), fat_check_mount_select_noopen(), fat_check_mount_select_open(), and nav_partition_serialnumber().
{
   if( !fat_check_device() )
      return FALSE;
   if (FS_TYPE_FAT_UNM == fs_g_nav_fast.u8_type_fat)
   {
      if( !fat_mount() )
      {
         fs_g_status = FS_ERR_NO_MOUNT;
         return FALSE;
      }
   }
   return TRUE;
}
Bool fat_check_mount_noopen (void)
This function checks if the partition is mounted and no file is opened.
Returns:
TRUE partition mounted and no file is opened
FALSE otherwise
Definition at line 227 of file fat.c.
References fat_check_mount(), and fat_check_noopen().
Referenced by nav_dir_gotoparent(), nav_dir_is_root(), nav_dir_make(), nav_dir_name(), nav_filelist_reset(), nav_filelist_set(), nav_filterlist_gotoparent(), and nav_getcwd().
{
   if( !fat_check_mount() )
      return FALSE;
   return fat_check_noopen();
}
Bool fat_check_mount_select (void)
This function checks if the partition is mounted and if a file is selected.
Returns:
TRUE partition mounted and a file is selected
FALSE otherwise
Definition at line 270 of file fat.c.
References fat_check_mount(), and fat_check_select().
Referenced by file_ispresent(), nav_file_attributset(), nav_file_checkext(), nav_file_dateget(), nav_file_dateset(), nav_file_isreadonly(), and nav_file_name().
{
   if( !fat_check_mount() )
      return FALSE;
   return fat_check_select();
}
Bool fat_check_mount_select_noopen (void)
This function checks if the partition is mounted and if no file is opened and a file is selected.
Returns:
TRUE partition mounted and no file is opened and a file is selected
FALSE otherwise
Definition at line 240 of file fat.c.
References fat_check_mount(), fat_check_noopen(), and fat_check_select().
Referenced by file_open(), nav_dir_cd(), nav_file_del(), nav_file_rename(), and nav_filelist_validpos().
{
   if( !fat_check_mount() )
      return FALSE;
   if( !fat_check_select() )
      return FALSE;
   return fat_check_noopen();
}
Bool fat_check_mount_select_open (void)
This function checks if the partition is mounted and if a file is opened.
Returns:
TRUE partition mounted and a file is opened
FALSE otherwise
Definition at line 255 of file fat.c.
References fat_check_mount(), fat_check_open(), and fat_check_select().
Referenced by file_bof(), file_close(), file_eof(), file_getpos(), file_putc(), file_read(), file_read_buf(), file_seek(), file_set_eof(), file_write(), and file_write_buf().
{
   if( !fat_check_mount() )
      return FALSE;
   if( !fat_check_select() )
      return FALSE;
   return fat_check_open();
}
Bool fat_check_nav_access_disk (void)
This function checks write access.
Returns:
TRUE, write access on disk possibled
FALSE, File open then write access not possibled
Definition at line 1888 of file fat.c.
References FS_ERR_FILE_OPEN, fs_g_nav, fs_g_navext, fs_g_navext_entry, fs_g_navext_fast, fs_g_status, FS_NB_NAVIGATOR, FS_TYPE_FAT_UNM, and Fs_management::u8_lun.
Referenced by nav_drive_format().
{
   U8 i;
   // For each navigators
   for( i=0 ; i!=(FS_NB_NAVIGATOR-1) ; i++ )
   {
      // Disk mounted ?
      if( FS_TYPE_FAT_UNM != fs_g_navext_fast[i].u8_type_fat )
      // Is it the same disk ?
      if( fs_g_nav.u8_lun == fs_g_navext[i].u8_lun )
      // Is it access file ?
      if( fs_g_navext_entry[i].u8_open_mode!=0 )
      {
         fs_g_status = FS_ERR_FILE_OPEN;
         return FALSE;  // File opened then write access not possibled
      }
   }
   return TRUE;
}
Bool fat_check_nav_access_file (Bool mode)
This function checks all access at current file.
Parameters:
mode TRUE, check to write access
FALSE, check to read access
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail :
mode TRUE, File opened then write access not possibles
mode FALSE, File opened in write mode then read access not possibles
TRUE, access file possibles
Definition at line 1920 of file fat.c.
References FOPEN_WRITE_ACCESS, FS_ERR_FILE_OPEN, FS_ERR_FILE_OPEN_WR, fs_g_nav, fs_g_nav_fast, fs_g_navext, fs_g_navext_entry, fs_g_navext_fast, fs_g_status, FS_NB_NAVIGATOR, FS_TYPE_FAT_UNM, Fs_management_fast::u16_entry_pos_sel_file, Fs_management::u32_cluster_sel_dir, Fs_management::u8_lun, and Fs_management::u8_partition.
Referenced by file_open(), nav_file_del(), and nav_file_rename().
{
   U8 i;
   // For each navigators
   for( i=0 ; i!=(FS_NB_NAVIGATOR-1) ; i++ )
   {
      // Disk mounted ?
      if( FS_TYPE_FAT_UNM != fs_g_navext_fast[i].u8_type_fat )
      // Is it the same disk ?
      if( fs_g_nav.u8_lun == fs_g_navext[i].u8_lun )
#if (FS_MULTI_PARTITION == ENABLED)
      // Is it the same partition ?
      if( fs_g_nav.u8_partition == fs_g_navext[i].u8_partition )
#endif
      // Is it the same directory ?
      if( fs_g_nav.u32_cluster_sel_dir == fs_g_navext[i].u32_cluster_sel_dir )
      // Is it the same file ?
      if( fs_g_nav_fast.u16_entry_pos_sel_file == fs_g_navext_fast[i].u16_entry_pos_sel_file )
      {
         if( mode )
         {
            // Is it open ?
            if( fs_g_navext_entry[i].u8_open_mode!=0 )
            {
               fs_g_status = FS_ERR_FILE_OPEN;
               return FALSE;  // File opened then write access not possibled
            }
         }
         else
         {
            // Is it open in write mode ?
            if( fs_g_navext_entry[i].u8_open_mode & FOPEN_WRITE_ACCESS )
            {
               fs_g_status = FS_ERR_FILE_OPEN_WR;
               return FALSE;  // File opened in write mode then read access not possibled
            }
         }
      }
   }
   return TRUE;
}
Bool fat_check_noopen (void)
This function checks if a file is not opened on current navigator.
Returns:
TRUE no file opened
FALSE otherwise
Definition at line 175 of file fat.c.
References fat_check_device(), Fat_file_is_open, FS_ERR_TOO_FILE_OPEN, fs_g_nav_fast, fs_g_status, FS_TYPE_FAT_UNM, and Fs_management_fast::u8_type_fat.
Referenced by fat_check_mount_noopen(), fat_check_mount_select_noopen(), nav_drive_format(), nav_drive_set(), nav_filelist_fileisnotopen(), nav_partition_mount(), nav_partition_set(), and nav_setcwd().
{
   if( !fat_check_device() )
      return TRUE;
   if (FS_TYPE_FAT_UNM == fs_g_nav_fast.u8_type_fat)
      return TRUE;
   if( Fat_file_is_open() )
   {
      fs_g_status = FS_ERR_TOO_FILE_OPEN;  // The navigation have already open a file
      return FALSE;
   }
   return TRUE;
}
Bool fat_check_open (void)
This function checks if a file is opened on current navigator.
Returns:
TRUE a file is opened
FALSE otherwise
Definition at line 195 of file fat.c.
References Fat_file_isnot_open, FS_ERR_FILE_NO_OPEN, and fs_g_status.
Referenced by fat_check_mount_select_open().
{
   if( Fat_file_isnot_open() )
   {
      fs_g_status = FS_ERR_FILE_NO_OPEN;
      return FALSE;
   }
   return TRUE;
}
Bool fat_check_select (void)
This function checks if a file is selected on current navigator.
Returns:
TRUE a file is selected
FALSE otherwise
Definition at line 211 of file fat.c.
References FS_ERR_NO_FILE_SEL, fs_g_nav_fast, fs_g_status, FS_NO_SEL, and Fs_management_fast::u16_entry_pos_sel_file.
Referenced by fat_check_mount_select(), fat_check_mount_select_noopen(), fat_check_mount_select_open(), and nav_getcwd().
{
   if (FS_NO_SEL == fs_g_nav_fast.u16_entry_pos_sel_file)
   {
      fs_g_status = FS_ERR_NO_FILE_SEL;
      return FALSE;
   }
   return TRUE;
}
U8 fat_checkcluster (void)
This function checks the cluster value.
Returns:
value status
FS_CLUS_OK Value correct
FS_CLUS_BAD Value bad
FS_CLUS_END It is a end of list
//! Global variable used
//! IN :
//!   fs_g_cluster.u32_val       value to check
//!
Definition at line 845 of file fat.c.
References FS_CLUS_BAD, FS_CLUS_END, FS_CLUS_OK, fs_g_cluster, Is_fat12, Is_fat16, Is_fat32, and st_fs_cluster::u32_val.
Referenced by fat_cluster_list().
{
  if ( !fs_g_cluster.u32_val )
    return FS_CLUS_BAD;
  // Cluster bad if (FAT12 == 0x0FF7) (FAT16 == 0xFFF7) (FAT32 == 0x0FFFFFF7)
  // Last cluster if (FAT12 > 0x0FF7) (FAT16 > 0xFFF7) (FAT32 > 0x0FFFFFF7)
  if ( Is_fat32 )
  {
    if (fs_g_cluster.u32_val >= 0x0FFFFFF8)
      return FS_CLUS_END;
    else if (fs_g_cluster.u32_val == 0x0FFFFFF7)
      return FS_CLUS_BAD;
  }
  else if ( Is_fat16 )
  {
    if (fs_g_cluster.u32_val >= 0xFFF8)
      return FS_CLUS_END;
    else if (fs_g_cluster.u32_val == 0xFFF7)
      return FS_CLUS_BAD;
  }
  else if ( Is_fat12 )
  {
    if (fs_g_cluster.u32_val >= 0xFF8)
      return FS_CLUS_END;
    else if (fs_g_cluster.u32_val == 0xFF7)
      return FS_CLUS_BAD;
  }
  return FS_CLUS_OK;
}
Bool fat_clear_cluster (void)
This function clears one cluster.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_seg.u32_addr          Cluster value to clear
//!
Definition at line 2474 of file fat_unusual.c.
References fat_cache_clear(), fat_cache_mark_sector_as_dirty(), fat_cache_read_sector(), fat_cluster_list(), FS_CLUST_ACT_ONE, fs_g_nav, fs_g_seg, fs_gu32_addrsector, Fs_segment::u32_addr, Fs_segment::u32_size_or_pos, and Fs_management::u8_BPB_SecPerClus.
Referenced by fat_alloc_entry_free(), and fat_initialize_dir().
{
   U8 u8_loop;
   // Compute the cluster sector address
   fs_g_seg.u32_size_or_pos  = 0;   // Select the beginning of cluster
   if( !fat_cluster_list( FS_CLUST_ACT_ONE, FALSE ))
      return FALSE;
   // Loop in the cluster (start at the end of cluster)
   fs_gu32_addrsector = fs_g_seg.u32_addr + (fs_g_nav.u8_BPB_SecPerClus -1);
   for(  u8_loop = 0
   ;     fs_g_nav.u8_BPB_SecPerClus != u8_loop
   ;     u8_loop++ )
   {
      // Update internal cache with cluster sector inforamtion but don't read data from memory
      if( !fat_cache_read_sector( FALSE ))
         return FALSE;
      if(0 == u8_loop)
      {  // Clean internal cache (just for the sector)
         fat_cache_clear();
      }
      fat_cache_mark_sector_as_dirty();
      fs_gu32_addrsector--;         // go to previous sector
   }
   return TRUE;
}
#endif  // FS_LEVEL_FEATURES
void fat_clear_entry_info_and_ptr (void)
This function resets the selection pointers.
Definition at line 1394 of file fat.c.
References Fs_management::b_mode_nav, Fs_management::b_mode_nav_single, Fat_file_close, FS_DIR, fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, FS_NO_SEL, Fs_management_fast::u16_entry_pos_sel_file, Fs_management::u16_pos_sel_file, Fs_management_entry::u32_cluster, Fs_management_entry::u32_size, and Fs_management_entry::u8_attr.
Referenced by fat_mount(), nav_filelist_reset(), and nav_partition_mount().
{
   fs_g_nav_fast.u16_entry_pos_sel_file= FS_NO_SEL;
   fs_g_nav.u16_pos_sel_file           = FS_NO_SEL;
   if( !fs_g_nav.b_mode_nav_single )
   {
      fs_g_nav.b_mode_nav                 = FS_DIR;
   }
   fs_g_nav_entry.u8_attr     = 0;
   fs_g_nav_entry.u32_cluster = 0;
   fs_g_nav_entry.u32_size    = 0;
   Fat_file_close();
}
void fat_clear_info_fat_mod (void)
This function clears the cache information about FAT modifications.
Definition at line 2425 of file fat_unusual.c.
References fs_g_u16_first_mod_fat, and fs_g_u16_last_mod_fat.
Referenced by fat_allocfreespace(), and fat_cluster_list().
{
   fs_g_u16_first_mod_fat = 0xFFFF;
   fs_g_u16_last_mod_fat = 0;
}
#endif  // FS_LEVEL_FEATURES
Bool fat_cluster_list (U8 opt_action, Bool b_for_file)
This function gets or clears a cluster list.
Parameters:
b_for_file If TRUE then it is a file cluster list else a directory cluster list
opt_action Choose action on the cluster list
FS_CLUST_ACT_SEG Get continue memory segment corresponding at cluster list
FS_CLUST_ACT_ONE Get only one memory sector (512B) corresponding at cluster list
FS_CLUST_ACT_CLR Clear the cluster list
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_seg.u32_addr          The first cluster of the cluster list
//!   fs_g_seg.u32_size_or_pos   Start position in the cluster list (unit 512B)
//! OUT:
//!   fs_g_seg.u32_addr          The memory segment address corresponding at the beginning of cluster list (only for action FS_CLUST_ACT_SEG & FS_CLUST_ACT_ONE)
//!   fs_g_seg.u32_size_or_pos   The memory segment size corresponding at cluster list readed or cleared (unit 512B)
//!
Definition at line 364 of file fat.c.
References fat_cache_clusterlist_reset(), fat_cache_clusterlist_update_finish(), fat_cache_clusterlist_update_read(), fat_checkcluster(), fat_clear_info_fat_mod(), fat_cluster_readnext(), fat_cluster_val(), fat_update_fat2(), fat_write_fat32_FSInfo(), FS_CLUS_BAD, FS_CLUS_END, FS_CLUST_ACT_CLR, FS_CLUST_ACT_ONE, FS_CLUST_ACT_SEG, FS_CLUST_VAL_EOL, FS_CLUST_VAL_READ, FS_CLUST_VAL_WRITE, FS_ERR_FS, FS_ERR_OUT_LIST, fs_g_cache_clusterlist, fs_g_cluster, fs_g_nav, fs_g_seg, fs_g_status, fs_g_u8_current_cache, Is_fat12, Is_fat16, Is_fat32, Fs_management::rootdir, Fs_rootdir::seg, Fs_rootdir::u16_pos, Fs_rootdir::u16_size, Fs_segment::u32_addr, Fs_rootdir::u32_cluster, Fs_management::u32_offset_data, st_fs_cluster::u32_pos, Fs_management::u32_ptr_fat, Fs_segment::u32_size_or_pos, Fs_clusterlist_cache::u32_start, st_fs_cluster::u32_val, and Fs_management::u8_BPB_SecPerClus.
Referenced by fat_clear_cluster(), fat_read_dir(), and fat_read_file().
{
   _MEM_TYPE_FAST_ U32 u32_tmp;
   _MEM_TYPE_FAST_ U8 u8_cluster_status;
   fs_g_status = FS_ERR_FS;      // By default system error
   if(  Is_fat32
   &&  (FS_CLUST_ACT_CLR == opt_action) )
   {
#if (FSFEATURE_WRITE_COMPLET == (FS_LEVEL_FEATURES & FSFEATURE_WRITE_COMPLET))
      // Clear free space information storage in FAT32
      if( !fat_write_fat32_FSInfo( 0xFFFFFFFF ))
         return FALSE;
#else
      return FALSE;
#endif
   }
   if ( 0 == fs_g_seg.u32_addr )
   {
      // Cluster list of root directory
      if( FS_CLUST_ACT_CLR == opt_action )
         return FALSE;           // Impossible to erase ROOT DIR
      if ( Is_fat12 || Is_fat16 )
      {
         // For a FAT 12 & 16, the root dir isn't a cluster list
         // Check the position
         if ( fs_g_seg.u32_size_or_pos < fs_g_nav.rootdir.seg.u16_size )
         {
            // Compute the start address and the size
            fs_g_seg.u32_addr = fs_g_nav.u32_ptr_fat + fs_g_nav.rootdir.seg.u16_pos + fs_g_seg.u32_size_or_pos;
            fs_g_seg.u32_size_or_pos = fs_g_nav.rootdir.seg.u16_size - fs_g_seg.u32_size_or_pos;
            return TRUE;
         } else {
            fs_g_status = FS_ERR_OUT_LIST;
            return FALSE;        // Position outside the root area
         }
      }
      if ( Is_fat32 )
      {
         // For FAT 32, the root is a cluster list and the first cluster is reading during the mount
         fs_g_cluster.u32_pos = fs_g_nav.rootdir.u32_cluster;
      }
   } else {
      // It is the first cluster of a cluster list
      fs_g_cluster.u32_pos = fs_g_seg.u32_addr;
   }
   // Management of cluster list caches
   if( FS_CLUST_ACT_CLR != opt_action )
   {
      if( fat_cache_clusterlist_update_read( b_for_file ) )
         return TRUE;            // Segment found in cache
      // Segment not found & cache ready to update
   }else{
      fat_cache_clusterlist_reset();   // It is a clear action then clear cluster list caches
#if (FS_LEVEL_FEATURES > FSFEATURE_READ)
      fat_clear_info_fat_mod();        // Init cache on fat modification range
#endif  // FS_LEVEL_FEATURES
   }
   // Init loop with a start segment no found
   MSB0( fs_g_seg.u32_addr ) = 0xFF;
   //**** Loop to read the cluster list
   while ( 1 )
   {
      if ( fs_g_seg.u32_size_or_pos < fs_g_nav.u8_BPB_SecPerClus )
      {
         // The segment starts in this cluster
         // Compute the sector address of this cluster
         fs_g_seg.u32_addr = ((fs_g_cluster.u32_pos - 2) * fs_g_nav.u8_BPB_SecPerClus)
                           + fs_g_nav.u32_ptr_fat + fs_g_nav.u32_offset_data + fs_g_seg.u32_size_or_pos;
         if ( FS_CLUST_ACT_ONE == opt_action )
         {
            // Compute the maximum size
            fs_g_seg.u32_size_or_pos = fs_g_nav.u8_BPB_SecPerClus-fs_g_seg.u32_size_or_pos;
            fat_cache_clusterlist_update_finish();
            // Send a size of one sector
            fs_g_seg.u32_size_or_pos = 1;
            return TRUE;
         }
         // Update the segment size
         fs_g_seg.u32_size_or_pos = fs_g_nav.u8_BPB_SecPerClus - LSB0( fs_g_seg.u32_size_or_pos );
         // Take time, during read cluster list on FAT 16 & 32
         if( (FS_CLUST_ACT_SEG == opt_action)
         &&  (!Is_fat12) )
         {
            // Init loop with the current cluster
            u32_tmp = fs_g_cluster.u32_pos;
            if( !fat_cluster_val( FS_CLUST_VAL_READ ))
               return FALSE;
            // Read cluster list, while this one is continue
            while(1)
            {
               if ( (++fs_g_cluster.u32_pos) != fs_g_cluster.u32_val )
               {
                  fs_g_cluster.u32_pos--;                   // Recompute previous value
                  u32_tmp = fs_g_cluster.u32_pos - u32_tmp; // Compute the size of cluster list
                  fs_g_seg.u32_size_or_pos += u32_tmp * fs_g_nav.u8_BPB_SecPerClus;
                  break;
               }
               if( !fat_cluster_readnext() )
                  return FALSE;
            }
         }
      }
      // Get the cluster value
      if( !fat_cluster_val( FS_CLUST_VAL_READ ))
         return FALSE;
      // Read and check the status of the new cluster
      u8_cluster_status = fat_checkcluster();
      if (FS_CLUS_BAD == u8_cluster_status)
         return FALSE; // error, end of cluster list
      if (0xFF == MSB0(fs_g_seg.u32_addr))
      {
         // The beginning of the segment isn't found
         if (FS_CLUS_END == u8_cluster_status)
         {
            u32_tmp = fs_g_seg.u32_size_or_pos;       // Save number of sector remaining
            // Compute the sector address of this last cluster to take time during a futur request with the same cluster list
            fs_g_cache_clusterlist[fs_g_u8_current_cache].u32_start -= fs_g_seg.u32_size_or_pos;
            fs_g_seg.u32_addr = ((fs_g_cluster.u32_pos - 2) * fs_g_nav.u8_BPB_SecPerClus)
                              + fs_g_nav.u32_ptr_fat + fs_g_nav.u32_offset_data;
            fs_g_seg.u32_size_or_pos = fs_g_nav.u8_BPB_SecPerClus;
            if (FS_CLUST_ACT_CLR != opt_action)
               fat_cache_clusterlist_update_finish();
            // The position is outside the cluster list
            fs_g_seg.u32_addr = fs_g_cluster.u32_pos; // Send the last cluster value
            fs_g_seg.u32_size_or_pos = u32_tmp;       // Restore number of sector remaining
            fs_g_status = FS_ERR_OUT_LIST;
            return FALSE;
         }
         // Good cluster then continue
         fs_g_seg.u32_size_or_pos -= fs_g_nav.u8_BPB_SecPerClus;
#if (FS_LEVEL_FEATURES > FSFEATURE_READ)
         if (FS_CLUST_ACT_CLR == opt_action)
         {
            if( fs_g_seg.u32_size_or_pos == 0)
            {
               // At cluster position, set the flag end of cluster list
               fs_g_seg.u32_addr = fs_g_cluster.u32_val; // Save the next cluster
               fs_g_cluster.u32_val = FS_CLUST_VAL_EOL;
               if( !fat_cluster_val( FS_CLUST_VAL_WRITE ))
                  return FALSE;
               fs_g_cluster.u32_val = fs_g_seg.u32_addr; // Resotre the next cluster
               // !!!! It isn't necessary to reinit MSB0( fs_g_seg.u32_addr ) to 0xFF,
               // !!!! fs_g_seg.u32_addr will be modified at the beginning of main loop
            }
         }
#endif  // FS_LEVEL_FEATURES
      }
      else
      {
         // The beginning of segment is found
         if (FS_CLUST_ACT_SEG == opt_action)
         {
            if ( (fs_g_cluster.u32_pos+1) != fs_g_cluster.u32_val )
            {
               // The cluster is not a continue cluster or a invalid cluster
               fat_cache_clusterlist_update_finish();
               return TRUE;                              // End of segment
            }
         }
#if (FS_LEVEL_FEATURES > FSFEATURE_READ)
         if (FS_CLUST_ACT_CLR == opt_action)
         {
            //** Clear cluster position
            fs_g_seg.u32_addr = fs_g_cluster.u32_val;    // Save the next cluster
            fs_g_cluster.u32_val = 0;                    // by default free cluster
            // If it is the first cluster (fs_g_seg.u32_size_or_pos <= fs_g_nav.u8_BPB_SecPerClus)
            // and doesn't start at the beginning of cluster (fs_g_seg.u32_size_or_pos != fs_g_nav.u8_BPB_SecPerClus)
            if (fs_g_seg.u32_size_or_pos < fs_g_nav.u8_BPB_SecPerClus)
            {
               fs_g_cluster.u32_val = FS_CLUST_VAL_EOL;  // End of cluster list allocated
            }
            if( !fat_cluster_val( FS_CLUST_VAL_WRITE ))
               return FALSE;
            fs_g_cluster.u32_val = fs_g_seg.u32_addr;    // Resotre the next cluster
            // !!!! It isn't necessary to reinit MSB0( fs_g_seg.u32_addr ) at 0xFF,
            // !!!! because it isn't possible that MSB0( fs_g_cluster.val ) = 0xFF.
         }
#endif  // FS_LEVEL_FEATURES
         // Check the end of cluster list
         if (FS_CLUS_END == u8_cluster_status)
         {
#if (FS_LEVEL_FEATURES > FSFEATURE_READ)
            if (FS_CLUST_ACT_CLR == opt_action)
            {
               return fat_update_fat2();
            }
#endif  // FS_LEVEL_FEATURES
            fat_cache_clusterlist_update_finish();
            return TRUE; // End of segment
         }
         // Update the segment size
         fs_g_seg.u32_size_or_pos += fs_g_nav.u8_BPB_SecPerClus;
      }
      // HERE, Continue to read the cluster list
      // The next cluster is the value of previous cluster
      fs_g_cluster.u32_pos = fs_g_cluster.u32_val;
   }  // End of main loop
}
Bool fat_cluster_readnext (void)
This function is optimized to read a continue cluster list on FAT16 and FAT32.
Read global value "fs_g_status" in case of error : FS_ERR_HW Hardware driver error FS_LUN_WP Drive is read only
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_u16_pos_fat        previous cluster position in FAT
//! OUT:
//!   fs_g_u16_pos_fat        readed cluster position in FAT
//!   fs_g_cluster.u32_val    value of cluster readed
//!
Definition at line 798 of file fat.c.
References fat_cache_read_sector(), FS_CACHE_SIZE, fs_g_cluster, fs_g_sector, fs_g_u16_pos_fat, fs_gu32_addrsector, Is_fat32, and st_fs_cluster::u32_val.
Referenced by fat_cluster_list(), and fat_getfreespace().
{
   // Compute the next cluster position in FAT
   if ( Is_fat32 )
   {
      fs_g_u16_pos_fat += 4;
   }else{
      // Is_fat16
      fs_g_u16_pos_fat += 2;
   }
   // Check if next cluster is in internal cache
   if( FS_CACHE_SIZE == fs_g_u16_pos_fat )
   {
      // Update cache
      fs_g_u16_pos_fat = 0;
      fs_gu32_addrsector++;
      if( !fat_cache_read_sector( TRUE ))
         return FALSE;
   }
   //**** Read the cluster value
   LSB0( fs_g_cluster.u32_val ) = fs_g_sector[fs_g_u16_pos_fat+0];  // FAT 16,32
   LSB1( fs_g_cluster.u32_val ) = fs_g_sector[fs_g_u16_pos_fat+1];  // FAT 16,32
   if ( Is_fat32 )
   {  // FAT 32
      LSB2( fs_g_cluster.u32_val ) = fs_g_sector[fs_g_u16_pos_fat+2];
      LSB3( fs_g_cluster.u32_val ) = fs_g_sector[fs_g_u16_pos_fat+3];
   }
   return TRUE;
}
Bool fat_cluster_val (Bool b_mode)
This function returns or modifys a cluster value in FAT.
Parameters:
b_mode FALSE, to read a cluster value
TRUE, to write a cluster value
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_cluster.u32_pos    cluster number to read or write
//!   fs_g_cluster.u32_val    value to write
//! OUT:
//!   fs_g_cluster.u32_val    value readed
//!   fs_g_u16_pos_fat        position in FAT of the cluster to read or write
//!                           value init in case of the fat_cluster_readnext() routine is used after
//!
Definition at line 603 of file fat.c.
References fat_cache_mark_sector_as_dirty(), fat_cache_read_sector(), FS_CACHE_SIZE, FS_ERR_COMMAND, fs_g_cluster, fs_g_nav, fs_g_sector, fs_g_status, fs_g_u16_first_mod_fat, fs_g_u16_last_mod_fat, fs_g_u16_pos_fat, fs_gu32_addrsector, Is_fat12, Is_fat16, Is_fat32, st_fs_cluster::u32_pos, Fs_management::u32_ptr_fat, st_fs_cluster::u32_val, u8_data3, and u8_data4.
Referenced by fat_allocfreespace(), fat_cluster_list(), fat_getfreespace(), and fat_getfreespace_percent().
{
   _MEM_TYPE_FAST_ U16   u16_offset_fat;
   _MEM_TYPE_FAST_ U8    u8_data1, u8_data2;
#define  u8_data3    (LSB(u16_offset_fat)) // Manual overlay
#define  u8_data4    (MSB(u16_offset_fat)) // Manual overlay
   _MEM_TYPE_FAST_ PTR_CACHE u8_ptr_cluster;
   //**** Compute the cluster position in FAT (sector address & position in sector)
   if ( Is_fat32 )
   {
      // FAT 32
      // Optimization of -> u16_offset_fat = fs_g_cluster.pos * 4 / FS_CACHE_SIZE;
      // Optimization of -> u16_offset_fat = fs_g_cluster.pos / 128
      u16_offset_fat = fs_g_cluster.u32_pos >> (8-1);
      // Optimization of -> fs_g_u16_pos_fat = (fs_g_cluster.u32_pos * 4) % FS_CACHE_SIZE;
      // Optimization of -> fs_g_u16_pos_fat = (fs_g_cluster.u32_pos % 128) * 4
      fs_g_u16_pos_fat = ((U16)(LSB0(fs_g_cluster.u32_pos) & 0x7F))<< 2;
   }
   else if ( Is_fat16 )
   {
      // FAT 16
      // Optimization of -> u16_offset_fat = fs_g_cluster.u32_pos * 2 / FS_CACHE_SIZE = fs_g_cluster.u32_pos / 256;
      u16_offset_fat = LSB1(fs_g_cluster.u32_pos);
      // Optimization of -> fs_g_u16_pos_fat = (fs_g_cluster.u32_pos * 2) % FS_CACHE_SIZE;
      // Optimization of -> fs_g_u16_pos_fat = (fs_g_cluster.u32_pos % 256) * 2
      fs_g_u16_pos_fat = ((U16)LSB0(fs_g_cluster.u32_pos)) <<1;
   }
   else if ( Is_fat12 )
   {
      // FAT 12
      // Optimization of -> fs_g_u16_pos_fat = fs_g_cluster.u32_pos + (fs_g_cluster.u32_pos/ 2)
      fs_g_u16_pos_fat = (U16)fs_g_cluster.u32_pos + ((U16)fs_g_cluster.u32_pos >>1);
      // Optimization of -> u16_offset_fat = fs_g_cluster.u32_pos / FS_CACHE_SIZE
      u16_offset_fat = MSB(fs_g_u16_pos_fat) >> 1;
      // Optimization of -> fs_g_u16_pos_fat = fs_g_u16_pos_fat % FS_CACHE_SIZE
      MSB( fs_g_u16_pos_fat ) &= 0x01;
   }
#if (FS_LEVEL_FEATURES > FSFEATURE_READ)
   if (b_mode)
   {
      // Update information about FAT modification
      if( fs_g_u16_first_mod_fat > u16_offset_fat )
      {
         fs_g_u16_first_mod_fat = u16_offset_fat;
      }
      if( fs_g_u16_last_mod_fat < u16_offset_fat )
      {
         fs_g_u16_last_mod_fat = u16_offset_fat;
      }
      if ( Is_fat12 )
      {  // A cluster may be stored on two sectors
         if( fs_g_u16_pos_fat == (FS_CACHE_SIZE-1) )
         {  // Count the next FAT sector
            if( fs_g_u16_last_mod_fat < (u16_offset_fat+1) )
            {
               fs_g_u16_last_mod_fat = (u16_offset_fat+1);
            }
         }
      }
   }
#endif  // FS_LEVEL_FEATURES
   //**** Read cluster sector in FAT
   fs_gu32_addrsector = fs_g_nav.u32_ptr_fat + u16_offset_fat;   // Computed logical sector address
   if( !fat_cache_read_sector( TRUE ))
      return FALSE;
   // Read cluster information
   u8_ptr_cluster = &fs_g_sector[fs_g_u16_pos_fat];
   u8_data1 = u8_ptr_cluster[0];
   // Remark: if (fs_g_u16_pos_fat+1)=512 then it isn't a mistake, because this value will be erase in next lines
   u8_data2 = u8_ptr_cluster[1];
   u8_data3 = u8_ptr_cluster[2];
   u8_data4 = u8_ptr_cluster[3];
   if ( Is_fat12 )
   {   // A cluster may be stored on two sectors
      if(  fs_g_u16_pos_fat == (FS_CACHE_SIZE-1) )
      {  // Go to next sector
         fs_gu32_addrsector++;
         if( !fat_cache_read_sector( TRUE ))
           return FALSE;
         u8_data2 = fs_g_sector[0];
      }
   }
   if (FALSE == b_mode)
   {
      //**** Read the cluster value
      LSB0( fs_g_cluster.u32_val ) = u8_data1;  // FAT 12,16,32
      LSB1( fs_g_cluster.u32_val ) = u8_data2;  // FAT 12,16,32
      if ( Is_fat32 )
      {  // FAT 32
         LSB2( fs_g_cluster.u32_val ) = u8_data3;
         LSB3( fs_g_cluster.u32_val ) = u8_data4 & 0x0F; // The high 4 bits are reserved
      }
      else
      {  // FAT 12 & 16 don't use the high bytes
         LSB2( fs_g_cluster.u32_val ) = 0;
         LSB3( fs_g_cluster.u32_val ) = 0;
         // FAT 12 translate 16bits value to 12bits
         if ( Is_fat12 )
         {
            if ( 0x01 & LSB0(fs_g_cluster.u32_pos) )
            {  // Readed cluster is ODD
               LSB0( fs_g_cluster.u32_val ) = (LSB1( fs_g_cluster.u32_val ) <<4 ) + (LSB0( fs_g_cluster.u32_val ) >>4 );
               LSB1( fs_g_cluster.u32_val ) =  LSB1( fs_g_cluster.u32_val ) >>4 ;
            }
            else
            {  // Readed cluster is EVEN
               LSB1( fs_g_cluster.u32_val ) &= 0x0F;
            }
         }
      }
   } else {
#if (FS_LEVEL_FEATURES > FSFEATURE_READ)
      //**** Write the cluster value
      if ( Is_fat12 )
      {
         // FAT 12, translate cluster value
         if ( 0x01 & LSB0(fs_g_cluster.u32_pos) )
         {  // Cluster writing is ODD
            u8_data1 = (u8_data1 & 0x0F) + (LSB0( fs_g_cluster.u32_val )<<4);
            u8_data2 = (LSB1( fs_g_cluster.u32_val )<<4) + (LSB0( fs_g_cluster.u32_val )>>4) ;
         } else {
            // Cluster writing is EVEN
            u8_data1 = LSB0( fs_g_cluster.u32_val );
            u8_data2 = (u8_data2 & 0xF0) + (LSB1( fs_g_cluster.u32_val ) & 0x0F) ;
         }
         // A cluster may be stored on two sectors
         if( fs_g_u16_pos_fat == (FS_CACHE_SIZE-1) )
         {
            fs_g_sector[0] = u8_data2;
            fat_cache_mark_sector_as_dirty();
            // Go to previous sector
            fs_gu32_addrsector--;
            if( !fat_cache_read_sector( TRUE ))
              return FALSE;
            // Modify the previous sector
            fs_g_sector[ FS_CACHE_SIZE-1 ] = u8_data1;
            fat_cache_mark_sector_as_dirty();
            return TRUE;
         }
      }
      else
      {
         // FAT 16 & 32
         u8_data1 = LSB0( fs_g_cluster.u32_val );
         u8_data2 = LSB1( fs_g_cluster.u32_val );
         if ( Is_fat32 )
         {  // FAT 32
            u8_ptr_cluster[2] = LSB2( fs_g_cluster.u32_val );
            u8_ptr_cluster[3] = LSB3( fs_g_cluster.u32_val ) + (u8_data4 & 0xF0); // The high 4 bits are reserved
         }
      }
      // Here for FAT 32, 16 & 12 (only if the cluster values are in the same sector)
      u8_ptr_cluster[0] = u8_data1;
      u8_ptr_cluster[1] = u8_data2;
      fat_cache_mark_sector_as_dirty();
#else
      fs_g_status = FS_ERR_COMMAND;
      return FALSE;
#endif  // FS_LEVEL_FEATURES
   }
   return TRUE;
#undef  u8_data3    // end of Manual overlay
#undef  u8_data4    // end of Manual overlay
}
void fat_copy_nav (U8 u8_idnav)
This function copys the main navigator to another navigator.
Parameters:
u8_idnav Id navigator to fill
Definition at line 1994 of file fat.c.
References fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, fs_g_navext, fs_g_navext_entry, fs_g_navext_fast, and Fs_management_entry::u8_open_mode.
Referenced by nav_copy().
{
   if( 0 != u8_idnav)
   {
      u8_idnav--;
      memcpy_ram2ram((U8*)&fs_g_navext[u8_idnav],       (U8*)&fs_g_nav       , sizeof(Fs_management) );
      memcpy_ram2ram((U8*)&fs_g_navext_entry[u8_idnav], (U8*)&fs_g_nav_entry , sizeof(Fs_management_entry) );
      memcpy_ram2ram((U8*)&fs_g_navext_fast[u8_idnav],  (U8*)&fs_g_nav_fast  , sizeof(Fs_management_fast) );
      fs_g_navext_entry[u8_idnav].u8_open_mode=0;   // Clear open file flag
   }
}
Bool fat_create_entry_file_name (FS_STRING sz_name)
This function creates the short and the long name of a new entry.
Parameters:
sz_name name to create (ASCII or UNICODE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! IN:
//! b_unicode is a global flag to select UNICODE or ASCII
//! The name must be terminated by NULL and it can't have two dot characters.
//!
Definition at line 1500 of file fat_unusual.c.
References fat_alloc_entry_free(), fat_check_name(), fat_create_long_name_entry(), fat_create_short_entry_name(), fat_find_short_entry_name(), fat_read_dir(), FS_ENTRY_LFN_LAST, FS_ERR_FILE_EXIST, fs_g_nav_fast, fs_g_status, FS_SIZE_LFN_ENTRY, Is_unicode, and Fs_management_fast::u16_entry_pos_sel_file.
Referenced by nav_file_create().
{
   U8 u8_i, u8_nb;
   U8 u8_crc, u8_nb_entry;
   // Compute the number of entry for this name
   u8_nb_entry = fat_check_name( sz_name  );
   if( 0 == u8_nb_entry )
      return FALSE;
   // Search a unik short entry
   u8_nb = fat_find_short_entry_name( sz_name  );
   if( 0 == u8_nb )
   {
      fs_g_status = FS_ERR_FILE_EXIST;
      return FALSE;  // All short name exist
   }
   // Alloc a space for entrys
   if( !fat_alloc_entry_free( u8_nb_entry ))
      return FALSE;
   // Remark: here the pointer of entry is on the last free entry of new space allocated
   // Add short name entry
   u8_crc = fat_create_short_entry_name( sz_name , 0 , u8_nb, FALSE  );
   u8_nb_entry--;
   // For each long name entry
   for( u8_i=1 ; u8_i<=u8_nb_entry ; u8_i++ )
   {
      // Go to previous entry
      fs_g_nav_fast.u16_entry_pos_sel_file--;
      if( !fat_read_dir())
         return FALSE;
      // Write a long name entry
      if( u8_i == u8_nb_entry )
      {
         u8_i += FS_ENTRY_LFN_LAST;
      }
      fat_create_long_name_entry( sz_name , u8_crc , u8_i );
      sz_name += FS_SIZE_LFN_ENTRY*(Is_unicode? 2 : 1 );
  }
  // Go back to the short name entry
  fs_g_nav_fast.u16_entry_pos_sel_file += u8_nb_entry;
  return TRUE;
}
Bool fat_delete_file (Bool b_cluster_list)
This function deletes the file entries and cluster list.
Parameters:
b_cluster_list TRUE, delete file entries and cluster list FALSE, delete only file entries
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 2074 of file fat_unusual.c.
References fat_cache_mark_sector_as_dirty(), fat_get_ptr_entry(), fat_read_dir(), fat_read_file(), FS_ATTR_LFN_ENTRY, FS_CLUST_ACT_CLR, FS_ENTRY_DEL, FS_ENTRY_LFN_LAST, fs_g_nav_entry, fs_g_nav_fast, Fs_management_fast::u16_entry_pos_sel_file, and Fs_management_entry::u32_pos_in_file.
Referenced by nav_dir_make(), nav_file_del(), and nav_file_rename().
{
   PTR_CACHE ptr_entry;
   U8 u8_tmp;
   Bool b_short_del = FALSE;
   // loop in directory
   while( 1 )
   {
      // Fill internal cache with a sector from directory
      if( !fat_read_dir() )
         return FALSE;
      // Get pointer on the current entry
      ptr_entry = fat_get_ptr_entry();
      u8_tmp = ptr_entry[0];
      if( (FS_ATTR_LFN_ENTRY != ptr_entry[11])
      &&  (b_short_del) )
      {
         // no long entry exist, then only a short entry to delete
         break;   // Go to delete cluster list
      }
      // Delete entry
      b_short_del = TRUE;
      ptr_entry[0] = FS_ENTRY_DEL;
      fat_cache_mark_sector_as_dirty();
      if( (FS_ATTR_LFN_ENTRY == ptr_entry[11])
      &&  ( 0 != (FS_ENTRY_LFN_LAST & u8_tmp)) )
      {
         // It is the last entry of long name
         break;   // Go to delete cluster list
      }
      // Go to previous entry
      fs_g_nav_fast.u16_entry_pos_sel_file--;
   }  // end of while(1)
   if( b_cluster_list )
   {
      // Delete cluster list
      fs_g_nav_entry.u32_pos_in_file=0;      // Delete ALL list (start at begining)
      if( !fat_read_file( FS_CLUST_ACT_CLR ))
         return FALSE;
   }
   return TRUE;
}
#endif  // FS_LEVEL_FEATURES
Bool fat_entry_check (Bool b_type)
This function checks the entry.
Parameters:
b_type entry type to compare (FS_FILE or FS_DIR)
Returns:
TRUE, the entry is a short entry and correspond to b_type
FALSE, otherwise
//! Global variable used
//! IN :
//!   fs_g_sector       The directory sector corresponding at the current position
//!   fs_g_nav_fast.u16_entry_pos_sel_file    Position in directory of the entry file (unit entry)
//!
Definition at line 1243 of file fat.c.
References fat_get_ptr_entry(), FS_ATTR_DIRECTORY, FS_ATTR_VOLUME_ID, FS_DIR, FS_ENTRY_DEL, FS_ENTRY_END, FS_ERR_ENTRY_BAD, FS_ERR_ENTRY_EMPTY, FS_FILE, and fs_g_status.
Referenced by nav_filelist_set().
{
   PTR_CACHE u8_ptr_entry;
   U8 u8_first_byte, u8_seconde_byte;
   U8 u8_attribut;
   u8_ptr_entry = fat_get_ptr_entry();
   u8_first_byte = u8_ptr_entry[0];
   if ( FS_ENTRY_END == u8_first_byte )
   {
      fs_g_status = FS_ERR_ENTRY_EMPTY;   // end of directory
      return FALSE;
   }
   fs_g_status = FS_ERR_ENTRY_BAD;        // by default BAD ENTRY
   if ( FS_ENTRY_DEL == u8_first_byte )      { return FALSE;   } // entry deleted
   if (   '.'  == u8_first_byte )            { return FALSE;   } // current dir "."
   u8_seconde_byte = u8_ptr_entry[1];
   if ( ('.'  == u8_first_byte)
   &&   ('.'  == u8_seconde_byte) )          { return FALSE;   } // current dir ".."
   // Check attribut
   u8_attribut = u8_ptr_entry[11];
   if ( FS_ATTR_VOLUME_ID & u8_attribut )    { return FALSE;   } // volume id
   // Optimization, this line isn't necessary because the next test control this case
   // if ( FS_ATTR_LFN_ENTRY == *u8_ptr_entry) { return FALSE;   } // long file name
   // Check entry type
   if( FS_ATTR_DIRECTORY & u8_attribut )
   {
      return (FS_DIR == b_type);
   }else{
      return (FS_FILE == b_type);
   }
}
Bool fat_entry_checkext (FS_STRING sz_filter)
This function checks the file extension.
Parameters:
sz_filter extension filter is a ASCII string (ex: "mp3,w*")
Returns:
TRUE, the file name have a good extension
FALSE, otherwise
//! Global variable used
//! IN :
//!   fs_g_sector       The directory sector corresponding at the current position
//!   fs_g_nav_fast.u16_entry_pos_sel_file    Position in directory of the entry file (unit entry)
//!
Definition at line 1294 of file fat.c.
References fat_get_ptr_entry().
Referenced by nav_file_checkext().
{
   PTR_CACHE u8_ptr_entry;
   U8 u8_i, u8_filter_char, u8_entry_char;
   u8_ptr_entry = fat_get_ptr_entry();
   // Compare the extension with filter
   for( u8_i=0 ; u8_i<3 ; u8_i++)
   {
      u8_filter_char = *sz_filter;
      if ('*' == u8_filter_char)
         break; // All extension is good
      u8_entry_char = u8_ptr_entry[8+u8_i];
      // Compare the extension filter to extension file (this one ignore the case)
      if( (u8_filter_char!=  u8_entry_char     )
      &&  (u8_filter_char!= (u8_entry_char+('a'-'A'))) )
      {
         if ( (',' == u8_filter_char)
         ||   ( 0  == u8_filter_char) )
         {
           // It is the end of filter
           if (' ' == u8_entry_char)
              break; // it is the end of extension file -> extension good
         }
         // here, bad extension
         // Search the next filter
         while( ',' != u8_filter_char )
         {
            if (0  == u8_filter_char)
            {
               return FALSE;   // it is the last filter
            }
            sz_filter++;
            u8_filter_char = *sz_filter;
         }
         u8_i = 0xFF;          // restart loop compare
      }
      sz_filter++; // go to next char of filter
   }
   return TRUE; // It is a good extension
}
Bool fat_entry_is_dir (void)
This function checks if the entry file is a directory.
Returns:
TRUE, this entry is a directory
FALSE, otherwise
Definition at line 1385 of file fat.c.
References FS_ATTR_DIRECTORY, FS_ERR_NO_DIR, fs_g_nav_entry, fs_g_status, and Fs_management_entry::u8_attr.
Referenced by nav_dir_cd(), nav_file_isdir(), and nav_setcwd().
{
   fs_g_status = FS_ERR_NO_DIR;
   return (FS_ATTR_DIRECTORY & fs_g_nav_entry.u8_attr);
}
Bool fat_entry_label (Bool b_action, FS_STRING sz_label)
This function reads or writes a label in the partition.
Parameters:
b_action choose action (FS_LABEL_READ or FS_LABEL_WRITE)
sz_label string ASCII to store label (11B min) or to get new label (11B max)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1088 of file fat_unusual.c.
References fat_cache_flush(), fat_cache_mark_sector_as_dirty(), fat_get_ptr_entry(), FS_ATTR_VOLUME_ID, FS_ENTRY_END, FS_ERR_ENTRY_BAD, FS_ERR_ENTRY_EMPTY, FS_ERR_NAME_INCORRECT, fs_g_status, FS_LABEL_READ, and FS_LABEL_WRITE.
Referenced by nav_partition_label().
{
   PTR_CACHE ptr_entry;
   U8 u8_pos_name;
   U8 u8_char;
   ptr_entry = fat_get_ptr_entry();
   if( FS_LABEL_READ == b_action)
   {
      if( FS_ENTRY_END == ptr_entry[0] )           // end of directory
      {
         fs_g_status = FS_ERR_ENTRY_EMPTY;
         return FALSE;
      }
      if( FS_ATTR_VOLUME_ID != ptr_entry[11])      // no system label
      {
         fs_g_status = FS_ERR_ENTRY_BAD;
         return FALSE;
      }
      if( NULL == sz_label )
         return TRUE;
      for( u8_pos_name=0; u8_pos_name<11; u8_pos_name++ )
      {
         u8_char = *ptr_entry;
         if( 0x20 == u8_char )
            u8_char = 0;
         *sz_label = u8_char;
         if( 0 == u8_char )
            return TRUE;                           // Label readed
         ptr_entry++;
         sz_label++;
      }
      *sz_label = 0;
      return TRUE;
   }
   if( FS_LABEL_WRITE == b_action)
   {
      // Autorize to write the label only on an empty entry or the system label entry
      if( FS_ENTRY_END != ptr_entry[0] )           // end of directory
      {
         if( FS_ATTR_VOLUME_ID != ptr_entry[11])   // no system label
         {
            fs_g_status = FS_ERR_ENTRY_BAD;
            return FALSE;
         }
      }
      if( 0 == *sz_label )
      {
         fs_g_status = FS_ERR_NAME_INCORRECT;
         return FALSE;
      }
      ptr_entry[11] = FS_ATTR_VOLUME_ID;
      for( u8_pos_name=0; u8_pos_name<11; u8_pos_name++ )
      {
         u8_char = *sz_label;
         if( ('a'<=u8_char) && (u8_char<='z') )
         {
            u8_char -= ('a'-'A');                  // Change to upper case
         }
         if( 0 == u8_char )
         {
            u8_char = 0x20;
         }
         *ptr_entry = u8_char;
         ptr_entry++;
         if( 0x20 == u8_char )
            continue;
         sz_label++;
      }
      fat_cache_mark_sector_as_dirty();
      return fat_cache_flush();
   }
   return FALSE;                                   // To delete the compilation warning
}
#endif  // FS_LEVEL_FEATURES
Bool fat_entry_longname (FS_STRING sz_name, U8 u8_size_max, Bool b_mode, Bool b_match_case)
This function returns or compares the long name entry.
Parameters:
b_mode action mode:
FS_NAME_GET to get the long name of selected file
FS_NAME_CHECK to compare the long name of selected file
sz_name if FS_NAME_GET then buffer to store the long name file (ASCII or UNICODE)
if FS_NAME_CHECK then name to compare with long name (ASCII or UNICODE), it must be terminate by NULL or '*' value
b_match_case FALSE, ignore the case (only used in "FS_NAME_CHECK" action mode)
u8_size_max buffer size (unit ASCII or UNICODE) (ignored in "FS_NAME_CHECK" mode)
Returns:
FALSE is not the end of long name, or in case of error, see global value "fs_g_status" for more detail
TRUE, the name is correct or read is finish
//! Global variable used
//! IN :
//!   fs_g_sector       The directory sector corresponding at the current position
//!   fs_g_nav_fast.u16_entry_pos_sel_file    Position in directory of the entry file (unit entry)
//!
Definition at line 1607 of file fat.c.
References fat_check_eof_name(), fat_get_ptr_entry(), FS_ATTR_LFN_ENTRY, FS_ENTRY_DEL, FS_ENTRY_END, FS_ENTRY_LFN_LAST, FS_ERR_ENTRY_BAD, FS_ERR_NAME_INCORRECT, fs_g_status, FS_NAME_GET, FS_NO_LAST_LFN_ENTRY, FS_SIZE_FILE_ENTRY, g_b_string_length, and Is_unicode.
Referenced by nav_file_name().
{
   U8 u8_pos_name;
   PTR_CACHE ptr_entry;
   U16 u16_unicode_entry;
   U16 u16_unicode_szname;
   ptr_entry = fat_get_ptr_entry();
   if( (FS_ENTRY_END == *ptr_entry )            // end of directory
   ||  (FS_ENTRY_DEL == *ptr_entry )            // entry deleted
   ||  (FS_ATTR_LFN_ENTRY != ptr_entry[11]) )   // no long name
   {
      fs_g_status = FS_ERR_ENTRY_BAD;
      return FALSE;
   }
   if( g_b_string_length )
   {
      if ( 0 == (FS_ENTRY_LFN_LAST & *ptr_entry))
      {
         // no necessary -> ((FS_STR_UNICODE)sz_name)[0] = FS_SIZE_LFN_ENTRY;
         fs_g_status = FS_NO_LAST_LFN_ENTRY;
         return FALSE;                          // Other entry long name
      }
   }
   ptr_entry++;                                 // The long name start at offset 1 of the entry file
   u8_pos_name=0;
   while( 1 )
   {
      LSB(u16_unicode_entry) = ptr_entry[0];
      MSB(u16_unicode_entry) = ptr_entry[1];
      if( FS_NAME_GET == b_mode )
      {
         if( !g_b_string_length )
         {
            // Check the end of buffer
            if( u8_pos_name>=(u8_size_max-1) )
            {
               // Write end of string
               if( Is_unicode )
               {
                  ((FS_STR_UNICODE)sz_name)[0] = 0;
               }else{
                  sz_name[0] = 0;
               }
               return TRUE;                     // the buffer is full
            }
            // Read and store the long name
            if( Is_unicode )
            {
               ((FS_STR_UNICODE)sz_name)[0] = u16_unicode_entry;
            }else{
               sz_name[0] = (U8)u16_unicode_entry;
            }
         }
      }
      else
      {
         if( Is_unicode )
         {
            u16_unicode_szname = ((FS_STR_UNICODE)sz_name)[0];
         }else{
            u16_unicode_szname = sz_name[0];
         }
         // Check the name
         if( '*' == u16_unicode_szname )
         {  // end of filter name which autorise all next character
            return TRUE;   //*** The name is correct ***
         }
         if( ((0 != u16_unicode_entry ) || (( '\\' != u16_unicode_szname) && ( '/' != u16_unicode_szname)) )
         &&  ((u16_unicode_szname != (u16_unicode_entry+('a'-'A'))) || b_match_case)
         &&  ((u16_unicode_szname != (u16_unicode_entry-('a'-'A'))) || b_match_case)
         &&  (u16_unicode_szname != u16_unicode_entry) )
         {
           fs_g_status = FS_ERR_NAME_INCORRECT; //  The name don't corresponding at filter name
           return FALSE;
         }
      }
      if( 0 == u16_unicode_entry)
      {
         if( g_b_string_length )
         {
            ((FS_STR_UNICODE)sz_name)[0] = u8_pos_name+1;
         }
         return TRUE;                           // Last long name entry
      }
      if( 4 == u8_pos_name )
         ptr_entry += 3;                        // Go to second character
      if( 10 == u8_pos_name )
         ptr_entry += 2;                        // Go to third character
      if( 12 == u8_pos_name )
      {  // End of entry long name
         ptr_entry -= (FS_SIZE_FILE_ENTRY-2);   // Go to the first byte of the file entry
         if ( 0 == (FS_ENTRY_LFN_LAST & ptr_entry[0]))
         {
            fs_g_status = FS_NO_LAST_LFN_ENTRY;
            return FALSE;                       // Other long name entry is present
         }
         else
         {  // It is the last long name entry
            // then it is the end of name
            if( (FS_NAME_GET == b_mode) && g_b_string_length )
            {
               ((FS_STR_UNICODE)sz_name)[0] = 14;
               return TRUE;
            }
            sz_name += (Is_unicode? 2 : 1 );
            if( FS_NAME_GET == b_mode )
            {
               // Write end of string UNICODE
               if( Is_unicode )
               {
                  ((FS_STR_UNICODE)sz_name)[0] = 0;
               }else{
                  sz_name[0] = 0;
               }
               return TRUE;
            }
            else
            {
               // if it is the end of filter
               if( Is_unicode )
               {
                  u16_unicode_szname = ((FS_STR_UNICODE)sz_name)[0];
               }else{
                  u16_unicode_szname = sz_name[0];
               }
               return fat_check_eof_name(u16_unicode_szname);
            }
         }
      }
      if( !g_b_string_length )
      {
         sz_name += (Is_unicode? 2 : 1 );
      }
      u8_pos_name++;
      ptr_entry+=2;
   }
}
Bool fat_entry_shortname (FS_STRING sz_name, U8 u8_size_max, Bool b_mode)
This function returns or compares the short name entry.
Parameters:
b_mode action mode:
FS_NAME_GET to get the short name of selected file
FS_NAME_CHECK to compare the short name of selected file
sz_name if FS_NAME_GET then buffer to store the short name file (ASCII or UNICODE)
if FS_NAME_CHECK then name to compare with short name (ASCII or UNICODE), it must be terminate by NULL or '*' value
u8_size_max buffer size (unit ASCII or UNICODE) (ignored in "FS_NAME_CHECK" mode)
Returns:
FALSE, in case of error, see global value "fs_g_status" for more detail
TRUE, the name is correct or read OK
//! Global variable used
//! IN :
//!   fs_g_sector       The directory sector corresponding at the current position
//!   fs_g_nav_fast.u16_entry_pos_sel_file    Position in directory of the entry file (unit entry)
//!
Definition at line 1476 of file fat.c.
References fat_get_ptr_entry(), FS_ERR_NAME_INCORRECT, fs_g_status, FS_NAME_GET, FS_SIZE_SFNAME, FS_SIZE_SFNAME_WITHOUT_EXT, g_b_string_length, and Is_unicode.
Referenced by nav_file_name().
{
   Bool b_extension_nostart = TRUE;
   U8 u8_pos_name;
   U8 u8_entry_char, u8_szname_char;
   PTR_CACHE ptr_entry;
   U8 u8_pos_entry;
   fs_g_status = FS_ERR_NAME_INCORRECT;  // by default the name don't corresponding at filter name
   u8_pos_name = 0;
   u8_pos_entry = 0;
   ptr_entry = fat_get_ptr_entry();
   // for each characters of short name
   while( 1 )
   {
      if( FS_SIZE_SFNAME == u8_pos_entry )
      {
         u8_entry_char = 0;   // end of name
      }
      else
      {
         u8_entry_char = ptr_entry[ u8_pos_entry ];
         if( ((FS_SIZE_SFNAME_WITHOUT_EXT == u8_pos_entry) && b_extension_nostart)  // end of name and '.' character no writed
         ||  ( ' ' == u8_entry_char) )
         {
            // end of name or extension
            if( (FS_SIZE_SFNAME_WITHOUT_EXT >= u8_pos_entry)         // End of name without extension
            &&  (' ' != ptr_entry[ FS_SIZE_SFNAME_WITHOUT_EXT ]) )   // extension exists
            {
               // go to extension position
               b_extension_nostart = FALSE;
               u8_pos_entry = FS_SIZE_SFNAME_WITHOUT_EXT-1;
               u8_entry_char = '.';
            }
            else
            {
               u8_entry_char = 0;                                    // end of name
            }
         }
      }
      if( FS_NAME_GET == b_mode )
      {
         if( !g_b_string_length )
         {
            if(u8_pos_name >= (u8_size_max-1))
               u8_entry_char = 0;                                    // buffer full then force end of string
            if( ('A'<=u8_entry_char) && (u8_entry_char<='Z'))
               u8_entry_char += ('a'-'A');                           // display short name in down case
            if( Is_unicode )
            {
               ((FS_STR_UNICODE)sz_name)[0] = u8_entry_char;
            }else{
               sz_name[0] = u8_entry_char;
            }
         }
      }
      else
      {
         // Compare the name
         if( Is_unicode
         && (0 != MSB(((FS_STR_UNICODE)sz_name)[0])) )
         {
            // The UNICODE is not possibled in short name
            return FALSE;
         }
         if( Is_unicode )
         {
            u8_szname_char = ((FS_STR_UNICODE)sz_name)[0];
         }else{
            u8_szname_char = sz_name[0];
         }
         if ('*' == u8_szname_char)
         {  // end of filter name which autorise all next character
            return TRUE;   //*** The name is correct ***
         }
         if( (0 != u8_entry_char) || (('\\' != u8_szname_char) && ('/' != u8_szname_char)) )
         {
            if((u8_szname_char != u8_entry_char)
            && (u8_szname_char != (u8_entry_char+('a'-'A'))) )  // no case sensitive
               return FALSE;  // short name not equal
         }
      }
      // For each characters
      if (0 == u8_entry_char)
      {
         if( g_b_string_length )
         {
            ((FS_STR_UNICODE)sz_name)[0] = u8_pos_name+1;      // Get length name
         }
         return TRUE;   // End of test correct or end of get name
      }
      if( !g_b_string_length )
      {
         sz_name += (Is_unicode? 2 : 1 );
      }
      u8_pos_name++;
      u8_pos_entry++;
   }
}
Bool fat_format (U8 u8_fat_type)
This function formats the drive.
This function formats the drive.
Parameters:
u8_fat_type Select the type of format
FS_FORMAT_DEFAULT, The file system module choose the better FAT format for the drive space
FS_FORMAT_FAT, The FAT12 or FAT16 is used to format the drive, if possible (disk space <2GB)
FS_FORMAT_FAT32, The FAT32 is used to format the drive, if possible (disk space >32MB)
FS_FORMAT_NOMBR_FLAG if you don't want a MRB in disk then add this flag (e.g. FAT format on a CD support)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//! fs_g_nav.u8_lun        indicate the drive to format
//!
//! This routine can't format a multi-partiton, if the disk contains a multi-partition area
//! then the multi-partition will be erased and replaced by a single partition on all disk space.
//!
Definition at line 341 of file fat_unusual.c.
References fat_cache_flush(), fat_clean_zone(), fat_initialize_fat(), fat_select_filesystem(), fat_write_MBR(), fat_write_PBR(), FS_FORMAT_NOMBR_FLAG, fs_g_nav, fs_s_u32_size_partition, mem_read_capacity(), Fs_management::u8_lun, and Fs_management::u8_partition.
Referenced by nav_drive_format().
{
   Bool b_MBR;
#if (FS_MULTI_PARTITION == ENABLED)
#error NOT SUPPORTED
   fs_g_nav.u8_partition = 0;
#endif
   // Get drive capacity (= last LBA)
   mem_read_capacity( fs_g_nav.u8_lun , &fs_s_u32_size_partition );
   if( u8_fat_type & FS_FORMAT_NOMBR_FLAG )
   {
      b_MBR = FALSE;
      u8_fat_type &= ~FS_FORMAT_NOMBR_FLAG;
      // partition size = disk size = last LBA + 1
      fs_s_u32_size_partition++;
   }else{
      b_MBR = TRUE;
      // partition size = size disk -1 = last LBA
   }
   // Compute the FAT type for the device
   if( !fat_select_filesystem( u8_fat_type , b_MBR ))
      return FALSE;
   // Write the MBR sector (first sector)
   if( b_MBR )
      if( !fat_write_MBR())
         return FALSE;
   // Write the PBR sector
   if( !fat_write_PBR( b_MBR ))
      return FALSE;
   // Clear reserved zone, FAT zone, and Root dir zone
   // Remark: the reserved zone of FAT32 isn't initialized, because BPB_FSInfo is equal to 0
   if( !fat_clean_zone( b_MBR ))
      return FALSE;
   // Initialization of the FAT 1 and 2
   if( !fat_initialize_fat())
      return FALSE;
   return fat_cache_flush();
}
void fat_get_date (FS_STRING sz_date, Bool type_date)
This function reads the information about a date.
Parameters:
type_date choose the date type (FS_DATE_LAST_WRITE or FS_DATE_CREATION)
sz_date table to store the date
storage format (ASCII) = "YYYYMMDDHHMMSSMS" = year, month, day, hour, minute, seconde, miliseconde
Definition at line 1222 of file fat_unusual.c.
References fat_get_ptr_entry(), fat_translatedate_number_to_ascii(), and FS_DATE_LAST_WRITE.
Referenced by nav_file_dateget().
{
   PTR_CACHE ptr_entry;
   ptr_entry = fat_get_ptr_entry();
   if( FS_DATE_LAST_WRITE == type_date )
   {
      fat_translatedate_number_to_ascii( sz_date , &ptr_entry[22] , FALSE );
   }
   else
   {
      fat_translatedate_number_to_ascii( sz_date , &ptr_entry[13] , TRUE );
   }
}
void fat_get_entry_info (void)
This function reads information about selected file.
//! Global variable used
//! IN :
//!   fs_g_sector       The directory sector corresponding at the current position
//!   fs_g_nav_fast.u16_entry_pos_sel_file    Position in directory of the entry file (unit entry)
//! OUT:
//!   fs_g_nav_entry. u32_cluster, u8_attr, u32_size
//!
Definition at line 1353 of file fat.c.
References fat_get_ptr_entry(), fs_g_nav_entry, Fs_management_entry::u32_cluster, Fs_management_entry::u32_size, and Fs_management_entry::u8_attr.
Referenced by nav_dir_gotoparent(), nav_filelist_set(), and nav_filterlist_gotoparent().
{
   PTR_CACHE ptr_entry;
   ptr_entry = fat_get_ptr_entry();
   // Get attribut
   ptr_entry+= 11;
   fs_g_nav_entry.u8_attr = ptr_entry[0];
   // Get the first cluster of the file cluster list
   ptr_entry += (20-11);
   LSB2(fs_g_nav_entry.u32_cluster) = ptr_entry[0];
   LSB3(fs_g_nav_entry.u32_cluster) = ptr_entry[1];
   ptr_entry += (26-20);
   LSB0(fs_g_nav_entry.u32_cluster) = ptr_entry[0];
   LSB1(fs_g_nav_entry.u32_cluster) = ptr_entry[1];
   // Get the size of file
   ptr_entry += (28-26);
   LSB0(fs_g_nav_entry.u32_size) = ptr_entry[0];
   LSB1(fs_g_nav_entry.u32_size) = ptr_entry[1];
   LSB2(fs_g_nav_entry.u32_size) = ptr_entry[2];
   LSB3(fs_g_nav_entry.u32_size) = ptr_entry[3];
}
U8 fat_get_nbpartition (void)
This function returns the number of partition present on selected drive.
This function returns the number of partition present on selected drive.
Returns:
u8_number number of partition
Definition at line 299 of file fat.c.
References fat_cache_read_sector(), fat_check_device(), FS_BR_SIGNATURE_HIGH, FS_BR_SIGNATURE_LOW, fs_g_sector, fs_gu32_addrsector, and FS_MBR_OFFSET_PART_ENTRY.
Referenced by nav_partition_nb().
{
   if( !fat_check_device() )
      return 0;
#warning this routine contains bug, rework it
   // Read the first sector of drive
   fs_gu32_addrsector = 0;
   if( !fat_cache_read_sector( TRUE ))
      return FALSE;
   // Check PBR or MBR signature
   if ( (fs_g_sector[510] != FS_BR_SIGNATURE_LOW  )
   &&   (fs_g_sector[511] != FS_BR_SIGNATURE_HIGH ) )
   {
      // No MBR
      // The sector, is it a PBR ?
      if ( (fs_g_sector[0] == 0xEB) &&          // PBR Byte 0
           (fs_g_sector[2] == 0x90) &&          // PBR Byte 2
           ((fs_g_sector[21] & 0xF0) == 0xF0) ) // PBR Byte 21 : Media byte
      {
         return 1;   // No MBR but PBR exist then only one partition
      } else {
         return 0;   // No MBR and no PBR then no partition found
      }
   }
   number_part = 0;
   while( 1 )
   {
      // The first sector must be a MBR, then check the partition entry in the MBR
      if ( ((fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(number_part)+0] != FS_PARTITION_ACTIVE) &&
            (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(number_part)+0] != 0x00))
      ||    (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(number_part)+4] == 0x00) )
      {
         break;
      }
      number_part++;
   }
   return number_part;
}
PTR_CACHE fat_get_ptr_entry (void)
This function returns a cache pointer on the current entry.
Returns:
a pointer on the internal cache
Definition at line 1773 of file fat.c.
References FS_512B_MASK, fs_g_nav_fast, fs_g_sector, FS_SIZE_FILE_ENTRY, and Fs_management_fast::u16_entry_pos_sel_file.
Referenced by fat_alloc_entry_free(), fat_create_long_name_entry(), fat_create_short_entry_name(), fat_delete_file(), fat_entry_check(), fat_entry_checkext(), fat_entry_label(), fat_entry_longname(), fat_entry_shortname(), fat_entry_shortname_compare(), fat_garbage_collector_entry(), fat_get_date(), fat_get_entry_info(), fat_set_date(), and fat_write_entry_file().
{
   return &fs_g_sector[(fs_g_nav_fast.u16_entry_pos_sel_file * FS_SIZE_FILE_ENTRY) & FS_512B_MASK];
}
U32 fat_getfreespace (void)
This function returns the space free in the partition.
Returns:
the number of sector free
if 0, then error or full
Definition at line 2133 of file fat_unusual.c.
References fat_cluster_readnext(), fat_cluster_val(), fat_read_fat32_FSInfo(), fat_write_fat32_FSInfo(), FS_CLUST_VAL_READ, fs_g_cluster, fs_g_nav, Is_fat12, Is_fat32, Fs_management::u32_CountofCluster, st_fs_cluster::u32_pos, st_fs_cluster::u32_val, and Fs_management::u8_BPB_SecPerClus.
Referenced by fat_getfreespace_percent(), and nav_partition_freespace().
{
   U32 u32_nb_free_cluster = 0;
   // Read ALL FAT1
   fs_g_cluster.u32_pos = 2;
   if( Is_fat12 )
   {  // FAT12 only
      for(
      ;     fs_g_cluster.u32_pos < fs_g_nav.u32_CountofCluster
      ;     fs_g_cluster.u32_pos++ )
      {
         // Get the value of the cluster
         if ( !fat_cluster_val( FS_CLUST_VAL_READ ) )
            return 0;
         if ( 0 == fs_g_cluster.u32_val )
            u32_nb_free_cluster++;
      }
   }
   else
   {
      if( Is_fat32 )
      {
         u32_nb_free_cluster = fat_read_fat32_FSInfo();
         if( 0xFFFFFFFF != u32_nb_free_cluster )
            goto endof_fat_getfreespace;
         u32_nb_free_cluster = 0;
      }
      // Speed optimization only for FAT16 and FAT32
      // init first value used by fat_cluster_readnext()
      if( !fat_cluster_val( FS_CLUST_VAL_READ ))
         return FALSE;
      for(
      ;     fs_g_cluster.u32_pos < fs_g_nav.u32_CountofCluster
      ;     fs_g_cluster.u32_pos++ )
      {
         if ( 0 == fs_g_cluster.u32_val )
            u32_nb_free_cluster++;
         if( !fat_cluster_readnext() )
            return FALSE;
      }
#if (FSFEATURE_WRITE_COMPLET == (FS_LEVEL_FEATURES & FSFEATURE_WRITE_COMPLET))
      if( Is_fat32 )
      {
         // Save value for the future call
         fat_write_fat32_FSInfo( u32_nb_free_cluster );
      }
#endif
   }
endof_fat_getfreespace:
   return (u32_nb_free_cluster * fs_g_nav.u8_BPB_SecPerClus);
}
U8 fat_getfreespace_percent (void)
This function returns the space free in percent.
Returns:
percent of free space (1 to 100) if 0, then error or full
//! More speed than fat_getfreespace() routine but error delta 1%
//!
Definition at line 2198 of file fat_unusual.c.
References fat_cache_read_sector(), fat_cluster_val(), fat_getfreespace(), fat_read_fat32_FSInfo(), FS_CLUST_VAL_READ, fs_g_cluster, fs_g_nav, fs_g_sector, fs_gu32_addrsector, Is_fat12, Is_fat16, Is_fat32, Fs_management::u16_fat_size, Fs_management::u32_CountofCluster, st_fs_cluster::u32_pos, and Fs_management::u8_BPB_SecPerClus.
Referenced by nav_partition_freespace_percent().
{
   U32 u32_nb_free_cluster = 0;
   U16 u16_tmp, u16_pos;
   if( Is_fat12 )
   {  // No speed optimization necessary on FAT12
      return (((fat_getfreespace()/fs_g_nav.u8_BPB_SecPerClus)*100) / fs_g_nav.u32_CountofCluster);
   }
   fs_g_cluster.u32_pos = 2;
   // Init first value used by fat_cluster_readnext()
   if( !fat_cluster_val( FS_CLUST_VAL_READ ))
      return FALSE;
   // The optimization is to
   // - read only the LSB byte of cluster
   // - read only 1 cluster for 2 clusters
   if( Is_fat32 )
   {
      u32_nb_free_cluster = fat_read_fat32_FSInfo();
      if( 0xFFFFFFFF != u32_nb_free_cluster )
         goto endof_fat_getfreespace_percent;
      u32_nb_free_cluster = 0;
      u16_pos = 2*4;
      for(  u16_tmp = fs_g_nav.u16_fat_size
      ;     u16_tmp!=0
      ;     u16_tmp-- )
      {
         for( ; u16_pos < 512 ; u16_pos += (2*4) )
         {
            if( 0 == fs_g_sector[u16_pos] )
               u32_nb_free_cluster+=2;
         }
         // Read next sector in FAT
         u16_pos = 0;
         fs_gu32_addrsector++;
         if( !fat_cache_read_sector( TRUE ))
            return 0;
      }
   }
   if ( Is_fat16 )
   {
      u16_pos = 2*2;
      for(  u16_tmp = fs_g_nav.u16_fat_size
      ;     u16_tmp!=0
      ;     u16_tmp-- )
      {
         for( ; u16_pos < 512 ; u16_pos += (2*2) )
         {
            if( 0 == fs_g_sector[u16_pos] )
               u32_nb_free_cluster+=2;
         }
         // Read next sector in FAT
         u16_pos = 0;
         fs_gu32_addrsector++;
         if( !fat_cache_read_sector( TRUE ))
            return 0;
      }
   }
   // Compute percent
   if( u32_nb_free_cluster > fs_g_nav.u32_CountofCluster )
      return 100;
   if( u32_nb_free_cluster > ((fs_g_nav.u32_CountofCluster-u32_nb_free_cluster)/256) )
   {
      // Compute and add a delta error
      u32_nb_free_cluster -= ((fs_g_nav.u32_CountofCluster-u32_nb_free_cluster)/256);
   }
endof_fat_getfreespace_percent:
   return ((u32_nb_free_cluster * 100) / fs_g_nav.u32_CountofCluster);
}
Bool fat_initialize_dir (void)
This function writes the directory information.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_seg.u32_addr          cluster value of a directory
//! OUT:
//!   update the sector cache with init directory datas
//!
Definition at line 1181 of file fat_unusual.c.
References fat_cache_mark_sector_as_dirty(), fat_clear_cluster(), FS_ATTR_DIRECTORY, fs_g_nav, fs_g_nav_entry, fs_g_sector, FS_SIZE_FILE_ENTRY, Fs_management_entry::u32_cluster, and Fs_management::u32_cluster_sel_dir.
Referenced by nav_dir_make().
{
   U8 u8_i;
   // Clear the cluster corresponding at directory
   if( !fat_clear_cluster())
      return FALSE;
   fat_cache_mark_sector_as_dirty();
   // here, the internal cache is the first sector of the cluster
   // Create the dot "." entry, this one is a directory that points to itself
   fs_g_sector[0]='.';
   for( u8_i=1 ; u8_i<11 ; u8_i++ )
      fs_g_sector[u8_i]=' ';
   fs_g_sector[11]=FS_ATTR_DIRECTORY;
   fs_g_sector[26]= LSB0( fs_g_nav_entry.u32_cluster );
   fs_g_sector[27]= LSB1( fs_g_nav_entry.u32_cluster );
   fs_g_sector[20]= LSB2( fs_g_nav_entry.u32_cluster );
   fs_g_sector[21]= LSB3( fs_g_nav_entry.u32_cluster );
   // Create the dotdot ".." entry, this one points to the starting cluster of the parent directory
   fs_g_sector[FS_SIZE_FILE_ENTRY+0]='.';
   fs_g_sector[FS_SIZE_FILE_ENTRY+1]='.';
   for( u8_i=2 ; u8_i<11 ; u8_i++ )
      fs_g_sector[FS_SIZE_FILE_ENTRY+u8_i]=' ';
   fs_g_sector[FS_SIZE_FILE_ENTRY+11]=FS_ATTR_DIRECTORY;
   fs_g_sector[FS_SIZE_FILE_ENTRY+26]= LSB0( fs_g_nav.u32_cluster_sel_dir );
   fs_g_sector[FS_SIZE_FILE_ENTRY+27]= LSB1( fs_g_nav.u32_cluster_sel_dir );
   fs_g_sector[FS_SIZE_FILE_ENTRY+20]= LSB2( fs_g_nav.u32_cluster_sel_dir );
   fs_g_sector[FS_SIZE_FILE_ENTRY+21]= LSB3( fs_g_nav.u32_cluster_sel_dir );
   return TRUE;
}
#endif  // FS_LEVEL_FEATURES
void fat_invert_nav (U8 u8_idnav)
This function inverts the current navigation with another.
Parameters:
u8_idnav Id navigator to invert
Definition at line 1968 of file fat.c.
References fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, fs_g_navext, fs_g_navext_entry, and fs_g_navext_fast.
Referenced by nav_select().
{
   _MEM_TYPE_SLOW_ U8 Temp[Max(Max(sizeof(Fs_management),sizeof(Fs_management_entry)),sizeof(Fs_management_fast))];
   if( u8_idnav == 0 )
      return;
   u8_idnav--;
   memcpy_ram2ram(Temp,                              (U8*)&fs_g_nav,                     sizeof(Fs_management));
   memcpy_ram2ram((U8*)&fs_g_nav,                    (U8*)&fs_g_navext[u8_idnav],        sizeof(Fs_management));
   memcpy_ram2ram((U8*)&fs_g_navext[u8_idnav],       Temp,                               sizeof(Fs_management));
   memcpy_ram2ram(Temp,                              (U8*)&fs_g_nav_entry,               sizeof(Fs_management_entry));
   memcpy_ram2ram((U8*)&fs_g_nav_entry,              (U8*)&fs_g_navext_entry[u8_idnav],  sizeof(Fs_management_entry));
   memcpy_ram2ram((U8*)&fs_g_navext_entry[u8_idnav], Temp,                               sizeof(Fs_management_entry));
   memcpy_ram2ram(Temp,                              (U8*)&fs_g_nav_fast,                sizeof(Fs_management_fast));
   memcpy_ram2ram((U8*)&fs_g_nav_fast,               (U8*)&fs_g_navext_fast[u8_idnav],   sizeof(Fs_management_fast));
   memcpy_ram2ram((U8*)&fs_g_navext_fast[u8_idnav],  Temp,                               sizeof(Fs_management_fast));
}
Bool fat_mount (void)
This function mounts a partition.
This function mounts a partition.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variables used
//! IN :
//!   fs_g_nav.u8_lun            Indicate the drive to mount
//!   fs_g_nav.u8_partition      Indicate the partition to mount (if FS_MULTI_PARTITION =  ENABLED)
//! OUT:
//!   fs_g_nav                   update structure
//! If the FS_MULTI_PARTITION option is disabled
//! then the mount routine selects the first partition supported by file system. <br>
//!
Definition at line 105 of file fat_unusual.c.
References fat_cache_read_sector(), fat_check_device(), fat_clear_entry_info_and_ptr(), FS_512B, FS_BR_SIGNATURE_HIGH, FS_BR_SIGNATURE_LOW, FS_ERR_NO_FORMAT, FS_ERR_NO_PART, FS_ERR_NO_SUPPORT_PART, FS_FAT12_MAX_CLUSTERS, FS_FAT16_MAX_CLUSTERS, fs_g_nav, fs_g_nav_fast, fs_g_sector, fs_g_status, fs_gu32_addrsector, FS_MBR_OFFSET_PART_ENTRY, FS_NB_FAT, FS_PART_BOOTABLE, FS_PART_NO_BOOTABLE, FS_PART_TYPE_FAT12, FS_PART_TYPE_FAT16_INF32M, FS_PART_TYPE_FAT16_SUP32M, FS_PART_TYPE_FAT16_SUP32M_BIS, FS_PART_TYPE_FAT32, FS_PART_TYPE_FAT32_BIS, FS_SIZE_FILE_ENTRY, FS_TYPE_FAT_12, FS_TYPE_FAT_16, FS_TYPE_FAT_32, FS_TYPE_FAT_UNM, HIGH_16_BPB_BytsPerSec, HIGH_16_BPB_FATSz16, HIGH_16_BPB_ResvSecCnt, HIGH_16_BPB_RootEntCnt, HIGH_16_BPB_TotSec16, LOW0_32_BPB_FATSz32, LOW0_32_BPB_RootClus, LOW0_32_BPB_TotSec32, LOW1_32_BPB_FATSz32, LOW1_32_BPB_RootClus, LOW1_32_BPB_TotSec32, LOW2_32_BPB_FATSz32, LOW2_32_BPB_RootClus, LOW2_32_BPB_TotSec32, LOW3_32_BPB_FATSz32, LOW3_32_BPB_RootClus, LOW3_32_BPB_TotSec32, LOW_16_BPB_FATSz16, LOW_16_BPB_FSInfo, LOW_16_BPB_ResvSecCnt, LOW_16_BPB_RootEntCnt, LOW_16_BPB_TotSec16, mem_sector_size(), Fs_management::rootdir, Fs_rootdir::seg, Fs_management::u16_fat_size, Fs_management::u16_offset_FSInfo, Fs_rootdir::u16_pos, Fs_rootdir::u16_size, Fs_rootdir::u32_cluster, Fs_management::u32_cluster_sel_dir, Fs_management::u32_CountofCluster, Fs_management::u32_offset_data, Fs_management::u32_ptr_fat, U8_BPB_SecPerClus, Fs_management::u8_BPB_SecPerClus, Fs_management::u8_lun, Fs_management::u8_partition, and Fs_management_fast::u8_type_fat.
Referenced by fat_check_mount(), nav_drive_format(), and nav_partition_mount().
{
   U8  u8_sector_size;
   U8  u8_tmp;
   U16 u16_tmp;
   U32 u32_tmp;
   // Select the root directory
   fs_g_nav.u32_cluster_sel_dir   = 0;
   // No selected file
   fat_clear_entry_info_and_ptr();
   fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_UNM;
   fs_gu32_addrsector = 0;    // Start read at the beginning of memory
   // Check if the drive is availabled
   if( !fat_check_device() )
      return FALSE;
   while( 1 )  // Search a valid partition
   {
      // Read one sector
      if( !fat_cache_read_sector( TRUE ))
         return FALSE;
      // Check PBR/MBR signature
      if ( (fs_g_sector[510] != FS_BR_SIGNATURE_LOW  )
      &&   (fs_g_sector[511] != FS_BR_SIGNATURE_HIGH ) )
      {
         fs_g_status = FS_ERR_NO_FORMAT;
         return FALSE;
      }
      if ( 0 == fs_gu32_addrsector )
      {
         //** first sector then check a MBR structure
         // Search the first partition supported
#if (FS_MULTI_PARTITION == ENABLED)
         u16_tmp=0;  // Init to "no valid partition found"
#endif
         for( u8_tmp=0 ; u8_tmp!=4 ; u8_tmp++ )
         {
            // The first sector must be a MBR, then check the partition entry in the MBR
            if ( ((fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+0] == FS_PART_BOOTABLE             )||
                  (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+0] == FS_PART_NO_BOOTABLE          )  )
            &&   ((fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+4] == FS_PART_TYPE_FAT12           )||
                  (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+4] == FS_PART_TYPE_FAT16_INF32M    )||
                  (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+4] == FS_PART_TYPE_FAT16_SUP32M    )||
                  (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+4] == FS_PART_TYPE_FAT16_SUP32M_BIS)||
                  (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+4] == FS_PART_TYPE_FAT32           )||
                  (fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+4] == FS_PART_TYPE_FAT32_BIS       )) )
            {
               // A valid partition is found
#if (FS_MULTI_PARTITION == ENABLED)
               if( u16_tmp == fs_g_nav.u8_partition )
                  break;   // The selected partition is valid
               u16_tmp++;
#else
               break;
#endif
            }
         }
         if( u8_tmp != 4 )
         {
            // Partition found -> Get partition position (unit sector) at offset 8
            LSB0(fs_gu32_addrsector) = fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+8];
            LSB1(fs_gu32_addrsector) = fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+9];
            LSB2(fs_gu32_addrsector) = fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+10];
            LSB3(fs_gu32_addrsector) = fs_g_sector[FS_MBR_OFFSET_PART_ENTRY(u8_tmp)+11];
            fs_gu32_addrsector *= mem_sector_size( fs_g_nav.u8_lun );
            continue;   // Go to check PBR of partition
         }
         // No MBR found then check PBR
#if (FS_MULTI_PARTITION == ENABLED)
         // The device don't have mutli partition, but only one
         if ( 0 != fs_g_nav.u8_partition )
         {
            fs_g_status = FS_ERR_NO_PART;
            return FALSE;
         }
#endif
      }
      //** Check a PBR structure
      if ( (fs_g_sector[0] == 0xEB) &&          // PBR Byte 0
           (fs_g_sector[2] == 0x90) &&          // PBR Byte 2
           ((fs_g_sector[21] & 0xF0) == 0xF0) ) // PBR Byte 21 : Media byte
      {
         break;   // valid PBR found
      }
      // PBR not found
      fs_g_status = FS_ERR_NO_PART;
      return FALSE;
   }
   fs_g_status = FS_ERR_NO_SUPPORT_PART;  // by default partition no supported
   // Get sector size of File System (unit 512B)
   // To translate from sector disk unit to sector 512B unit
   u8_sector_size = HIGH_16_BPB_BytsPerSec/2;
   // Read BPB_SecPerClus (unit sector)
   fs_g_nav.u8_BPB_SecPerClus = U8_BPB_SecPerClus * u8_sector_size;
   //** FAT Type determination (algorithm of "Hardware White Paper FAT")
   // Get FAT size (unit sector)
   LSB( u16_tmp ) = LOW_16_BPB_FATSz16;
   MSB( u16_tmp ) = HIGH_16_BPB_FATSz16;
   if ( 0==u16_tmp )
   {
      LSB( u16_tmp ) = LOW0_32_BPB_FATSz32;
      MSB( u16_tmp ) = LOW1_32_BPB_FATSz32;
      // a large FAT32 isn't supported by this file system
      if( (0 != LOW2_32_BPB_FATSz32 )
      ||  (0 != LOW3_32_BPB_FATSz32 ) )
      {
         return FALSE;
      }
   }
   fs_g_nav.u16_fat_size = u16_tmp * u8_sector_size;
   // Get total count of sectors in partition
   if ( (0==LOW_16_BPB_TotSec16) && (0==HIGH_16_BPB_TotSec16) )
   {
      LSB0( u32_tmp ) = LOW0_32_BPB_TotSec32;
      LSB1( u32_tmp ) = LOW1_32_BPB_TotSec32;
      LSB2( u32_tmp ) = LOW2_32_BPB_TotSec32;
      LSB3( u32_tmp ) = LOW3_32_BPB_TotSec32;
   }
   else
   {
      LSB0( u32_tmp ) = LOW_16_BPB_TotSec16;
      LSB1( u32_tmp ) = HIGH_16_BPB_TotSec16;
      LSB2( u32_tmp ) = 0;
      LSB3( u32_tmp ) = 0;
   }
   u32_tmp *= u8_sector_size;   // Translate from sector disk unit to sector 512B unit
   // Compute the offset (unit 512B) between the end of FAT (beginning of root dir in FAT1x) and the beginning of PBR
   fs_g_nav.rootdir.seg.u16_pos = FS_NB_FAT * fs_g_nav.u16_fat_size;
   // Compute the root directory size (unit sector), for FAT32 is always 0
   LSB( u16_tmp ) = LOW_16_BPB_RootEntCnt;
   MSB( u16_tmp ) = HIGH_16_BPB_RootEntCnt;
   fs_g_nav.rootdir.seg.u16_size = ((u16_tmp * FS_SIZE_FILE_ENTRY) + ((FS_512B*u8_sector_size)-1)) / (FS_512B*u8_sector_size);
   fs_g_nav.rootdir.seg.u16_size *= u8_sector_size;
   // Get number of reserved sector
   LSB( u16_tmp ) = LOW_16_BPB_ResvSecCnt;
   MSB( u16_tmp ) = HIGH_16_BPB_ResvSecCnt;
   // Get FSInfo position
   fs_g_nav.u16_offset_FSInfo = (u16_tmp-LOW_16_BPB_FSInfo)*u8_sector_size;
   u16_tmp *= u8_sector_size; // number of reserved sector translated in unit 512B
   // Compute the FAT address (unit 512B)
   fs_g_nav.u32_ptr_fat = fs_gu32_addrsector + u16_tmp;
   // Compute the offset (unit 512B) between the first data cluster and the FAT beginning
   fs_g_nav.u32_offset_data = (FS_NB_FAT * (U32)fs_g_nav.u16_fat_size) + (U32)fs_g_nav.rootdir.seg.u16_size;
   // Compute the data region (clusters space = Total - Sector used) size (unit 512B)
   u32_tmp -= ((U32)u16_tmp + fs_g_nav.u32_offset_data);
   // Compute the count of CLUSTER in the data region
   // !!!Optimization -> u32_CountofCluster (unit 512B)/ fs_g_nav.u8_BPB_SecPerClus (unit 512B & power of 2)
   if (!fs_g_nav.u8_BPB_SecPerClus)
     return FALSE;
   for( u8_tmp = fs_g_nav.u8_BPB_SecPerClus; u8_tmp!=1 ; u8_tmp >>= 1 )
   {
     u32_tmp  >>= 1;   // This computation round down
   }
   fs_g_nav.u32_CountofCluster = u32_tmp+2; // The total of cluster include the two reserved clusters
   // Determine the FAT type
   if (u32_tmp < FS_FAT12_MAX_CLUSTERS)
   {
      // Is FAT 12
#if (FS_FAT_12 == DISABLED)
      return FALSE;
#endif
      fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_12;
   } else {
   if (u32_tmp < FS_FAT16_MAX_CLUSTERS)
   {
      // Is FAT 16
#if (FS_FAT_16 == DISABLED)
      return FS_NO_SUPPORT_PART;
#endif
      fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_16;
   } else {
      // Is FAT 32
#if (FS_FAT_32 == DISABLED)
      return FALSE;
#endif
      fs_g_nav_fast.u8_type_fat = FS_TYPE_FAT_32;
      // In FAT32, the root dir is like another directory, this one have a cluster list
      // Get the first cluster number of root
      LSB0( fs_g_nav.rootdir.u32_cluster ) = LOW0_32_BPB_RootClus;
      LSB1( fs_g_nav.rootdir.u32_cluster ) = LOW1_32_BPB_RootClus;
      LSB2( fs_g_nav.rootdir.u32_cluster ) = LOW2_32_BPB_RootClus;
      LSB3( fs_g_nav.rootdir.u32_cluster ) = LOW3_32_BPB_RootClus;
   }
   }
   return TRUE;
}
Bool fat_read_dir (void)
This function fill the internal cache with a sector from current directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variable used
//! IN :
//!   fs_g_nav.u32_cluster_sel_dir           First cluster of current directory
//!   fs_g_nav_fast.u16_entry_pos_sel_file   Position in directory (unit entry)
//!
Definition at line 1195 of file fat.c.
References fat_cache_read_sector(), fat_cluster_list(), FS_512B_SHIFT_BIT, FS_CLUST_ACT_ONE, fs_g_nav, fs_g_nav_fast, fs_g_sectorcache, fs_g_seg, fs_gu32_addrsector, FS_SHIFT_B_TO_FILE_ENTRY, Fs_management_fast::u16_entry_pos_sel_file, Fs_segment::u32_addr, Fs_management::u32_cluster_sel_dir, Fs_sector_cache::u32_clusterlist_pos, Fs_sector_cache::u32_clusterlist_start, Fs_segment::u32_size_or_pos, Fs_management::u8_lun, and Fs_sector_cache::u8_lun.
Referenced by fat_alloc_entry_free(), fat_create_entry_file_name(), fat_delete_file(), fat_find_short_entry_name(), fat_garbage_collector_entry(), file_close(), nav_dir_gotoparent(), nav_dir_make(), nav_file_attributset(), nav_file_checkext(), nav_file_dateget(), nav_file_dateset(), nav_file_name(), nav_file_rename(), nav_filelist_set(), nav_filterlist_gotoparent(), and nav_partition_label().
{
   U32 u32_cluster_pos;
   // Compute the cluster list position corresponding of the current entry
   u32_cluster_pos = fs_g_nav_fast.u16_entry_pos_sel_file >> (FS_512B_SHIFT_BIT - FS_SHIFT_B_TO_FILE_ENTRY);
   if( (fs_g_sectorcache.u8_lun                 == fs_g_nav.u8_lun )
   &&  (fs_g_sectorcache.u32_clusterlist_start  == fs_g_nav.u32_cluster_sel_dir )
   &&  (fs_g_sectorcache.u32_clusterlist_pos    == u32_cluster_pos ) )
   {
         return TRUE;      // The internal cache contains the sector ascked
   }
   // Get sector address corresponding at cluster list position
   fs_g_seg.u32_addr = fs_g_nav.u32_cluster_sel_dir;
   fs_g_seg.u32_size_or_pos = u32_cluster_pos;
   if( fat_cluster_list( FS_CLUST_ACT_ONE, FALSE ) )
   {
      // Read the sector
      fs_gu32_addrsector = fs_g_seg.u32_addr;
      if( fat_cache_read_sector( TRUE ) )
      {
         // Update information about internal sector cache
         fs_g_sectorcache.u32_clusterlist_start  = fs_g_nav.u32_cluster_sel_dir;
         fs_g_sectorcache.u32_clusterlist_pos    = u32_cluster_pos;
         return TRUE;
      }
   }
   return FALSE;
}
U32 fat_read_fat32_FSInfo (void)
This function returns the space free in the selected FAT32 partition.
Returns:
the number of sector free (if 0xFFFFFFFF, then no value available in FSInfo Sector)
Definition at line 888 of file fat_unusual.c.
References const_FSI_LeadSig, const_FSI_StrucSig, fat_cache_read_sector(), FS_BR_SIGNATURE_HIGH, FS_BR_SIGNATURE_LOW, fs_g_nav, fs_g_sector, fs_gu32_addrsector, Fs_management::u16_offset_FSInfo, and Fs_management::u32_ptr_fat.
Referenced by fat_getfreespace(), and fat_getfreespace_percent().
{
   U32 u32_nb_free_cluster;
   // Read FAT32 FSInfo Sector
   fs_gu32_addrsector = fs_g_nav.u32_ptr_fat - fs_g_nav.u16_offset_FSInfo;
   if( !fat_cache_read_sector( TRUE ))
      return 0xFFFFFFFF;
   //* Check signature
   // offset 510-511, Signature
   if( fs_g_sector[510] != FS_BR_SIGNATURE_LOW )
      return 0xFFFFFFFF;
   if( fs_g_sector[511] != FS_BR_SIGNATURE_HIGH)
      return 0xFFFFFFFF;
   // offset 00-04, This lead signature
   if( 0 != memcmp_code2ram( &fs_g_sector[0], const_FSI_LeadSig, sizeof(const_FSI_LeadSig) ))
      return 0xFFFFFFFF;
   // offset 004-483, reserved (fill with 0)
   // offset 484-487, signature
   if( 0 != memcmp_code2ram( &fs_g_sector[484], const_FSI_StrucSig, sizeof(const_FSI_StrucSig)) )
      return 0xFFFFFFFF;
   //* Read value
   // offset 488-491, free cluster count
   LSB0(u32_nb_free_cluster) = fs_g_sector[488];
   LSB1(u32_nb_free_cluster) = fs_g_sector[489];
   LSB2(u32_nb_free_cluster) = fs_g_sector[490];
   LSB3(u32_nb_free_cluster) = fs_g_sector[491];
   return u32_nb_free_cluster;
}
#endif  // FS_FAT_32
Bool fat_read_file (U8 mode)
This function gets or clears a cluster list at the current position in the selected file.
Parameters:
mode Choose action
FS_CLUST_ACT_SEG Get memory segment corresponding at the position in selected file
FS_CLUST_ACT_ONE Store in internal cache the sector corresponding at the position in selected file
FS_CLUST_ACT_CLR Clear the cluster list corresponding at the position in selected file
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variable used
//! IN :
//!   fs_g_nav_entry.u32_cluster       First cluster of selected file
//!   fs_g_nav_entry.u32_pos_in_file   Position in file (unit byte)
//!
Definition at line 1035 of file fat.c.
References fat_cache_read_sector(), fat_cluster_list(), FS_512B_MASK, FS_512B_SHIFT_BIT, FS_CLUST_ACT_CLR, FS_CLUST_ACT_ONE, FS_CLUST_ACT_SEG, FS_ERR_OUT_LIST, fs_g_nav, fs_g_nav_entry, fs_g_sectorcache, fs_g_seg, fs_g_status, fs_gu32_addrsector, Fs_segment::u32_addr, Fs_management_entry::u32_cluster, Fs_sector_cache::u32_clusterlist_pos, Fs_sector_cache::u32_clusterlist_start, Fs_management_entry::u32_pos_in_file, Fs_segment::u32_size_or_pos, Fs_management::u8_lun, and Fs_sector_cache::u8_lun.
Referenced by fat_delete_file(), fat_write_file(), file_getc(), file_read(), file_read_buf(), and file_set_eof().
{
   U32   u32_sector_pos;
   // Compute sector position
   u32_sector_pos = fs_g_nav_entry.u32_pos_in_file >> FS_512B_SHIFT_BIT;
   if(FS_CLUST_ACT_ONE  == mode)
   {
      if( (fs_g_sectorcache.u8_lun                 == fs_g_nav.u8_lun )
      &&  (fs_g_sectorcache.u32_clusterlist_start  == fs_g_nav_entry.u32_cluster )
      &&  (fs_g_sectorcache.u32_clusterlist_pos    == u32_sector_pos ) )
      {
         return TRUE;      // The internal cache contains the sector ascked
      }
   }
   else
   {
      if( FS_CLUST_ACT_CLR == mode )
      {
         // Clear cluster list
         if( 0 == fs_g_nav_entry.u32_cluster )
            return TRUE;   // No cluster list is linked with the file, then no clear is necessary
         if(0 != (fs_g_nav_entry.u32_pos_in_file & FS_512B_MASK) )
         {
            // The actual sector is used, then start clear on the next sector
            u32_sector_pos++;
         }
      }
   }
   // Get the segment which start at the current position
   fs_g_seg.u32_addr = fs_g_nav_entry.u32_cluster;
   fs_g_seg.u32_size_or_pos = u32_sector_pos;
   if( FS_CLUST_ACT_ONE != mode )
   {
      if( fat_cluster_list( mode, TRUE ) )
         return TRUE;      // Get or clear segment OK
   }
   else
   {
      if( fat_cluster_list( FS_CLUST_ACT_SEG, TRUE ) )   // Read all segment
      {
         // Read the sector corresponding at the position file (= first sector of segment)
         fs_gu32_addrsector = fs_g_seg.u32_addr ;
         if( fat_cache_read_sector( TRUE ) )
         {
            fs_g_sectorcache.u32_clusterlist_start  = fs_g_nav_entry.u32_cluster;
            fs_g_sectorcache.u32_clusterlist_pos    = u32_sector_pos;
            return TRUE;
         }
      }
   }
   if( (FS_CLUST_ACT_CLR == mode       )
   &&  (FS_ERR_OUT_LIST  == fs_g_status) )
   {
      // It is possible to clear nothing
      return TRUE;
   }
   return FALSE;
}
Bool fat_serialnumber (Bool b_action, U8 _MEM_TYPE_SLOW_ * a_u8_sn)
This function reads or writes a serial number.
This function reads or writes a serial number.
Parameters:
b_action choose action (FS_SN_READ or FS_SN_WRITE)
a_u8_sn array to store or get the serial number (U8[4])
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 1044 of file fat_unusual.c.
References fat_cache_flush(), fat_cache_mark_sector_as_dirty(), fat_cache_read_sector(), fs_g_nav, fs_g_sector, fs_gu32_addrsector, FS_SN_READ, Is_fat12, Is_fat16, and Fs_management::u32_ptr_fat.
Referenced by nav_partition_serialnumber().
{
   // Compute PBR address
   if ( Is_fat12 || Is_fat16 )
   {  // FAT 12 & 16 (BPB_ResvSecCnt must be ega to 1)
      fs_gu32_addrsector = fs_g_nav.u32_ptr_fat-1;
   }
   else
   {  // FAT 32 (BPB_ResvSecCnt must be ega to 32)
      fs_gu32_addrsector = fs_g_nav.u32_ptr_fat-32;
   }
   // Read PBR
   if( !fat_cache_read_sector( TRUE ))
      return FALSE;
   // The serial is storaged at invert
   if( b_action == FS_SN_READ )
   {
      // Read serial number
      a_u8_sn[0] = fs_g_sector[42];
      a_u8_sn[1] = fs_g_sector[41];
      a_u8_sn[2] = fs_g_sector[40];
      a_u8_sn[3] = fs_g_sector[39];
      return TRUE;
   }else{
      // Write serial number
      fs_g_sector[42] = a_u8_sn[0];
      fs_g_sector[41] = a_u8_sn[1];
      fs_g_sector[40] = a_u8_sn[2];
      fs_g_sector[39] = a_u8_sn[3];
      fat_cache_mark_sector_as_dirty();
      return fat_cache_flush();
   }
}
void fat_set_date (const FS_STRING sz_date, Bool type_date)
This function changes the date information.
Parameters:
type_date choose date field (FS_DATE_LAST_WRITE or FS_DATE_CREATION)
sz_date table with date information
storage format (ASCII) = "YYYYMMDDHHMMSSMS" = year, month, day, hour, minute, seconde, miliseconde
//! OUT, update cache sector with the new date
//!
Definition at line 1349 of file fat_unusual.c.
References fat_cache_mark_sector_as_dirty(), fat_get_ptr_entry(), fat_translatedate_ascii_to_number(), and FS_DATE_LAST_WRITE.
Referenced by nav_file_dateset().
{
   PTR_CACHE ptr_entry;
   fat_cache_mark_sector_as_dirty();
   ptr_entry = fat_get_ptr_entry();
   if( FS_DATE_LAST_WRITE == type_date )
   {
      fat_translatedate_ascii_to_number( sz_date , &ptr_entry[22] , FALSE );
   }
   else
   {
      fat_translatedate_ascii_to_number( sz_date , &ptr_entry[13] , TRUE );
   }
}
Bool fat_update_fat2 (void)
This function copys the modifications of the first FAT to the second FAT.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 2439 of file fat_unusual.c.
References fat_cache_mark_sector_as_dirty(), fat_cache_read_sector(), fs_g_nav, fs_g_u16_first_mod_fat, fs_g_u16_last_mod_fat, fs_gu32_addrsector, Fs_management::u16_fat_size, and Fs_management::u32_ptr_fat.
Referenced by fat_allocfreespace(), and fat_cluster_list().
{
  while( fs_g_u16_first_mod_fat <= fs_g_u16_last_mod_fat )
  {
     // Compute the modification position of FAT 1
     fs_gu32_addrsector = fs_g_nav.u32_ptr_fat + fs_g_u16_first_mod_fat;
     // Read FAT1
      if( !fat_cache_read_sector( TRUE ))
         return FALSE;
     // Compute the modification position of FAT 2
     fs_gu32_addrsector = fs_g_nav.u32_ptr_fat + ((U32)fs_g_u16_first_mod_fat + fs_g_nav.u16_fat_size);
     // Init the sector FAT2 with the previous sector of the FAT1
     if( !fat_cache_read_sector( FALSE ))
         return FALSE;
     // Flag the sector FAT2 like modify
     fat_cache_mark_sector_as_dirty();
     fs_g_u16_first_mod_fat++;
  }
  return TRUE;
}
#endif  // FS_LEVEL_FEATURES
void fat_write_entry_file (void)
This function writes the information about selected file.
//! Global variable used
//! IN :
//!   fs_g_sector       The directory sector corresponding at the current position
//!   fs_g_nav_fast.u16_entry_pos_sel_file    Position in directory of the entry file (unit entry)
//! OUT:
//!   fs_g_sector    Updated
//!
Write the attribut
Write the size of file
Definition at line 1421 of file fat.c.
References fat_cache_mark_sector_as_dirty(), fat_get_ptr_entry(), FS_ATTR_DIRECTORY, fs_g_nav_entry, Fs_management_entry::u32_cluster, Fs_management_entry::u32_size, and Fs_management_entry::u8_attr.
Referenced by file_close(), nav_dir_make(), nav_file_attributset(), and nav_file_rename().
{
   PTR_CACHE ptr_entry;
   fat_cache_mark_sector_as_dirty();
   ptr_entry = fat_get_ptr_entry();
   if( !(FS_ATTR_DIRECTORY | fs_g_nav_entry.u8_attr))
   {
      if( 0 == fs_g_nav_entry.u32_size )
         fs_g_nav_entry.u32_cluster = 0;
   }
   ptr_entry+= 11;
   ptr_entry[0] = fs_g_nav_entry.u8_attr;
   // Write the first cluster of file cluster list
   ptr_entry += (20-11);
   ptr_entry[0] = LSB2(fs_g_nav_entry.u32_cluster);
   ptr_entry[1] = LSB3(fs_g_nav_entry.u32_cluster);
   ptr_entry += (26-20);
   ptr_entry[0] = LSB0(fs_g_nav_entry.u32_cluster);
   ptr_entry[1] = LSB1(fs_g_nav_entry.u32_cluster);
   ptr_entry += (28-26);
   ptr_entry[0] = LSB0(fs_g_nav_entry.u32_size);
   ptr_entry[1] = LSB1(fs_g_nav_entry.u32_size);
   ptr_entry[2] = LSB2(fs_g_nav_entry.u32_size);
   ptr_entry[3] = LSB3(fs_g_nav_entry.u32_size);
}
Bool fat_write_fat32_FSInfo (U32 u32_nb_free_cluster)
This function writes the space free number in selected FAT32 partition.
Read global value "fs_g_status" in case of error : FS_ERR_HW Hardware driver error FS_ERR_HW_NO_PRESENT Device not present FS_LUN_WP Drive is read only
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 853 of file fat_unusual.c.
References const_FSI_LeadSig, const_FSI_StrucSig, fat_cache_clear(), fat_cache_mark_sector_as_dirty(), fat_cache_read_sector(), FS_BR_SIGNATURE_HIGH, FS_BR_SIGNATURE_LOW, fs_g_nav, fs_g_sector, fs_gu32_addrsector, Fs_management::u16_offset_FSInfo, and Fs_management::u32_ptr_fat.
Referenced by fat_allocfreespace(), fat_cluster_list(), fat_getfreespace(), and fat_write_PBR().
{
   // Init sector
   fs_gu32_addrsector = fs_g_nav.u32_ptr_fat - fs_g_nav.u16_offset_FSInfo;
   if( !fat_cache_read_sector( FALSE ))
      return FALSE;
   fat_cache_mark_sector_as_dirty();
   fat_cache_clear();
   // Fill sector
   // offset 00-04, This lead signature
   memcpy_code2ram( &fs_g_sector[0], const_FSI_LeadSig, sizeof(const_FSI_LeadSig) );
   // offset 004-483, reserved (fill with 0)
   // offset 484-487, signature
   memcpy_code2ram( &fs_g_sector[484], const_FSI_StrucSig, sizeof(const_FSI_StrucSig) );
   // offset 488-491, free cluster count (by default NO value)
   fs_g_sector[488] = LSB0(u32_nb_free_cluster);
   fs_g_sector[489] = LSB1(u32_nb_free_cluster);
   fs_g_sector[490] = LSB2(u32_nb_free_cluster);
   fs_g_sector[491] = LSB3(u32_nb_free_cluster);
   // offset 492-495, indicates the cluster number at which the driver should start looking for free clusters (by default NO value)
   memset( &fs_g_sector[492] , 0xFF , 4 );
   // offset 496-509, reserved (fill with 0)
   // offset 510-511, Signature
   fs_g_sector[510] = FS_BR_SIGNATURE_LOW;
   fs_g_sector[511] = FS_BR_SIGNATURE_HIGH;
   return TRUE;
}
Bool fat_write_file (U8 mode, U32 u32_nb_sector_write)
This function gets and eventually allocs a cluster list at the current position in the selected file.
Parameters:
mode Choose action
FS_CLUST_ACT_SEG Get and eventuelly alloc a cluster list
FS_CLUST_ACT_ONE Get and eventually alloc a cluster list for one sector, and load this sector in internal cache
u32_nb_sector_write maximum number of sector to get and eventually to alloc for the selected file (ignored if mode = FS_CLUST_ACT_ONE)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! Global variable used
//! IN :
//!   fs_g_nav_entry.u32_cluster       First cluster of selected file
//!   fs_g_nav_entry.u32_pos_in_file   Position in the file (unit byte)
//!
Definition at line 1117 of file fat.c.
References fat_allocfreespace(), fat_cache_clusterlist_update_finish(), fat_cache_clusterlist_update_start(), fat_read_file(), FS_CLUST_ACT_SEG, FS_ERR_OUT_LIST, fs_g_cache_clusterlist, fs_g_nav, fs_g_nav_entry, fs_g_seg, fs_g_status, fs_g_u8_current_cache, Fs_segment::u32_addr, Fs_clusterlist_cache::u32_cluster, Fs_management_entry::u32_cluster, Fs_management::u32_offset_data, Fs_management::u32_ptr_fat, Fs_segment::u32_size_or_pos, Fs_clusterlist_cache::u32_start, Fs_management::u8_BPB_SecPerClus, and Fs_clusterlist_cache::u8_lun.
Referenced by file_putc(), file_write(), and file_write_buf().
{
   if( 0 == fs_g_nav_entry.u32_cluster )
   {
      // File don't have a cluster list, then alloc the first cluster list of the file
      MSB0(fs_g_seg.u32_addr)    = 0xFF;     // It is a new cluster list
      // Update cluster list caches
      // fs_g_cluster.u32_pos    = ?         // To fill after alloc
      fs_g_seg.u32_size_or_pos   = 0;
      fat_cache_clusterlist_update_start(TRUE);
   }
   else
   {
      if( fat_read_file( mode ) )
         return TRUE;      // A segment is availabled (no alloc necessary)
      if( FS_ERR_OUT_LIST != fs_g_status )
      {
         return FALSE;     // Error system
      }
      // fat_read_file is outsize the list then the current cluster list cache contains the last cluster
      // Initialize cluster list caches before alloc routine
      fs_g_cache_clusterlist[fs_g_u8_current_cache].u8_lun       = 0xFF;                     // unvalid cache
      // fs_g_cache_clusterlist[fs_g_u8_current_cache].u32_cluster  = fs_g_cluster.u32_pos;  // it is the same
      fs_g_cache_clusterlist[fs_g_u8_current_cache].u32_start += fs_g_nav.u8_BPB_SecPerClus; // Position of next cluster (the first new)
   }
   // Alloc a cluster list
   if( FS_CLUST_ACT_SEG == mode )
   {
      fs_g_seg.u32_size_or_pos = u32_nb_sector_write;
   }else{
      fs_g_seg.u32_size_or_pos = 1;                                                          // only one sector
   }
   //note: fs_g_seg.u32_addr is already initialized with the last cluster value (see fat_cluster_list())
   if( !fat_allocfreespace())
      return FALSE;
   //note: fs_g_seg.u32_addr is the first cluster of the cluster list allocated by alloc_free_space()
   //note: fs_g_seg.u32_size_or_pos = number of sectors remaining
   if( 0 == fs_g_nav_entry.u32_cluster )
   {
      // It is the first cluster list of file, then update following values in cluster list cache
      // fs_g_seg.u32_addr = already contzins the first cluster of the file (see alloc_free_space())
      fs_g_cache_clusterlist[fs_g_u8_current_cache].u32_cluster = fs_g_seg.u32_addr;
      // Update file entry
      fs_g_nav_entry.u32_cluster = fs_g_seg.u32_addr;
   }
   // Update cluster list cache
   if( FS_CLUST_ACT_SEG == mode )
   {
      fs_g_seg.u32_size_or_pos = u32_nb_sector_write - fs_g_seg.u32_size_or_pos;
   }else{
      fs_g_seg.u32_size_or_pos = 1 - fs_g_seg.u32_size_or_pos;
   }
   fs_g_seg.u32_addr = ((fs_g_seg.u32_addr - 2) * fs_g_nav.u8_BPB_SecPerClus)
                     + fs_g_nav.u32_ptr_fat + fs_g_nav.u32_offset_data;
   fat_cache_clusterlist_update_finish();
   return fat_read_file( mode );    // load the new cluster list
}
Variable Documentation
_GLOBEXT_ _MEM_TYPE_FAST_ Fs_cluster fs_g_cluster
To take time in functions: fat_getfreespace, fat_cluster_list, fat_cluster_val, fat_checkcluster.
Definition at line 403 of file fat.h.
Referenced by fat_allocfreespace(), fat_cache_clusterlist_update_read(), fat_cache_clusterlist_update_start(), fat_checkcluster(), fat_cluster_list(), fat_cluster_readnext(), fat_cluster_val(), fat_getfreespace(), and fat_getfreespace_percent().
_GLOBEXT_ _MEM_TYPE_SLOW_ Fs_management fs_g_nav
Definition at line 394 of file fat.h.
Referenced by fat_allocfreespace(), fat_cache_clusterlist_update_finish(), fat_cache_clusterlist_update_read(), fat_cache_read_sector(), fat_check_device(), fat_check_nav_access_disk(), fat_check_nav_access_file(), fat_clean_zone(), fat_clear_cluster(), fat_clear_entry_info_and_ptr(), fat_cluster_list(), fat_cluster_val(), fat_copy_nav(), fat_format(), fat_getfreespace(), fat_getfreespace_percent(), fat_initialize_dir(), fat_initialize_fat(), fat_invert_nav(), fat_mount(), fat_read_dir(), fat_read_fat32_FSInfo(), fat_read_file(), fat_select_filesystem(), fat_serialnumber(), fat_update_fat2(), fat_write_fat32_FSInfo(), fat_write_file(), fat_write_PBR(), file_load_segment_value(), file_open(), file_read(), file_read_buf(), file_write_buf(), nav_dir_cd(), nav_dir_gotoparent(), nav_dir_is_root(), nav_dir_name(), nav_drive_get(), nav_drive_getname(), nav_drive_set(), nav_file_create(), nav_file_isreadonly(), nav_file_rename(), nav_filelist_eol(), nav_filelist_exist(), nav_filelist_first(), nav_filelist_get(), nav_filelist_nb(), nav_filelist_set(), nav_filelist_single_disable(), nav_filelist_single_enable(), nav_filterflat_cd(), nav_filterflat_get(), nav_filterflat_gotoparent(), nav_filterflat_mount(), nav_filterflat_next(), nav_filterflat_previous(), nav_filterflat_reset(), nav_filterflat_root(), nav_filterlist_cd(), nav_filterlist_get(), nav_filterlist_goto(), nav_filterlist_gotoindex(), nav_filterlist_gotoparent(), nav_filterlist_mount(), nav_filterlist_nb_ex(), nav_filterlist_next(), nav_filterlist_previous(), nav_filterlist_reset(), nav_filterlist_root(), nav_filterlist_setfilter(), nav_flat_cd(), nav_flat_get(), nav_flat_gotoparent(), nav_flat_mount(), nav_flat_next(), nav_flat_previous(), nav_flat_reset(), nav_flat_root(), nav_getindex(), nav_gotoindex(), nav_partition_cluster_size(), nav_partition_mount(), nav_partition_set(), nav_partition_space(), and nav_reset().
_GLOBEXT_ _MEM_TYPE_SLOW_ Fs_management_entry fs_g_nav_entry
Definition at line 396 of file fat.h.
Referenced by fat_clear_entry_info_and_ptr(), fat_copy_nav(), fat_delete_file(), fat_entry_is_dir(), fat_get_entry_info(), fat_initialize_dir(), fat_invert_nav(), fat_read_file(), fat_write_entry_file(), fat_write_file(), file_bof(), file_close(), file_eof(), file_flush(), file_getc(), file_getpos(), file_open(), file_putc(), file_read(), file_read_buf(), file_seek(), file_set_eof(), file_write(), file_write_buf(), nav_dir_cd(), nav_dir_gotoparent(), nav_dir_make(), nav_dir_name(), nav_file_attributget(), nav_file_attributset(), nav_file_create(), nav_file_isreadonly(), nav_file_lgt(), nav_file_lgtsector(), nav_file_rename(), nav_filterlist_gotoparent(), reader_txt_beg(), reader_txt_get_line(), reader_txt_new(), and reader_txt_select_format().
_GLOBEXT_ _MEM_TYPE_FAST_ Fs_management_fast fs_g_nav_fast
Definition at line 395 of file fat.h.
Referenced by fat_alloc_entry_free(), fat_allocfreespace(), fat_check_device(), fat_check_mount(), fat_check_nav_access_file(), fat_check_noopen(), fat_check_select(), fat_clear_entry_info_and_ptr(), fat_copy_nav(), fat_create_entry_file_name(), fat_delete_file(), fat_find_short_entry_name(), fat_garbage_collector_entry(), fat_get_ptr_entry(), fat_invert_nav(), fat_mount(), fat_read_dir(), fat_select_filesystem(), nav_dir_cd(), nav_dir_gotoparent(), nav_dir_name(), nav_drive_set(), nav_file_name(), nav_file_rename(), nav_filelist_eol(), nav_filelist_set(), nav_filterlist_gotoindex(), nav_filterlist_gotoparent(), nav_getindex(), nav_gotoindex(), nav_partition_freespace(), nav_partition_freespace_percent(), nav_partition_label(), nav_partition_mount(), nav_partition_set(), nav_partition_space(), nav_partition_type(), and nav_reset().
_GLOBEXT_ _MEM_TYPE_SLOW_ U8 fs_g_sector[FS_CACHE_SIZE]
Use "FAT sector cache" to store a sector from a file (see file_putc(), file_getc(), file_read_buf(), file_write_buf()).
Definition at line 415 of file fat.h.
Referenced by fat_cache_clear(), fat_cache_flush(), fat_cache_read_sector(), fat_clean_zone(), fat_cluster_readnext(), fat_cluster_val(), fat_get_nbpartition(), fat_get_ptr_entry(), fat_getfreespace_percent(), fat_initialize_dir(), fat_initialize_fat(), fat_mount(), fat_read_fat32_FSInfo(), fat_serialnumber(), fat_write_fat32_FSInfo(), fat_write_MBR(), and fat_write_PBR().
_GLOBEXT_ _MEM_TYPE_SLOW_ Fs_sector_cache fs_g_sectorcache
Definition at line 416 of file fat.h.
Referenced by fat_cache_flush(), fat_cache_mark_sector_as_dirty(), fat_cache_read_sector(), fat_cache_reset(), fat_check_device(), fat_read_dir(), and fat_read_file().
_GLOBEXT_ _MEM_TYPE_FAST_ Fs_segment fs_g_seg
Variable frequently used by many function (optimization, no parameter in function).
Definition at line 400 of file fat.h.
Referenced by fat_alloc_entry_free(), fat_allocfreespace(), fat_cache_clusterlist_update_finish(), fat_cache_clusterlist_update_read(), fat_cache_clusterlist_update_start(), fat_clear_cluster(), fat_cluster_list(), fat_read_dir(), fat_read_file(), fat_write_file(), file_load_segment_value(), file_read(), file_read_buf(), file_write(), file_write_buf(), and nav_dir_make().
_GLOBEXT_ _MEM_TYPE_SLOW_ U16 fs_g_u16_first_mod_fat
Offset (unit 512B) in fat of the first sector (unit 512B).
Definition at line 408 of file fat.h.
Referenced by fat_clear_info_fat_mod(), fat_cluster_val(), and fat_update_fat2().
_GLOBEXT_ _MEM_TYPE_SLOW_ U16 fs_g_u16_last_mod_fat
Offset (unit 512B) in fat of the last sector (unit 512B).
Definition at line 409 of file fat.h.
Referenced by fat_clear_info_fat_mod(), fat_cluster_val(), and fat_update_fat2().
_GLOBEXT_ _MEM_TYPE_SLOW_ U32 fs_gu32_addrsector
Store the address of futur cache (unit 512B).
Definition at line 417 of file fat.h.
Referenced by fat_cache_read_sector(), fat_clean_zone(), fat_clear_cluster(), fat_cluster_readnext(), fat_cluster_val(), fat_get_nbpartition(), fat_getfreespace_percent(), fat_initialize_fat(), fat_mount(), fat_read_dir(), fat_read_fat32_FSInfo(), fat_read_file(), fat_serialnumber(), fat_update_fat2(), fat_write_fat32_FSInfo(), fat_write_MBR(), fat_write_PBR(), and file_write_buf().
_GLOBEXT_ Bool g_b_no_check_disk
Variables to enable/disable the disk check before each action on disk.
Definition at line 390 of file fat.h.
Referenced by fat_check_device(), nav_checkdisk_disable(), nav_checkdisk_enable(), and nav_reset().
_GLOBEXT_ Bool g_b_string_length
Variables to select LENGTH string mode (initialised in nav_reset()).
Definition at line 387 of file fat.h.
Referenced by fat_entry_longname(), fat_entry_shortname(), nav_dir_name(), nav_file_name(), nav_getcwd(), nav_reset(), nav_string_length_disable(), and nav_string_length_enable().
_GLOBEXT_ Bool g_b_unicode
Variables to select string format (initialised in nav_reset()).
Definition at line 385 of file fat.h.
Referenced by nav_reset(), nav_string_ascii(), and nav_string_unicode().