AVR32 UC3 - FSACCESS Services: nav_filterlist.h File Reference
nav_filterlist.h File Reference
Detailed Description
FAT 12/16/32 Services.
This plug-in allow a navigation in filter mode This plug-in is connected on the navigation module. The filter mode includes in the file list directories and only files corresponding at a extension
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file nav_filterlist.h.
#include "fs_com.h"
Enumerations
enum fl_type_t { FL_FILE, FL_DIR, FL_ALL }
Functions
Bool nav_filterlist_cd (void)
This function enters in the selected directory.
Bool nav_filterlist_findname (const FS_STRING sz_name, Bool b_match_case)
This function searches a file name in file list filtered.
U16 nav_filterlist_get (void)
This function returns the position of selected file in filtered file list.
Bool nav_filterlist_goto (U16 u16_newpos)
This function goes to a position in filtered file list.
Bool nav_filterlist_gotoindex (const Fs_index _MEM_TYPE_SLOW_ *index)
This function selects a file in the navigator via a file index.
Bool nav_filterlist_gotoparent (void)
This function goes to at the parent directory.
Bool nav_filterlist_mount (void)
This function mounts the selected partition.
U16 nav_filterlist_nb (fl_type_t fl_type, const FS_STRING sz_filterext)
This function computes the number of files and/or directories in filtered file list This function is blocking.
Bool nav_filterlist_nb_ex (fl_type_t fl_type, const FS_STRING sz_filterext, U16 *p_total, U8 retry)
This function computes the number of files and/or directories in filtered file list This function is not blocking.
Bool nav_filterlist_next (void)
This function goes to the next position in the filtered file list.
Bool nav_filterlist_previous (void)
This function goes to the previous position in filtered file list.
Bool nav_filterlist_reset (void)
This function resets the pointer of selection, so "no file selected" in filtered file list.
Bool nav_filterlist_root (void)
This function initializes the file filtered list on the root directory.
void nav_filterlist_setfilter (const FS_STRING sz_filterext)
This function affiliates an extension filter at current navigator.
Enumeration Type Documentation
enum fl_type_t
Enumerator:
FL_FILE
FL_DIR
FL_ALL
Definition at line 50 of file nav_filterlist.h.
{
  FL_FILE,
  FL_DIR,
  FL_ALL
} fl_type_t;
Function Documentation
Bool nav_filterlist_cd (void)
This function enters in the selected directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After this routine the file list changes and contains the files and directories of the new directory.
//! By default no file is selected.
//!
Definition at line 366 of file nav_filterlist.c.
References fs_g_nav, FS_NO_SEL, nav_dir_cd(), and Fs_management::u16_pos_filterlist.
{
   fs_g_nav.u16_pos_filterlist = FS_NO_SEL;
   return nav_dir_cd();
}
Bool nav_filterlist_findname (const FS_STRING sz_name, Bool b_match_case)
This function searches a file name in file list filtered.
Parameters:
sz_name name to search (UNICODE or ASCII)
The name must end with NULL or '*' value
b_match_case FALSE to ignore the case
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! This function starts a search at the next position of the current in filtered file list
//!
Definition at line 193 of file nav_filterlist.c.
References FS_NAME_CHECK, nav_file_name(), and nav_filterlist_next().
{
   while( 1 )
   {
      if ( !nav_filterlist_next())
         return FALSE;
      if ( nav_file_name( sz_name , 0 , FS_NAME_CHECK , b_match_case ))
         return TRUE;
   }
}
U16 nav_filterlist_get (void)
This function returns the position of selected file in filtered file list.
Returns:
position of selected file in directory (0 is the first position)
FS_NO_SEL, in case of no file selected
Definition at line 139 of file nav_filterlist.c.
References fs_g_nav, and Fs_management::u16_pos_filterlist.
Referenced by nav_filterflat_get(), nav_filterflat_next(), and nav_filterflat_previous().
{
   return fs_g_nav.u16_pos_filterlist;
}
Bool nav_filterlist_goto (U16 u16_newpos)
This function goes to a position in filtered file list.
Parameters:
u16_newpos new position to select (0 is the first position)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 152 of file nav_filterlist.c.
References fs_g_nav, FS_NO_SEL, nav_filterlist_next(), nav_filterlist_previous(), nav_filterlist_reset(), and Fs_management::u16_pos_filterlist.
Referenced by nav_filterlist_nb_ex().
{
   if (u16_newpos == FS_NO_SEL)
     return nav_filterlist_reset();
   if( u16_newpos < (fs_g_nav.u16_pos_filterlist/2) )
   {
      // Restart at the beginning of list to accelerate search
      if( !nav_filterlist_reset() )
         return FALSE;
   }
   if( FS_NO_SEL == fs_g_nav.u16_pos_filterlist )
      if( !nav_filterlist_next() )
         return FALSE;  // No file available
   while( u16_newpos > fs_g_nav.u16_pos_filterlist )
   {
      if( !nav_filterlist_next() )
         break;
   }
   while( u16_newpos < fs_g_nav.u16_pos_filterlist )
   {
      if( !nav_filterlist_previous() )
         break;
   }
   return (u16_newpos == fs_g_nav.u16_pos_filterlist);
}
Bool nav_filterlist_gotoindex (const Fs_index _MEM_TYPE_SLOW_ * index)
This function selects a file in the navigator via a file index.
Parameters:
index structure with information about file to select (disk, partition, dir, file/dir selected)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! This routine allow to reinit a navigator quickly via a file index (disk, partition, dir, file/dir selected)
//! To get a file index, you shall used the routine nav_getindex().
//!
Definition at line 432 of file nav_filterlist.c.
References fs_g_nav, fs_g_nav_fast, nav_drive_set(), nav_filterlist_next(), nav_filterlist_reset(), nav_partition_mount(), nav_partition_set(), Fs_management_fast::u16_entry_pos_sel_file, and Fs_management::u32_cluster_sel_dir.
{
   if( !nav_drive_set( index->u8_lun ))
      return FALSE;
#if (FS_MULTI_PARTITION  ==  ENABLED)
   if( !nav_partition_set(index->u8_partition))
      return FALSE;
#endif
   if( !nav_partition_mount())
      return FALSE;
    // Initialization of the current entry file with index information
   fs_g_nav.u32_cluster_sel_dir   = index->u32_cluster_sel_dir;
   // Reset position
   if ( !nav_filterlist_reset() )
      return FALSE;
   // Research the index in directory
   while( fs_g_nav_fast.u16_entry_pos_sel_file != index->u16_entry_pos_sel_file )
   {
      if( !nav_filterlist_next() )
      {
         nav_filterlist_reset();
         return FALSE;
      }
   }
   return TRUE;
}
Bool nav_filterlist_gotoparent (void)
This function goes to at the parent directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After, the filtered file list changes and contains the files and directories of the new directory.
//! By default, the file selected in filtered file list is the previous (children) directory.
//!
Definition at line 383 of file nav_filterlist.c.
References fat_check_mount_noopen(), fat_get_entry_info(), fat_read_dir(), FS_ERR_FS, FS_ERR_IS_ROOT, fs_g_nav, fs_g_nav_entry, fs_g_nav_fast, fs_g_status, nav_filterlist_next(), nav_filterlist_reset(), Fs_management_fast::u16_entry_pos_sel_file, Fs_management_entry::u32_cluster, and Fs_management::u32_cluster_sel_dir.
Referenced by nav_filterflat_next(), and nav_filterflat_previous().
{
   U32 u32_cluster_old_dir;
   if (!fat_check_mount_noopen())
      return FALSE;
   if (0 == fs_g_nav.u32_cluster_sel_dir)
   {
      fs_g_status = FS_ERR_IS_ROOT;        // There aren't parent
      return FALSE;
   }
   // Select and read information about directory ".."
   fs_g_nav_fast.u16_entry_pos_sel_file = 1;
   if ( !fat_read_dir())
      return FALSE;
   fat_get_entry_info();
   // Save the children directory cluster
   u32_cluster_old_dir = fs_g_nav.u32_cluster_sel_dir;
   // Select the parent directory via information present in the current directory ".."
   fs_g_nav.u32_cluster_sel_dir = fs_g_nav_entry.u32_cluster;
   // Select the children directory in new directory (=parent directory)
   if( FALSE == nav_filterlist_reset())
      return FALSE;
   while( nav_filterlist_next() )
   {
      if (fs_g_nav_entry.u32_cluster == u32_cluster_old_dir)
         return TRUE;   // It is the children directory
   }
   fs_g_status = FS_ERR_FS;
   return FALSE;
}
Bool nav_filterlist_mount (void)
This function mounts the selected partition.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! If the FS_MULTI_PARTITION option is disabled
//! then the mount routine selects the first partition supported by file system. <br>
//! After mount, the file list contains files and directories of ROOT directory
//!
Definition at line 337 of file nav_filterlist.c.
References fs_g_nav, FS_NO_SEL, nav_partition_mount(), and Fs_management::u16_pos_filterlist.
Referenced by nav_filterflat_mount().
{
   fs_g_nav.u16_pos_filterlist = FS_NO_SEL;
   return nav_partition_mount();
}
U16 nav_filterlist_nb (fl_type_t fl_type, const FS_STRING sz_filterext)
This function computes the number of files and/or directories in filtered file list This function is blocking.
It will only return when the final count is computed, which may take some time.
Parameters:
fl_type FL_ALL To check all types (files and directories).
FL_DIR To check the directory presence.
FL_FILE To check the file presence.
sz_filterext Extension filter (ASCII format, e.g.: "txt" or "txt,d*,wk").
If this argument in NULL, then it uses the defautl filter used by the filterlist.
This argument is also ignored for b_type == FS_DIR.
Returns:
number of files and/or directories present in filtered file list.
Definition at line 219 of file nav_filterlist.c.
References nav_filterlist_nb_ex().
{
   U16 total=(U16)-1; // Initialization is mandatory
   while( !nav_filterlist_nb_ex( fl_type, sz_filterext, &total, 0 ) );
   return total;
}
Bool nav_filterlist_nb_ex (fl_type_t fl_type, const FS_STRING sz_filterext, U16 * p_total, U8 retry)
This function computes the number of files and/or directories in filtered file list This function is not blocking.
It will return after <retry> iteration if the result is not yet computed.
Parameters:
fl_type FL_ALL To check all types (files and directories).
FL_DIR To check the directory presence.
FL_FILE To check the file presence.
sz_filterext Extension filter (ASCII format, e.g.: "txt" or "txt,d*,wk").
If this argument in NULL, then it uses the defautl filter used by the filterlist.
This argument is also ignored for b_type == FS_DIR.
p_total Pointer to the result which will be updated by the function (added). Initialization shall be done before untering into this function.
retry Number of files seen before leaving the function. 0 means that the function is blocking untill the result is known.
Returns:
number of files and/or directories present in filtered file list.
Definition at line 257 of file nav_filterlist.c.
References FL_DIR, FL_FILE, FS_DIR, FS_FILE, FS_FIND_NEXT, fs_g_nav, FS_NO_SEL, nav_file_checkext(), nav_file_isdir(), nav_filelist_set(), nav_filelist_single_disable(), nav_filelist_single_enable(), nav_filterlist_goto(), nav_filterlist_reset(), Fs_management::sz_filterext, Fs_management::u16_pos_filterlist, and update_counter().
Referenced by nav_filterlist_nb().
{
   static U16   u16_save_position;
   Bool   b_is_dir;
   // save current position
   if( *p_total==(U16) -1 )
   {
      u16_save_position = fs_g_nav.u16_pos_filterlist;
      // Reset position
      if ( !nav_filterlist_reset())
         return TRUE;
      if (fl_type == FL_DIR)
        nav_filelist_single_enable(FS_DIR);
      else if (fl_type == FL_FILE)
        nav_filelist_single_enable(FS_FILE);
      *p_total = 0;
   }
   // Scan all
   while( nav_filelist_set( 0, FS_FIND_NEXT ) )
   {
      b_is_dir = nav_file_isdir();
      // Check if its a file for FL_FILE mode
      if (fl_type == FL_FILE && b_is_dir)
      {
        if (!update_counter(&retry))
          return FALSE;
        continue;
      }
      // Check if its a directory for FL_DIR mode
      if (fl_type == FL_DIR && !b_is_dir)
      {
        if (!update_counter(&retry))
          return FALSE;
        continue;
      }
      // If the selection is on a file
      if (!b_is_dir)
      {
        // Check the extension of the file
        if (!((sz_filterext)?nav_file_checkext(sz_filterext):nav_file_checkext(fs_g_nav.sz_filterext)))
          if (!update_counter(&retry))
            return FALSE;
      }
      (*p_total)++;
      if (!update_counter(&retry))
         return FALSE;
   }
   nav_filelist_single_disable();
   // Restore previous position
   if ( u16_save_position != FS_NO_SEL )
   {
      nav_filterlist_reset();
   }else{
      // After operation, there are a file selected
      nav_filterlist_goto( u16_save_position );
   }
   return TRUE;
}
Bool nav_filterlist_next (void)
This function goes to the next position in the filtered file list.
Returns:
FALSE in case of error or no next file, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 88 of file nav_filterlist.c.
References FS_FIND_NEXT, fs_g_nav, FS_NO_SEL, nav_file_checkext(), nav_file_isdir(), nav_filelist_get(), nav_filelist_goto(), nav_filelist_set(), Fs_management::sz_filterext, and Fs_management::u16_pos_filterlist.
Referenced by nav_filterflat_next(), nav_filterflat_previous(), nav_filterlist_findname(), nav_filterlist_goto(), nav_filterlist_gotoindex(), and nav_filterlist_gotoparent().
{
   U16 u16_current_pos;
   u16_current_pos = nav_filelist_get();
   while( nav_filelist_set( 0, FS_FIND_NEXT ) )
   {
      if( nav_file_isdir()
      ||  nav_file_checkext( fs_g_nav.sz_filterext ) )
      {
         if( FS_NO_SEL == u16_current_pos )
         {
            fs_g_nav.u16_pos_filterlist = 0;
         }else{
            fs_g_nav.u16_pos_filterlist++;
         }
         return TRUE;
      }
   }
   nav_filelist_goto( u16_current_pos );
   return FALSE;
}
Bool nav_filterlist_previous (void)
This function goes to the previous position in filtered file list.
Returns:
FALSE in case of an error or no next file, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 116 of file nav_filterlist.c.
References FS_FIND_PREV, fs_g_nav, nav_file_checkext(), nav_file_isdir(), nav_filelist_get(), nav_filelist_goto(), nav_filelist_set(), Fs_management::sz_filterext, and Fs_management::u16_pos_filterlist.
Referenced by nav_filterflat_previous(), and nav_filterlist_goto().
{
   U16 u16_current_pos;
   u16_current_pos = nav_filelist_get();
   while( nav_filelist_set( 0, FS_FIND_PREV ) )
   {
      if( nav_file_isdir()
      ||  nav_file_checkext( fs_g_nav.sz_filterext ) )
      {
         fs_g_nav.u16_pos_filterlist--;
         return TRUE;
      }
   }
   nav_filelist_goto( u16_current_pos );
   return FALSE;
}
Bool nav_filterlist_reset (void)
This function resets the pointer of selection, so "no file selected" in filtered file list.
Returns:
FALSE in case of an error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 76 of file nav_filterlist.c.
References fs_g_nav, FS_NO_SEL, nav_filelist_reset(), and Fs_management::u16_pos_filterlist.
Referenced by nav_filterflat_gotoparent(), nav_filterflat_reset(), nav_filterlist_goto(), nav_filterlist_gotoindex(), nav_filterlist_gotoparent(), nav_filterlist_nb_ex(), and nav_filterlist_setfilter().
{
   fs_g_nav.u16_pos_filterlist = FS_NO_SEL;
   return nav_filelist_reset();
}
Bool nav_filterlist_root (void)
This function initializes the file filtered list on the root directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 349 of file nav_filterlist.c.
References fs_g_nav, FS_NO_SEL, nav_dir_root(), and Fs_management::u16_pos_filterlist.
Referenced by nav_filterflat_root().
{
   fs_g_nav.u16_pos_filterlist = FS_NO_SEL;
   return nav_dir_root();
}
void nav_filterlist_setfilter (const FS_STRING sz_filterext)
This function affiliates an extension filter at current navigator.
Parameters:
sz_filterext extension filter (ASCII format, e.g.: "txt" or "txt,d*,wk")
Definition at line 64 of file nav_filterlist.c.
References fs_g_nav, nav_filterlist_reset(), and Fs_management::sz_filterext.
{
   fs_g_nav.sz_filterext = sz_filterext;
   nav_filterlist_reset();
}