AVR32 UC3 - FSACCESS Services: fsaccess_example.c File Reference
fsaccess_example.c File Reference
Detailed Description
File System access example application.
This file gives an example of using the FS access, through POSIX commands.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices can be used. The example is written for UC3 and EVK110x.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file fsaccess_example.c.
#include <string.h>
#include "compiler.h"
#include "preprocessor.h"
#include "board.h"
#include "print_funcs.h"
#include "power_clocks_lib.h"
#include "gpio.h"
#include "usart.h"
#include "spi.h"
#include "conf_at45dbx.h"
#include "fsaccess.h"
Defines
#define ABORT_CHAR CTRL_C
#define AT45DBX_ENABLE_NPCS_PIN(NPCS, unused) {AT45DBX_SPI_NPCS##NPCS##_PIN, AT45DBX_SPI_NPCS##NPCS##_FUNCTION},
#define BKSPACE_CHAR '\b'
#define CR '\r'
#define CTRL_C 0x03
#define CTRL_Q 0x11
#define LF '\n'
#define MSG_FILENAME "Enter the filename : "
#define MSG_MODE "\r\nWhat do you want to do ?\r\n\t1 - Read file\r\n\t2 - Concatenate a file to an existing one\r\n\t3 - Copy the content of a file to a new one\r\nenter your choice : "
#define MSG_WELCOME "\r\n ---------- Welcome to FSACCESS Example ---------- \r\n"
#define NB_SECTOR_TO_SEND 4
#define QUIT_APPEND CTRL_Q
#define TEST_FAIL "\t[FAIL]\n"
#define TEST_SUCCESS "\t[PASS]\n"
Functions
static void at45dbx_resources_init (void)
Initialize daflash memory AT45DBX resources: GPIO, SPI and AT45DBX.
void fsaccess_example_get_filename (char *buf)
Wait for user to enter a filename.
int fsaccess_example_get_mode (void)
Wait for user to select the mode he wants to test.
int fsaccess_example_read (char *path)
Read a file and display it to USART.
int fsaccess_example_write (char *source, char *destination, int flags)
Copy a file to another one.
int main (void)
Main function, execution starts here. RS232 is used to input/output information. The example lets you issue the following commands on RS232 using POSIX interfaces (open, read, write, close):
read a file from the memory files system;
concatenate a file to an existing one;
copy the content of a file to a new one.
Define Documentation
#define ABORT_CHAR CTRL_C
Definition at line 131 of file fsaccess_example.c.
Referenced by fsaccess_example_get_filename().
#define AT45DBX_ENABLE_NPCS_PIN (NPCS, unused) {AT45DBX_SPI_NPCS##NPCS##_PIN, AT45DBX_SPI_NPCS##NPCS##_FUNCTION},
Referenced by at45dbx_resources_init().
#define BKSPACE_CHAR '\b'
Definition at line 130 of file fsaccess_example.c.
Referenced by fsaccess_example_get_filename().
#define CR '\r'
Definition at line 126 of file fsaccess_example.c.
Referenced by fsaccess_example_get_filename().
#define CTRL_C 0x03
Definition at line 129 of file fsaccess_example.c.
#define CTRL_Q 0x11
Definition at line 128 of file fsaccess_example.c.
#define LF '\n'
Definition at line 127 of file fsaccess_example.c.
Referenced by fsaccess_example_get_filename(), fsaccess_example_get_mode(), and fsaccess_example_read().
#define MSG_FILENAME "Enter the filename : "
Definition at line 118 of file fsaccess_example.c.
Referenced by fsaccess_example_get_filename().
#define MSG_MODE "\r\nWhat do you want to do ?\r\n\t1 - Read file\r\n\t2 - Concatenate a file to an existing one\r\n\t3 - Copy the content of a file to a new one\r\nenter your choice : "
Definition at line 119 of file fsaccess_example.c.
Referenced by fsaccess_example_get_mode().
#define MSG_WELCOME "\r\n ---------- Welcome to FSACCESS Example ---------- \r\n"
Definition at line 117 of file fsaccess_example.c.
Referenced by main().
#define NB_SECTOR_TO_SEND 4
Definition at line 135 of file fsaccess_example.c.
Referenced by fsaccess_example_read(), and fsaccess_example_write().
#define QUIT_APPEND CTRL_Q
Definition at line 132 of file fsaccess_example.c.
#define TEST_FAIL "\t[FAIL]\n"
Definition at line 124 of file fsaccess_example.c.
#define TEST_SUCCESS "\t[PASS]\n"
Definition at line 123 of file fsaccess_example.c.
Function Documentation
static void at45dbx_resources_init (void) [static]
Initialize daflash memory AT45DBX resources: GPIO, SPI and AT45DBX.
Definition at line 149 of file fsaccess_example.c.
References AT45DBX_ENABLE_NPCS_PIN, AT45DBX_MEM_CNT, AT45DBX_SPI_BITS, AT45DBX_SPI_FIRST_NPCS, and AT45DBX_SPI_MASTER_SPEED.
Referenced by main().
{
  static const gpio_map_t AT45DBX_SPI_GPIO_MAP =
  {
    {AT45DBX_SPI_SCK_PIN,          AT45DBX_SPI_SCK_FUNCTION         },  // SPI Clock.
    {AT45DBX_SPI_MISO_PIN,         AT45DBX_SPI_MISO_FUNCTION        },  // MISO.
    {AT45DBX_SPI_MOSI_PIN,         AT45DBX_SPI_MOSI_FUNCTION        },  // MOSI.
#define AT45DBX_ENABLE_NPCS_PIN(NPCS, unused) \
    {AT45DBX_SPI_NPCS##NPCS##_PIN, AT45DBX_SPI_NPCS##NPCS##_FUNCTION},  // Chip Select NPCS.
    MREPEAT(AT45DBX_MEM_CNT, AT45DBX_ENABLE_NPCS_PIN, ~)
#undef AT45DBX_ENABLE_NPCS_PIN
  };
  // SPI options.
  spi_options_t spiOptions =
  {
    .reg          = AT45DBX_SPI_FIRST_NPCS,   // Defined in conf_at45dbx.h.
    .baudrate     = AT45DBX_SPI_MASTER_SPEED, // Defined in conf_at45dbx.h.
    .bits         = AT45DBX_SPI_BITS,         // Defined in conf_at45dbx.h.
    .spck_delay   = 0,
    .trans_delay  = 0,
    .stay_act     = 1,
    .spi_mode     = 0,
    .modfdis      = 1
  };
  // Assign I/Os to SPI.
  gpio_enable_module(AT45DBX_SPI_GPIO_MAP,
                     sizeof(AT45DBX_SPI_GPIO_MAP) / sizeof(AT45DBX_SPI_GPIO_MAP[0]));
  // Initialize as master.
  spi_initMaster(AT45DBX_SPI, &spiOptions);
  // Set selection mode: variable_ps, pcs_decode, delay.
  spi_selectionMode(AT45DBX_SPI, 0, 0, 0);
  // Enable SPI.
  spi_enable(AT45DBX_SPI);
  // Initialize data flash with SPI clock Osc0.
  at45dbx_init(spiOptions, FOSC0);
}
void fsaccess_example_get_filename (char * buf)
Wait for user to enter a filename.
Definition at line 298 of file fsaccess_example.c.
References ABORT_CHAR, BKSPACE_CHAR, CR, LF, and MSG_FILENAME.
Referenced by main().
{
unsigned long i_str = 3;
unsigned short file;
int c;
  // Display asking message
  print_dbg(MSG_FILENAME);
  file = FALSE;
  buf[0] = 'A';
  buf[1] = ':';
  buf[2] = '/';
  while (file == FALSE)
  {
    // If something new in the USART :
    usart_reset_status(DBG_USART);
    if (usart_read_char(DBG_USART, &c) == USART_SUCCESS)
    {
      // Regarding the received char :
      switch (c)
      {
      // This is a carriage return
      case CR:
        // Add LF
        print_dbg_char(LF);
        // Add NUL char
        buf[i_str] = '\0';
        // End the loop
        file = TRUE;
        // Reset string length
        i_str = 0;
      break;
      // This is a CTRL+C
      case ABORT_CHAR:
        i_str = 0;
        print_dbg_char(LF);       // Add LF
        print_dbg(MSG_FILENAME);
      break;
      // This is a backspace
      case BKSPACE_CHAR:
        if (i_str > 0)
        {
          // Echo the backspace
          print_dbg_char(c);
          // Echo a space
          print_dbg_char(' ');
          // Echo the backspace
          print_dbg_char(c);
          // Decrease string length
          i_str--;
        }
      break;
      // This is a char
      default:
        // Echo it
        print_dbg_char(c);
        // Append to cmd line and increase string length
        buf[i_str++] = c;
      break;
      }
    }
  }
}
int fsaccess_example_get_mode (void)
Wait for user to select the mode he wants to test.
Definition at line 275 of file fsaccess_example.c.
References LF, and MSG_MODE.
Referenced by main().
{
int c;
  // Display asking message
  print_dbg(MSG_MODE);
  while (TRUE)
  {
    // If something new in the USART :
    usart_reset_status(DBG_USART);
    if (usart_read_char(DBG_USART, &c) == USART_SUCCESS)
    {
      // Echo char
      print_dbg_char(c);
      // Add LF
      print_dbg_char(LF);
      return (c);
    }
  }
}
int fsaccess_example_read (char * path)
Read a file and display it to USART.
Definition at line 365 of file fsaccess_example.c.
References close(), FS_SIZE_OF_SECTOR, fsaccess_file_get_size(), LF, NB_SECTOR_TO_SEND, O_RDONLY, open(), and read().
Referenced by main().
{
char * ptrFile;
int fd, i;
long size;
  // Try to open the file
  if ((fd = open(path, O_RDONLY)) < 0)
  {
    // Display error message
    print_dbg(path);
    print_dbg(" : Open failed\n");
    return (-1);
  }
  // Get file size
  size = fsaccess_file_get_size(fd);
  // Display file size
  print_dbg("File size: ");
  print_dbg_ulong(size);
  print_dbg_char(LF);
  // Allocate a buffer
  ptrFile = malloc((NB_SECTOR_TO_SEND * FS_SIZE_OF_SECTOR) + 1);
  // Allocation fails
  if (ptrFile == NULL)
  {
    // Display error message
    print_dbg("Malloc failed\n");
  }
  else
  {
    // Try to perform a single access
    if ( size < (NB_SECTOR_TO_SEND * FS_SIZE_OF_SECTOR) )
    {
      if( read(fd, ptrFile, size) != size)
      {
         // Display error message
         print_dbg("Reading entire file failed\n");
      }
       else
       {
         // Add a null terminating char
         ptrFile[size] = '\0';
         // Display the buffer to user
         print_dbg(ptrFile);
       }
    }
    else
    {
      // Try to send the biggest frame contained in the file
      for (i = NB_SECTOR_TO_SEND ; i > 0 ; i--)
      {
        // Get sectors of maximum size
        while(size > i * FS_SIZE_OF_SECTOR)
        {
          // Get the data from file
          if( read(fd, ptrFile, i * FS_SIZE_OF_SECTOR) !=  i * FS_SIZE_OF_SECTOR)
          {
            // Display error message
            print_dbg("Reading file block failed\n");
            // Close file
            close(fd);
            return (-1);
          }
          // Add a null terminating character
          ptrFile[i * FS_SIZE_OF_SECTOR] = '\0';
          // Display buffer content to user
          print_dbg(ptrFile);
          // Decrease remaining size
          size -= (i * FS_SIZE_OF_SECTOR);
        }
      }
      // Finish with the few data remaining (less than 1 sector)
      if ( size > 0 )
      {
        // Get the data from filesystem
        if( read(fd, ptrFile, size) != size)
        {
          // Display error message
          print_dbg("Reading file end failed\n");
          // Close file
          close(fd);
          return (-1);
        }
        else
        {
          // Add a null terminating char
          ptrFile[size] = '\0';
          // Display the buffer to user
          print_dbg(ptrFile);
        }
      }
    }
    // Free the buffer
    free(ptrFile);
  }
  // Close file
  close(fd);
  return (0);
}
int fsaccess_example_write (char * source, char * destination, int flags)
Copy a file to another one.
Definition at line 470 of file fsaccess_example.c.
References close(), FS_SIZE_OF_SECTOR, fsaccess_file_get_size(), NB_SECTOR_TO_SEND, O_RDONLY, open(), read(), and write().
Referenced by main().
{
char * ptrFile;
int fd1, fd2, i;
long size;
int ErrorCode = -1;
  if ((fd1 = open(source, O_RDONLY)) < 0)
  {
    // Display error message
    print_dbg(source);
    print_dbg(": Open failed\n");
    return (ErrorCode);
  }
  if ((fd2 = open(destination, flags)) < 0)
  {
    // Display error message
    print_dbg(destination);
    print_dbg(": Open failed\n");
    return (ErrorCode);
  }
  // Get file size
  size = fsaccess_file_get_size(fd1);
  // Display file size
  print_dbg("Copying ");
  print_dbg_ulong(size);
  print_dbg(" Bytes\n");
  // Allocate a buffer
  ptrFile = malloc(NB_SECTOR_TO_SEND * FS_SIZE_OF_SECTOR);
  // Allocation fails
  if (ptrFile == NULL)
  {
    // Display error message
    print_dbg("Malloc failed\n");
    return (ErrorCode);
  }
  else
  {
    if ( size <= (NB_SECTOR_TO_SEND * FS_SIZE_OF_SECTOR) )
    {
      if ( read(fd1, ptrFile, size) != size )
      {
        // Display error message
        print_dbg("Reading entire file failed\n");
        // Escape
        goto close_end;
      }
      if ( write(fd2, ptrFile, size) != size )
      {
        // Display error message
        print_dbg("Writing entire file failed\n");
        // Escape
        goto close_end;
      }
    }
    else
    {
      // Try to send the biggest frame contained in the file
      for (i = NB_SECTOR_TO_SEND ; i > 0 ; i--)
      {
        // Get sectors of maximum size
        while(size > i * FS_SIZE_OF_SECTOR)
        {
          // Clear previous buffer
          memset(ptrFile, 0, NB_SECTOR_TO_SEND * FS_SIZE_OF_SECTOR);
          // Read the data from source file
          if( read(fd1, ptrFile, i * FS_SIZE_OF_SECTOR) !=  i * FS_SIZE_OF_SECTOR)
          {
            print_dbg("Reading file block failed\n");
            // Escape
            goto close_end;
          }
          // Write the data to destination file
          if ( write(fd2, ptrFile, i * FS_SIZE_OF_SECTOR) != i * FS_SIZE_OF_SECTOR )
          {
            print_dbg("Writing file block failed\n");
            // Escape
            goto close_end;
          }
          // Decrease remaining size
          size -= (i * FS_SIZE_OF_SECTOR);
        }
      }
      // Finish with the few data remaining (less than 1 sector)
      if ( size > 0 )
      {
        // Get the data from filesystem
        if( read(fd1, ptrFile, size) !=  size)
        {
          print_dbg("Reading file end failed\n");
          // Escape
          goto close_end;
        }
        if ( write(fd2, ptrFile, size) != size )
        {
          print_dbg("Writing file end failed\n");
          // Escape
          goto close_end;
        }
      }
    }
    // No error occurs here
    ErrorCode = 0;
  }
close_end:
  // Free the buffer
  free(ptrFile);
  // Close files
  close(fd1);
  close(fd2);
  return (ErrorCode);
}
int main (void)
Main function, execution starts here. RS232 is used to input/output information. The example lets you issue the following commands on RS232 using POSIX interfaces (open, read, write, close):
read a file from the memory files system;
concatenate a file to an existing one;
copy the content of a file to a new one.
Connect USART_1 to your serial port via a standard RS-232 D-SUB9 cable Set the following settings in your terminal of choice: 57600 8N1
Definition at line 204 of file fsaccess_example.c.
References at45dbx_resources_init(), b_fsaccess_init(), fsaccess_example_get_filename(), fsaccess_example_get_mode(), fsaccess_example_read(), fsaccess_example_write(), MSG_WELCOME, O_APPEND, and O_CREAT.
{
char filename1[90];
char filename2[90];
  // switch to external oscillator 0
  pcl_switch_to_osc(PCL_OSC0, FOSC0, OSC0_STARTUP);
  // initialize RS232 debug text output
  init_dbg_rs232(FOSC0);
  // initialize AT45DBX resources: GPIO, SPI and AT45DBX
  at45dbx_resources_init();
  // initialize FSACCESS mutex and navigators
  b_fsaccess_init();
  // Try to init data flash
  if (at45dbx_mem_check())
  {
    // display welcome message
    print_dbg(MSG_WELCOME);
  }
  else
  {
    // display error message
    print_dbg("Initialization failed\r\n");
    return (-1);
  }
  while (TRUE)
  {
    // check the user command
    switch (fsaccess_example_get_mode())
    {
    case '1':
      // Wait for a filename
      fsaccess_example_get_filename(filename1);
      // Read it and display the content
      fsaccess_example_read(filename1);
    break;
    case '2':
      // Wait for source filename
      print_dbg("Source : ");
      fsaccess_example_get_filename(filename1);
      // Wait for destination filename
      print_dbg("Destination : ");
      fsaccess_example_get_filename(filename2);
      // Write from source to destination (append to the existing file)
      fsaccess_example_write(filename1, filename2, O_APPEND);
    break;
    case '3':
      // Wait for source filename
      print_dbg("Source : ");
      fsaccess_example_get_filename(filename1);
      // Wait for destination filename
      print_dbg("Destination : ");
      fsaccess_example_get_filename(filename2);
      // Write from source to destination (append to the unexisting file)
      fsaccess_example_write(filename1, filename2, (O_CREAT | O_APPEND));
    break;
    default:
      // Display error message
      print_dbg("Wrong choice\r\n");
    break;
    }
  }
}