AVR32 UC3 - FSACCESS Services: nav_flat.h File Reference
nav_flat.h File Reference
Detailed Description
FAT 12/16/32 Services.
This plug-in allow a navigation in FLAT mode This plug-in is connected on the navigation module. The flat mode includes in the file list all directories and all files of the current directory AND the sub directories Before use the flat mode, you must call nav_partition_mount() to reset navigation
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file nav_flat.h.
#include "fs_com.h"
Functions
Bool nav_flat_cd (void)
This function enters in the selected directory in file list FLAT.
Bool nav_flat_fileisnotopen (void)
This function checks if no file is opened.
Bool nav_flat_findname (const FS_STRING sz_name, Bool b_match_case)
This function searchs a file name in file list FLAT.
U16 nav_flat_get (void)
This function returns the position of selected file in file list FLAT.
Bool nav_flat_goto (U16 u16_newpos)
This function goes to a position in file list FLAT.
Bool nav_flat_gotoparent (void)
This function goes to the parent directory.
Bool nav_flat_mount (void)
This function mounts the selected partition.
U16 nav_flat_nb (void)
This function computes the number of files and directories present in the file list FLAT.
Bool nav_flat_next (void)
Go to next file or directory in file list FLAT.
Bool nav_flat_previous (void)
Go to previous file or directory in file list FLAT.
Bool nav_flat_reset (void)
This function resets the selection pointer, so "no file is selected" in file list FLAT.
Bool nav_flat_root (void)
This function initializes the falt list on the root directory.
Bool nav_flat_validpos (void)
This function checks if a file is selected.
Function Documentation
Bool nav_flat_cd (void)
This function enters in the selected directory in file list FLAT.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 324 of file nav_flat.c.
References fs_g_nav, nav_dir_cd(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   if( !nav_dir_cd() )
      return FALSE;
   fs_g_nav.u8_flat_dir_level   = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   return TRUE;
}
Bool nav_flat_fileisnotopen (void)
This function checks if no file is opened.
Returns:
TRUE if no file is opened
FALSE if a file is opened
Definition at line 124 of file nav_flat.c.
References nav_filelist_fileisnotopen().
{
   return nav_filelist_fileisnotopen();
}
Bool nav_flat_findname (const FS_STRING sz_name, Bool b_match_case)
This function searchs a file name in file list FLAT.
Parameters:
sz_name name to search (UNICODE or ASCII)
It must be terminated by NULL or '*' value
b_match_case FALSE to ignore the case
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! This function starts a search at the next position of the current in file list
//!
Definition at line 278 of file nav_flat.c.
References FS_NAME_CHECK, nav_file_name(), and nav_flat_next().
{
   while( 1 )
   {
      if ( !nav_flat_next() )
         return FALSE;
      if ( nav_file_name( sz_name , 0 , FS_NAME_CHECK , b_match_case ))
         return TRUE;
   }
}
U16 nav_flat_get (void)
This function returns the position of selected file in file list FLAT.
Returns:
position of selected file (0 is the first position)
FS_NO_SEL, in case of no file selected
Definition at line 223 of file nav_flat.c.
References fs_g_nav, nav_filelist_get(), and Fs_management::u16_flat_pos_offset.
Referenced by nav_flat_goto(), and nav_flat_nb().
{
   return (fs_g_nav.u16_flat_pos_offset + nav_filelist_get());
}
Bool nav_flat_goto (U16 u16_newpos)
This function goes to a position in file list FLAT.
Parameters:
u16_newpos new position to select (0 is the first position)
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 236 of file nav_flat.c.
References nav_flat_get(), nav_flat_next(), nav_flat_previous(), nav_flat_reset(), and nav_flat_validpos().
Referenced by nav_flat_nb().
{
   if (u16_newpos < (nav_flat_get()/2))
   {
      // Restart at the beginning of list to accelerate the search
      if (!nav_flat_reset())
         return FALSE;
   }
   if (!nav_flat_validpos())
   {
      // Go to first position
      if (!nav_flat_next())
         return FALSE;  // Empty list
   }
   while(u16_newpos < nav_flat_get())
   {
      if( !nav_flat_previous())
         return FALSE; // Position error
   }
   while(u16_newpos > nav_flat_get())
   {
      if( !nav_flat_next())
         return FALSE; // End of the list, then the position is bad
   }
   return TRUE;
}
Bool nav_flat_gotoparent (void)
This function goes to the parent directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! After the selected file is the first entry of the new file list FLAT
//!
Definition at line 343 of file nav_flat.c.
References fs_g_nav, nav_dir_gotoparent(), nav_filelist_reset(), nav_flat_next(), nav_getindex(), nav_gotoindex(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   _MEM_TYPE_SLOW_ Fs_index index;
   index = nav_getindex();
   while( 0 != fs_g_nav.u8_flat_dir_level )
   {
      fs_g_nav.u8_flat_dir_level--;
      nav_dir_gotoparent();
   }
   if( !nav_dir_gotoparent() )
   {
      nav_gotoindex( &index );
      return FALSE;
   }
   // Go to at the beginning of FLAT list
   fs_g_nav.u8_flat_dir_level   = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   nav_filelist_reset();
   nav_flat_next();
   return TRUE;
}
Bool nav_flat_mount (void)
This function mounts the selected partition.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
//! If the FS_MULTI_PARTITION option is disabled
//! then the mount routine selects the first partition supported by file system. <br>
//! After mount, the file list contains files and directories of ROOT directory
//!
Definition at line 71 of file nav_flat.c.
References fs_g_nav, nav_partition_mount(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   fs_g_nav.u8_flat_dir_level = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   return nav_partition_mount();
}
U16 nav_flat_nb (void)
This function computes the number of files and directories present in the file list FLAT.
Returns:
number of files and directories present in the file list FLAT
Definition at line 294 of file nav_flat.c.
References nav_flat_get(), nav_flat_goto(), nav_flat_next(), and nav_flat_reset().
{
   U16   u16_save_position;
   U16   u16_number;
   // Save current position
   u16_save_position = nav_flat_get();
   // Reset position
   if ( !nav_flat_reset())
      return 0;
   // Scan all directories
   u16_number  = 0;
   while( nav_flat_next() )
   {
      u16_number++;
   }
   // Restore previous position
   nav_flat_goto( u16_save_position );
   return u16_number;
}
Bool nav_flat_next (void)
Go to next file or directory in file list FLAT.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 135 of file nav_flat.c.
References FS_FIND_NEXT, fs_g_nav, nav_dir_cd(), nav_dir_gotoparent(), nav_file_isdir(), nav_filelist_get(), nav_filelist_set(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
Referenced by nav_flat_findname(), nav_flat_goto(), nav_flat_gotoparent(), and nav_flat_nb().
{
   U16 u16_save_current_pos;
   u16_save_current_pos = nav_filelist_get();
   if( nav_file_isdir() )
   {
      // The current file is a dir then enter in this
      if( !nav_dir_cd() )
         return FALSE;
      if( nav_filelist_set( 0 , FS_FIND_NEXT ) )
      {
         // A file is present in this dir then valid the new position
         fs_g_nav.u8_flat_dir_level++;
         fs_g_nav.u16_flat_pos_offset += u16_save_current_pos+1;
         return TRUE;
      }else{
         // No file then return in parent dir
         if( !nav_dir_gotoparent() )
            return FALSE;  // Error
      }
   }
   // Find next file in the current dir or the parent dir
   while( !nav_filelist_set( 0 , FS_FIND_NEXT ) )
   {
      // End of the directory then goes to parent
      if( 0 == fs_g_nav.u8_flat_dir_level )
         return FALSE;  // End of list FLAT
      if( !nav_dir_gotoparent() )
         return FALSE;  // Error
      fs_g_nav.u8_flat_dir_level--;
   }
   fs_g_nav.u16_flat_pos_offset = (fs_g_nav.u16_flat_pos_offset +u16_save_current_pos +1) -nav_filelist_get();
   return TRUE;
}
Bool nav_flat_previous (void)
Go to previous file or directory in file list FLAT.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 177 of file nav_flat.c.
References FS_FIND_NEXT, FS_FIND_PREV, fs_g_nav, nav_dir_cd(), nav_dir_gotoparent(), nav_file_isdir(), nav_filelist_get(), nav_filelist_set(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
Referenced by nav_flat_goto().
{
   U16 u16_save_current_pos;
   u16_save_current_pos = nav_filelist_get();
   if( nav_filelist_set( 0 , FS_FIND_PREV ) )
   {
      while( 1 )
      {
         if( !nav_file_isdir() )
         {
            fs_g_nav.u16_flat_pos_offset = ((fs_g_nav.u16_flat_pos_offset +u16_save_current_pos) -nav_filelist_get()) -1;
            return TRUE;   // New valid position
         }
         // The selection is a dir then enter in this
         if( !nav_dir_cd() )
            return FALSE;
         if( !nav_filelist_set( 0 , FS_FIND_NEXT ) )
         {
            // The dir is empty then goes to the parent
            nav_dir_gotoparent();
            // The parent dir is the new selection
            fs_g_nav.u16_flat_pos_offset = ((fs_g_nav.u16_flat_pos_offset +u16_save_current_pos) -nav_filelist_get()) -1;
            return TRUE;
         }
         fs_g_nav.u8_flat_dir_level++;
         // Go to the end of dir
         while( nav_filelist_set( 0 , FS_FIND_NEXT ) );
      }
   }
   // Beginning of the directory then goes to parent directory
   if( 0 == fs_g_nav.u8_flat_dir_level )
      return FALSE;  // beginning of the file list FLAT
   if( !nav_dir_gotoparent() )
      return FALSE;
   fs_g_nav.u8_flat_dir_level--;
   fs_g_nav.u16_flat_pos_offset -= (nav_filelist_get()+1);
   return TRUE;
}
Bool nav_flat_reset (void)
This function resets the selection pointer, so "no file is selected" in file list FLAT.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 96 of file nav_flat.c.
References fs_g_nav, nav_dir_gotoparent(), nav_filelist_reset(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
Referenced by nav_flat_goto(), and nav_flat_nb().
{
   while( 0 != fs_g_nav.u8_flat_dir_level )
   {
      fs_g_nav.u8_flat_dir_level--;
      nav_dir_gotoparent();
   }
   fs_g_nav.u16_flat_pos_offset = 0;
   return nav_filelist_reset();
}
Bool nav_flat_root (void)
This function initializes the falt list on the root directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
This function initializes the falt list on the root directory.
Returns:
FALSE in case of error, see global value "fs_g_status" for more detail
TRUE otherwise
Definition at line 84 of file nav_flat.c.
References fs_g_nav, nav_dir_root(), Fs_management::u16_flat_pos_offset, and Fs_management::u8_flat_dir_level.
{
   fs_g_nav.u8_flat_dir_level = 0;
   fs_g_nav.u16_flat_pos_offset = 0;
   return nav_dir_root();
}
Bool nav_flat_validpos (void)
This function checks if a file is selected.
Returns:
TRUE if a file is selected
FALSE if no file is selected
Definition at line 113 of file nav_flat.c.
References nav_filelist_validpos().
Referenced by nav_flat_goto().
{
   return nav_filelist_validpos();
}